<div class="row-fluid">
    <div>
        <label>Categorias</label>
    </div>

    <div class="progress">
        <div
            class="progress-bar"
            role="progressbar"
            aria-valuenow="2"
            aria-valuemin="0"
            aria-valuemax="<?php echo $articulos["total"] ?>"
            style="min-width: 2em;
            width: 25%;">
            25%
        </div>
    </div>
    <button name="play-publish-publicacion" type="button" class="btn btn-success btn-small btn-next" value="">
        <i class="icon-play"></i>
        Publicar
    </button>
    <button name="pause-publish-publicacion" type="button" class="btn btn-success btn-small btn-next" value="">
        <i class="icon-stop"></i>
        Detener
    </button>
</div>
<script>

</script>