<?php if(isset($_SESSION["miSession"]["usuario"])) $usuario = $_SESSION["miSession"]["usuario"]; ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php $form->setAttribute('action', $this->url('usuarios', array('controller' => 'evaluacion', 'action' => 'add2'))); ?>
<?php
$form->setAttribute('method', 'post')
        ->setAttribute('id', 'form-add-evaluacion')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('enctype', 'multipart/form-data');
?>
<div class="page-header position-relative">
    <div data-target="#step-container" class="row-fluid hide" id="fuelux-wizard" style="display: block;">
        <ul class="wizard-steps">
            <li class="active" data-target="#step1" style="min-width: 25%; max-width: 25%;">
                <span class="step">1</span>
                <span class="title">Select Agent/Campaign</span>
            </li>

            <li class="" data-target="#step2" style="min-width: 25%; max-width: 25%;">
                <span class="step">2</span>
                <span class="title">Chose Agent record</span>
            </li>

            <li class="" data-target="#step3" style="min-width: 25%; max-width: 25%;">
                <span class="step">3</span>
                <span class="title">Evaluate topics</span>
            </li>

            <li data-target="#step4" style="min-width: 25%; max-width: 25%;">
                <span class="step">4</span>
                <span class="title">Send Evaluatin</span>
            </li>
        </ul>
    </div>
</div><!--/.page-header-->
<?php //die(var_dump($this->save)) ?>
<?php if ($this->save): ?>
    <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
            <i class="icon-remove"></i>
        </button>
        <i class="icon-ok green"></i>
        Evaluation Save
    </div>
    <script>
        $(document).ready(function() {
            $("input[name=nombre-categoria],input[orden-categoria]").val("");
        })
    </script>
<?php endif; ?>

<div class="row-fluid">
    
    <div class="span12">
        
        <?php echo $this->form()->openTag($form); ?>
                                            
                <?php $mensaje = $this->formElementErrors($form->get('campania-evaluacion')); ?>

                <div class="row-fluid control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
                                <label for="form-field-2" class="control-label">Campaigns</label>
                        <div class="controls">
                        <?php echo $this->formSelect($form->get('campania-evaluacion')); ?>
                                <span class="help-inline"><?php echo $mensaje ?></span>
                        </div>
                </div>

                <?php $mensaje = $this->formElementErrors($form->get('agentes-evaluacion')); ?>

                <div class="row-fluid control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
                                <label for="form-field-2" class="control-label">Agent</label>
                        <div class="controls">
                        <?php echo $this->formSelect($form->get('agentes-evaluacion')); ?>
                                <span class="help-inline"><?php echo $mensaje ?></span>
                        </div>
                </div>

                <?php $mensaje = $this->formElementErrors($form->get('audio-agent-evaluacion')); ?>

                <div class="row-fluid control-group ">
                    <label for="form-field-2" class="control-label">Call Date</label>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('fecha-llamada')->setAttribute("style","width: 220px")->setAttribute("class","span10 date-picker")->setAttribute("id","id-date-picker-1")->setAttribute("data-date-format","dd-mm-yyyy")); ?>
                        <span class="add-on">
                            <i class="icon-calendar"></i>
                        </span>
                    </div>
                </div>
        
                <div class="row-fluid control-group ">
                    <label for="form-field-2" class="control-label">Evaluation Date</label>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('fecha-evaluacion')->setAttribute("readonly","readonly")->setAttribute("value",date("Y-m-d"))); ?>
                    </div>
                </div>
       
                <div class="row-fluid control-group ">
                    <label for="form-field-2" class="control-label">Agente Evaluator</label>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('evaluador-evaluacion')->setAttribute("readonly","readonly")->setAttribute("value",$usuario->getNombre())); ?>
                        <input type="hidden" name ="id-evaluador-evaluacion" id="id-evaluador-evaluacion" value="<?php echo $usuario->getId()?>">
                        
                    </div>
                </div>
                
        <hr>
        
        <div class="form-actions">
            <?php echo $this->formButton()->openTag($form->get('send-evaluacion')) . '<i class="icon-arrow-right icon-on-right"></i>Next' . $this->formButton()->closeTag(); ?>
        </div>

        <?php echo $this->form()->closeTag() ?>

    </div>
</div><!--PAGE CONTENT ENDS-->
<div class="modal-loading" style="display: none"></div>
<script>
    $(document).ready(function(){
        $('.date-picker').datepicker().next().on(ace.click_event, function(){
                $(this).prev().focus();
        });
    });
</script>
<style>
    .form-actions{
        text-align: right;
    }
    .btn-success{
        padding: 5px 15px 6px;
    }
    .form-horizontal .form-actions{
        padding-left: 0 !important;
    }
</style>