<script src="<?php echo $this->basePath() ?>/assets/js/audiojs/audiojs/audio.min.js"></script>
<?php if (isset($_SESSION["miSession"]["usuario"])) $usuario = $_SESSION["miSession"]["usuario"]; ?>
<?php
$form = $this->form;
$form->prepare();
?>
<?php $form->setAttribute('action', $this->url('usuarios', array('controller' => 'evaluacion', 'action' => 'add3'))); ?>
<?php
$form->setAttribute('method', 'post')
        ->setAttribute('id', 'form-add-evaluacion')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('enctype', 'multipart/form-data');
?>
<div class="page-header position-relative">
    <div data-target="#step-container" class="row-fluid hide" id="fuelux-wizard" style="display: block;">
        <ul class="wizard-steps">
            <li class="" data-target="#step1" style="min-width: 25%; max-width: 25%;">
                <span class="step">1</span>
                <span class="title">Select Agent/Campaign</span>
            </li>

            <li class="active" data-target="#step2" style="min-width: 25%; max-width: 25%;">
                <span class="step">2</span>
                <span class="title">Chose Agent record</span>
            </li>

            <li data-target="#step3" style="min-width: 25%; max-width: 25%;">
                <span class="step">3</span>
                <span class="title">Evaluate topics</span>
            </li>

            <li data-target="#step4" style="min-width: 25%; max-width: 25%;">
                <span class="step">4</span>
                <span class="title">Send Evaluatin</span>
            </li>
        </ul>
    </div>
</div><!--/.page-header-->
<?php //die(var_dump($this->save)) ?>
<?php if ($this->save): ?>
    <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
            <i class="icon-remove"></i>
        </button>
        <i class="icon-ok green"></i>
        Evaluation Save
    </div>
    <script>
        $(document).ready(function() {
            $("input[name=nombre-categoria],input[orden-categoria]").val("");
        })
    </script>
<?php endif; ?>

<div class="row-fluid">

    <div class="span12">

        <?php echo $this->form()->openTag($form); ?>


        <table id="sample-table-1" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="center">

                    </th>
                    <th>Phone Number</th>
                    <th>Agent</th>
                    <th>Campaign ID / Queue</th>
                    <th>Call Date</th>
                    <th class="hidden-480">Length</th>
                    <th class="hidden-phone">
                        Term
                    </th>
                    <th>Disposition</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->table as $item): ?>

                    <tr>
                        <td class="center">
                            <label>
                                <input type="radio" name="audio-agent-evaluacion" value="<?php echo $item["filename"] ?>" calldate="<?php echo $item["Call Date"] ?>">
                                <span class="lbl"></span>
                            </label>
                        </td>

                        <td><?php echo $item["Phone Number"] ?></td>
                        <td class="hidden-480"><a href="#"><?php echo $item["Agent"] ?></a></td>
                        <td class="hidden-phone"><?php echo $item["Campaign ID / Queue"] ?></td>
                        <td class="hidden-phone"><?php echo $item["Call Date"] ?></td>
                        <td class="hidden-phone"><?php echo $item["Length"] ?></td>
                        <td class="hidden-phone"><?php echo $item["Term"] ?></td>
                        <td><?php echo $item["Disposition"] ?></td>
                        <td>
                            <button class="btn btn-play" 
                                    calldate="<?php echo $item["Call Date"] ?>" 
                                    campania="<?php echo $item["Campaign ID / Queue"] ?>" 
                                    agente="<?php echo $item["Agent"] ?>" 
                                    filename="<?php echo $item["filename"] ?>" >
                                <i class="icon-youtube-play"></i>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <input type="hidden" id="idCampania" value="<?php echo $this->idCampania ?>">
        <hr>

        <input type="hidden" name='campania-evaluacion' value="<?php echo $this->idCampania ?>">
        <input type="hidden" name='agentes-evaluacion' value="<?php echo $this->idAgente ?>">
        <input type="hidden" name='fecha-llamada' value="<?php echo $this->fechaLlamada ?>">
        <input type="hidden" name='hora-llamada' value="">
        <input type="hidden" name='fecha-evaluacion' value="<?php echo $this->fechaEvaluacion ?>">
        <input type="hidden" name='id-evaluador-evaluacion' value="<?php echo $this->idEvaluador ?>">

        <div class="form-actions">
            <button id="back" class="btn btn-prev">
                <i class="icon-arrow-left"></i>
                Prev
            </button>
            <?php echo $this->formButton()->openTag($form->get('send-evaluacion')) . '<i class="icon-arrow-right icon-on-right"></i>Next' . $this->formButton()->closeTag(); ?>
        </div>

        <?php echo $this->form()->closeTag() ?>

    </div>
</div><!--PAGE CONTENT ENDS-->
<div class="modal-loading" style="display: none"></div>
<div class="modal fade" id="test_modal">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>Record</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <a id="close-records" href="#" class="btn" data-dismiss="modal">Close</a>
    </div>
</div>
<script>
        $(document).ready(function() {
            
            $(document).on("click","input[name=audio-agent-evaluacion]",function(){
                var hora = $(this).attr("calldate");
                $("input[name=hora-llamada]").val(hora);
            });
        
            $(".btn-play").click(function(e) {
                e.preventDefault();

                var
                        calldate = $(this).attr("calldate"),
                        campania = $(this).attr("campania"),
                        agente = $(this).attr("agente"),
                        filename = $(this).attr("filename"),
                        idCampania = $("#idCampania").val();
                
                $.ajax({
                    url: "<?php echo $this->url("usuarios", array("controller" => "evaluacion", "action" => "getRecord")) ?>",
                    async: false,
                    data: {
                        calldate: calldate,
                        idCampania: idCampania,
                        campania: campania,
                        agente: agente,
                        filename: filename
                    },
                    success: function(data) {
                        $(".modal-body").html(data.html);
                    }
                })
                $('#test_modal').modal({
                    escapeClose: false,
                    clickClose: false,
                    fadeDuration: 1000,
                    fadeDelay: 0.10,
                });
            });

            $(document).on("click", "#close-records", function() {
                $(".modal-body").find("audio").attr("src", "");
            });

            $(document).on("click", ".close", function() {
                $(".modal-body").find("audio").attr("src", "");
            });

            $(document).on("click", ".modal-backdrop", function() {
                $(".modal-body").find("audio").attr("src", "");
            });
            $("#back").click(function(e){
               e.preventDefault();
               history.back(1)
            });
        });
</script>
<style>
    #test_modal{
        width: 490px;
    }
    .form-actions{
        text-align: right;
    }
    .btn-success{
        padding: 5px 15px 6px;
    }
    .form-horizontal .form-actions{
        padding-left: 0 !important;
    }
</style>