<script src="<?php echo $this->basePath() ?>/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/markdown/markdown.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/markdown/bootstrap-markdown.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/jquery.hotkeys.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/bootstrap-wysiwyg.min.js"></script>

                
<?php if(isset($_SESSION["miSession"]["usuario"])) $usuario = $_SESSION["miSession"]["usuario"]; ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php $form->setAttribute('action', $this->url('usuarios', array('controller' => 'evaluacion', 'action' => 'add4'))); ?>
<?php
    $form
    ->setAttribute('method', 'post')
    ->setAttribute('id', 'form-add-evaluacion')
    ->setAttribute('class', 'form-horizontal')
    ->setAttribute('enctype', 'multipart/form-data');
?>
<div class="page-header position-relative">
    <div data-target="#step-container" class="row-fluid hide" id="fuelux-wizard" style="display: block;">
        <ul class="wizard-steps">
            <li class="" data-target="#step1" style="min-width: 25%; max-width: 25%;">
                <span class="step">1</span>
                <span class="title">Select Agent/Campaign</span>
            </li>

            <li class="" data-target="#step2" style="min-width: 25%; max-width: 25%;">
                <span class="step">2</span>
                <span class="title">Chose Agent record</span>
            </li>

            <li class="" data-target="#step3" style="min-width: 25%; max-width: 25%;">
                <span class="step">3</span>
                <span class="title">Evaluate topics</span>
            </li>

            <li class="active" data-target="#step4" style="min-width: 25%; max-width: 25%;">
                <span class="step">4</span>
                <span class="title">Send Evaluatin</span>
            </li>
        </ul>
    </div>
</div><!--/.page-header-->

<div class="row-fluid">
    
    <div class="span12">
        <?php echo $this->form()->openTag($form); ?>
            <div class="control-group">
                <label class="control-label">
                    <i class="red icon-bell-alt icon-animated-bell" style="margin-right: 5px;"></i>Notify Agent
                </label>
                <div class="controls">
                    <div class="row-fluid">
                            <div class="span3">
                                    <label>
                                            <input type="checkbox" class="ace-switch" name="switch-field-notify">
                                            <span class="lbl"></span>
                                    </label>
                            </div>
                    </div>
                </div>
            </div>
        
            <div class="control-group">
                <label class="control-label">
                    <i class="blue icon-envelope" style="margin-right: 5px;"></i>
                    Send Email
                </label>
                <div class="controls">
                    <div class="row-fluid">
                            <div class="span3">
                                    <label>
                                            <input type="checkbox" class="ace-switch" name="switch-field-send-email">
                                            <span class="lbl"></span>
                                    </label>
                            </div>
                    </div>
                </div>
            </div>
            
            <div class="wysiwyg-editor" id="editor" style="display:none"></div>

            <div class="hr hr-double dotted"></div>

            <div class="form-actions">
                <button id="back" class="btn btn-prev">
                    <i class="icon-arrow-left"></i>
                    Prev
                </button>
                <button value="" class="btn btn-success btn-small btn-next" type="button" name="send-evaluacion">
                    <i class="icon-ok bigger-110"></i>Finish
                </button>
            </div>
            
            <input type="hidden" name="campania-evaluacion" value="<?php echo $this->evaluacion->getCampania() ?>">
            <input type="hidden" name="agentes-evaluacion" value="<?php echo $this->evaluacion->getAgente() ?>">
            <input type="hidden" name="audio-agent-evaluacion" value="<?php echo $this->evaluacion->getUrlAudio() ?>">
            <input type="hidden" name="fecha-evaluacion" value="<?php echo $this->evaluacion->getFechaEvaluacion() ?>">
            <input type="hidden" name="fecha-llamada" value="<?php echo $this->evaluacion->getFechaLlamada() ?>">
            <input type="hidden" name="evaluador-evaluacion" value="<?php echo $this->evaluacion->getEvaluador() ?>">
            <input type="hidden" name ="id-evaluador-evaluacion" id="id-evaluador-evaluacion" value="<?php echo $this->evaluacion->getEvaluador()?>">
            <input type="hidden" name="textarea" value="">
            <input type="hidden" name="accion-evaluacion" value="guardar">
            <input name="puntajes-evaluacion" type="hidden" value='<?php echo json_encode($this->puntajes) ?>'>
            
        <?php echo $this->form()->closeTag() ?>

    </div>
</div><!--PAGE CONTENT ENDS-->
<div class="modal-loading" style="display: none"></div>
<script>
    $(document).ready(function(){
        $("#back").click(function(e){
            e.preventDefault();
            history.back(1)
        });
        
        setTimeout(function(){
            $(".wysiwyg-toolbar").hide();
        },200);
         
        $("input[name=switch-field-send-email]").change(function(){
           $(".wysiwyg-editor,.wysiwyg-toolbar").toggle();
        });
         
        $("#editor").ace_wysiwyg({toolbar:[
            'font',
            null,
            'fontSize',
            null,
            {name:'bold', className:'btn-info'},
            {name:'italic', className:'btn-info'},
            {name:'strikethrough', className:'btn-info'},
            {name:'underline', className:'btn-info'},
            null,
            null,
            null,
            {name:'justifyleft', className:'btn-primary'},
            {name:'justifycenter', className:'btn-primary'},
            {name:'justifyright', className:'btn-primary'},
            {name:'justifyfull', className:'btn-inverse'},
            null,
            null,
            null,
            null,
            null,
            null,
            'foreColor',
            null,
            null,
            null,
        ]
        }).prev().addClass('wysiwyg-style2');
        
        $('[data-toggle="buttons-radio"]').on('click', function(e){
		var target = $(e.target);
		var which = parseInt($.trim(target.text()));
		var toolbar = $('#editor').prev().get(0);
		if(which == 1 || which == 2 || which == 3) {
			toolbar.className = toolbar.className.replace(/wysiwyg\-style(1|2)/g , '');
			if(which == 1) $(toolbar).addClass('wysiwyg-style1');
			else if(which == 2) $(toolbar).addClass('wysiwyg-style2');
		}
	});
        $("*[name=send-evaluacion]").click(function(e){
            e.preventDefault();
            var textArea = $("#editor").html();
            
            $("input[name=textarea]").val(textArea);
            
            $("#form-add-evaluacion").submit();
        })
        
        $("input[name=switch-field-notify]").attr("checked",true);
    });
</script>
<style>
    .form-actions{
        text-align: right;
    }
    .btn-success{
        padding: 5px 15px 6px;
    }
    .form-horizontal .form-actions{
        padding-left: 0 !important;
    }
    .audiojs{
        width: 100%;
        margin-bottom: 20px;
    }
    .audiojs .scrubber{
        width: 83%;
    }
</style>