<?php if(isset($_SESSION["miSession"]["usuario"])) $usuario = $_SESSION["miSession"]["usuario"]; ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php $form->setAttribute('action', $this->url('usuarios', array('controller' => 'evaluacion', 'action' => 'edit3'))); ?>
<?php
$form->setAttribute('method', 'post')
        ->setAttribute('id', 'form-add-evaluacion')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('enctype', 'multipart/form-data');


?>
<div class="page-header position-relative">
    <h1>
        New Evaluation
    </h1>
</div><!--/.page-header-->

<?php if ($this->save): ?>
    <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
            <i class="icon-remove"></i>
        </button>
        <i class="icon-ok green"></i>
        Evaluation Updated
    </div>
    <script>
        $(document).ready(function() {
            $("input[name=nombre-categoria],input[orden-categoria]").val("");
        })
    </script>
<?php endif; ?>
    
<div class="row-fluid">
    
    <div class="span12">
        
        <?php echo $this->form()->openTag($form); ?>
                                            
                <?php $mensaje = $this->formElementErrors($form->get('campania-evaluacion')); ?>

                <div class="row-fluid control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
                                <label for="form-field-2" class="control-label">Campaigns</label>
                        <div class="controls">
                        <?php echo $this->formSelect($form->get('campania-evaluacion')->setAttribute("readonly","readonly")); ?>
                                <span class="help-inline"><?php echo $mensaje ?></span>
                        </div>
                </div>

                <?php $mensaje = $this->formElementErrors($form->get('agentes-evaluacion')); ?>

                <div class="row-fluid control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
                                <label for="form-field-2" class="control-label">Agent</label>
                        <div class="controls">
                        <?php echo $this->formSelect($form->get('agentes-evaluacion')->setAttribute("readonly","readonly")); ?>
                                <span class="help-inline"><?php echo $mensaje ?></span>
                        </div>
                </div>

                <?php $mensaje = $this->formElementErrors($form->get('audio-agent-evaluacion')); ?>

                <div class="row-fluid control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
                                <label for="form-field-2" class="control-label">Url Audio</label>
                        <div class="controls">
                        <?php echo $this->formInput($form->get('audio-agent-evaluacion')->setAttribute("value",$evaluacion->getUrlAudio())); ?>
                                <span class="help-inline"><?php echo $mensaje ?></span>
                        </div>
                </div>

                <div class="row-fluid control-group ">
                    <label for="form-field-2" class="control-label">Call Date</label>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('fecha-llamada')->setAttribute("value",$evaluacion->getFechaLlamada())->setAttribute("style","width: 220px")->setAttribute("class","span10 date-picker")->setAttribute("id","id-date-picker-1")->setAttribute("data-date-format","dd-mm-yyyy")); ?>
                        <span class="add-on">
                            <i class="icon-calendar"></i>
                        </span>
                    </div>
                </div>
        
                <div class="row-fluid control-group ">
                    <label for="form-field-2" class="control-label">Evaluation Date</label>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('fecha-evaluacion')->setAttribute("value",$evaluacion->getFechaEvaluacion())->setAttribute("readonly","readonly")); ?>
                    </div>
                </div>
       
                <div class="row-fluid control-group ">
                    <label for="form-field-2" class="control-label">Agente Evaluator</label>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('evaluador-evaluacion')->setAttribute("readonly","readonly")->setAttribute("value",$evaluacion->getEvaluador())); ?>
                        <input type="hidden" name ="id-evaluador-evaluacion" id="id-evaluador-evaluacion" value="<?php echo $usuario->getId()?>">
                    </div>
                </div>
                <input type="hidden" name="id-evaluacion" id="id-evaluacion" value="<?php echo $evaluacion->getId() ?>">
                <input type="hidden" name="campania-evaluacion-aprobacion" value="<?php echo $evaluacion->getPuntajeCampaniaAprobacion() ?>">
            <input type="hidden" name="campania-evaluacion-reprobacion" value="<?php echo $evaluacion->getPuntajeCampaniaReprobacion() ?>">
        <hr>
        
        <div class="form-actions">
            <?php echo $this->formButton()->openTag($form->get('send-evaluacion')) . '<i class="icon-ok bigger-110"></i>Next' . $this->formButton()->closeTag(); ?>
        </div>

        <?php echo $this->form()->closeTag() ?>

    </div>
</div><!--PAGE CONTENT ENDS-->
<script>
    $(document).ready(function(){
        $('.date-picker').datepicker().next().on(ace.click_event, function(){
                $(this).prev().focus();
        });
    });
</script>