<div class="row-fluid">
    <div>
        <h2>Mapeo Categorias</h2>
    </div>
	<div>
		<input class="form-control form-filtrar-categorias" placeholder="Filtrar" type="text" value="" />
	</div>
	<hr>
</div>
<script>

</script>
<div class="row-fluid">
    <form action="" method="post">
        <div class="row-fluid">
            <button name="btn-mapeo-categoria" type="submit" class="btn btn-success btn-small btn-next" value="">
            <i class="icon-save"></i>
            Guardar
            </button>
        </div>
    <?php foreach($this->categorias as $categoria):?>
        <div class="row-fluid">
            <input class="form-control form-categorias" type="text" value="<?php echo $categoria->getCategorias();?>" />
            <input style="width: 25%;" class="form-control form-categorias" type="text" value="" required />
			<select>
				<option value="">Template</option>
				<option value="DEFAULT">Default</option>
			</select>
        </div>
    <?php endforeach; ?>
        <div class="row-fluid">
            <button name="btn-mapeo-categoria" type="submit" class="btn btn-success btn-small btn-next" value="">
                <i class="icon-save"></i>
                Guardar
            </button>
        </div>
    </form>
</div>