<div class="row-fluid">
    <div>
        <label>Filtros</label>
        <div class="row-fluid">
            <select name="opt-categorias" required>
                <option value="">Categoria</option>
                <?php foreach($this->categorias as $categoria):?>
                <option value="<?php echo $categoria->getCategorias() ?>"><?php echo $categoria->getCategorias() ?></option>
                <?php endforeach;?>
            </select>
            <select name="opt-estado" required>
                <option value="">Estado</option>

                <?php foreach($this->estados as $estado):?>
                    <?php if(isset($estado["estado"])): ?>
                        <option value="<?php echo $estado["id"] ?>"><?php echo $estado["estado"] ?></option>
                    <?php endif; ?>
                <?php endforeach;?>
            </select>
        </div>
    </div>
    <label><span id="item-publicados">10</span> items publicados de <span id="total-item-publicados">100</span></label>
    <div class="progress">
        <div
            class="progress-bar"
            role="progressbar"
            aria-valuenow="2"
            aria-valuemin="0"
            aria-valuemax="100"
            style="min-width: 2em;
            width: 25%;">
            25%
        </div>
    </div>
    <button name="play-publish-publicacion" type="button" class="btn btn-success btn-small btn-next" value="">
        <i class="icon-play"></i>
        Publicar
    </button>
    <button name="pause-publish-publicacion" type="button" class="btn btn-success btn-small btn-next" value="">
        <i class="icon-stop"></i>
        Detener
    </button>
</div>
<script>
    jQuery(document).ready(function(){
        var filters = {};

        jQuery("select[name=opt-estado],select[name=opt-categorias]").change(function(){
            filters.estado = jQuery("select[name=opt-estado]").val();
            filters.categorias = jQuery("select[name=opt-categorias]").val();
            jQuery.ajax({
                url:"<?php echo $this->url("usuarios", array("controller" => "articulo", "action" => "getTotalArticulosFilter")) ?>",
                type:"post",
                data:{filters:filters},
                success:function(data){
                    var total = data.total;
                    var itemsPublicados = jQuery("#item-publicados").text();
                    var porcentaje = ((itemsPublicados/total) * 100).toFixed(3);

                    jQuery(".progress div").attr("aria-valuemax",porcentaje);
                    jQuery(".progress div").text(total);
                    jQuery(".progress div").css("width",porcentaje+"%")
                    jQuery("#total-item-publicados").text(total);
                }
            })
        });
    })
</script>