<h3 class="header smaller lighter blue">List Users</h3>
<div role="grid" class="dataTables_wrapper" id="sample-table-2_wrapper">
    <form method="POST">
        <div class="row-fluid row-fluid-filters">
            <div class="control-group control-grup-filtros">
                <div class="input-prepend" style="float: left; width: 247px; margin-left: 10px;">
                    <span class="add-on calendario-from-to" style="float: left;">
                        <i class="icon-calendar blue"></i>
                    </span>
                    <input type="text" id="id-date-range-picker-1" name="date-range-picker" class="span10 input-from-to" placeholder="DATE RANGE" style="width: 200px; float: left;">
                </div>
            </div>
            <div class="control-group control-grup-filtros">
                <select multiple="multiple" class="chzn-select" id="form-field-select-agent" name="form-field-select-agent" data-placeholder="Agent">
                        <option value="" />
                    <?php foreach($this->agentes as $agente): ?>
                            <option value="<?php echo $agente->getId() ?>" /><?php echo $agente->getNombre()." ".$agente->getApellido() ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="control-group control-grup-filtros">
                <select multiple="multiple" class="chzn-select" id="form-field-select-campaign" name="form-field-select-campaign" data-placeholder="Campaign">
                        <option value="" />
                    <?php foreach($this->campanias as $campanias): ?>
                        <option value="<?php echo $campanias->getId() ?>" /><?php echo $campanias->getNombre() ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="control-group control-grup-filtros span2">
                <button id="filtrar" class="btn btn-purple">Go!</button>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-2" aria-describedby="sample-table-2_info">
            <thead>
                <tr role="row">
                    <th class="center sorting_disabled" role="columnheader" rowspan="1" colspan="1" style="width: 51px;" aria-label=""></th>
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 111px;" aria-label="Price: activate to sort column ascending">Nombre</th>
                    <th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 121px;" aria-label="Clicks: activate to sort column ascending">Apellido</th>
                    <th class="hidden-phone sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 181px;" aria-label="Update: activate to sort column ascending">Campaigns</th>
                    <th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 150px;" aria-label="Status: activate to sort column ascending">Calls</th>
                    <th class="hidden-480 sorting" role="columnheader" rowspan="1" colspan="1" style="width: 146px;" aria-label="">Average</th>
                </tr>
            </thead>
            <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php $currentPageRange = $this->paginator->getCurrentPageNumber(); ?>
                <?php $pageRange = $this->paginator->getPageRange(); ?>
                <?php $end = $pageRange * $currentPageRange; ?>
                <?php $start = ($end - $pageRange) + 1; ?>
                <?php $count = 1; ?>
                <?php foreach ($this->usuarios as $usuario): ?>
                    <?php
                        $countEvaluaciones = 0;
                        $campanias = array();
                        foreach($usuario->getEvaluaciones() as $evaluacion){
                            $camp = $evaluacion->getCampania();
                            if(!in_array($camp,$campanias))
                            $campanias[] = $camp;
                            $countEvaluaciones++;
                        }
                        $camp = "";
                        foreach($campanias as $c){
                            $camp .= $c ." ";
                        }
                        $camp = trim($camp);
                    ?>
                    <?php if ($count >= $start && $count <= $end): ?>
                        <?php $porcentajeUsuario = ceil($usuario->getPorcentaje()) ?>
                        <tr class="<?php echo ($count % 2 == 0) ? "odd" : "even"; ?>">
                            <td class="center  sorting_1">
                                <?php if($usuario->getAvatar()):?>
                                    <img class="img-avatar" width="38" src="data:image/jpeg;base64,<?php echo base64_encode($usuario->getAvatar()); ?>">
                                <?php else: ?>
                                    <img class="img-avatar" width="38" src="<?php echo $this->basePath('assets/avatars/default-avatar.png') ?>">
                                <?php endif; ?>
                            </td>
                            <td class=" "><?php echo $usuario->getNombre(); ?></td>
                            <td class="hidden-480 "><?php echo $usuario->getApellido(); ?></td>
                            <td class="hidden-480 "><?php echo $camp; ?></td>
                            <td class="hidden-480 ">
                                <?php echo $countEvaluaciones ?>
                            </td>
                            <td class="td-actions ">
                                <?php echo $porcentajeUsuario ?>%
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php $count++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="row-fluid">
            <div class="span6">
                <div class="dataTables_info" id="sample-table-2_info">Showing 1 to 10 of 23 entries</div>
            </div>
            <div class="span6">
                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->paginator,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Album'),
                        // the route to link to when a user clicks a control link
                        array(
                    'ruta' => 'list'
                        )
                );
                ?>
            </div>
        </div>
    </form>
    <div style="text-align: right;">
        <a href="#">Download <i class="icon-download-alt"></i></a>
    </div>
</div>
<script>
    $(document).ready(function() {
        $(".remove").click(function(e) {
            e.preventDefault();
            var href = $(this).attr('href');
            jConfirm('Are you sure you want to remove this user?', 'Delete?', function(ans) {
                if (ans) {
                    window.location = href;
                }
            });
        });
        
        $('#id-date-range-picker-1').daterangepicker({format: 'YYYY-MM-DD'}).prev().on(ace.click_event, function() {
            $(this).next().focus();
        });
        
        $(".chzn-select").chosen();
        
        $("#filtrar").click(function(){
            $("form").submit();
        })
    })
</script>
<style>
.control-grup-filtros{
    float: left;
    width: 280px;
    margin-bottom: 0px;
}
#filtrar{
    line-height: 18px;
    float: right;
}
.row-fluid-filters{
    padding-bottom: 0px;
}
.chzn-container-multi .chzn-choices{
    border: 1px solid #d5d5d5;
    background-image: none !important;
    height: 30px !important;
}
.img-avatar{
    border-radius: 22px;
}
</style>
