<div class="row-fluid">
    <div class="span12">
        <table id="sample-table-1" class="table table-striped table-bordered table-hover">
            <tbody>
                <?php foreach($this->mensajes as $mensaje) : ?>
                <tr>
                    <td class="center">
                        <label>
                            <input type="checkbox" />
                            <span class="lbl"></span>
                        </label>
                    </td>
                    <?php
                    $b = "";
                    $bf = "";
                        if($mensaje->getEstado()=="1"){
                            $b = "<b>";
                            $bf = "</b>";
                        }
                    ?>
                    <td><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"msgs")) ?>"><?php echo $b.$mensaje->getEvaluador().$bf ?></td>
                    <td><?php echo $b.$mensaje->getAsunto().$bf ?></td>
                    <td><?php echo $b ?><?php echo (strlen($mensaje->getMensaje())<50) ? $mensaje->getMensaje():substr($mensaje->getMensaje(), 0,50)."..."; ?><?php echo $bf ?></td>
                    <td><?php echo $b.$mensaje->getFechaCreado().$bf ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="row-fluid">
        <div class="span6">
            <div class="dataTables_info" id="sample-table-2_info">Showing 1 to 10 of 23 entries</div>
        </div>
        <div class="span6">
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                    'sliding',
                    // the partial to use to render the control
                    array('partial/paginator.phtml', 'evaluacion'),
                    // the route to link to when a user clicks a control link
                    array(
                        'ruta' => 'list'
                    )
            );
            ?>
        </div>
    </div>
    </div><!--/span-->
</div><!--/row-->