<div class="row">
    <!-- left, vertical navbar -->
    <!-- content -->
    <div class="col-md-12">        
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">

                        <div class="title-bar-messages">Mensajes Recibidos</div>


                        <table class="table table-striped table-bordered" id="example">
                            <thead>
                                <tr>
                                    <th  style="width:58px;text-align:center;">Leido</th>
                                    <th>Remitente</th>
                                    <th >Asunto</th>
                                    <th style="width:108px;text-align:center;">Fecha</th>

                                    <th style="width:108px;text-align:center;" >Acciones</th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach ($this->mensajes as $mensaje) : ?>
                                <?php
                                $b = "";
                                $bf = "";
                                if ($mensaje->getEstado() == "1") {
                                    $b = "<b>";
                                    $bf = "</b>";
                                }
                                ?>
                                <tr class="odd gradeX">
                                    <td style="text-align: center;"><i class="fa fa-envelope">&nbsp;</i></td>
                                    <td><a href="<?php echo $this->url("usuarios", array("controller" => "mensaje", "action" => "view", "id" => $mensaje->getId())) ?>"><?php echo $b . $mensaje->getEvaluador() . $bf ?></a></td>
                                    <td><a href="<?php echo $this->url("usuarios", array("controller" => "mensaje", "action" => "view", "id" => $mensaje->getId())) ?>"><?php echo $b . $mensaje->getAsunto() . $bf ?></a></td>
                                    <td class="center"  style="text-align: center;"><a href="<?php echo $this->url("usuarios", array("controller" => "mensaje", "action" => "view", "id" => $mensaje->getId())) ?>"><?php echo $b . $mensaje->getFechaCreado() . $bf ?></a></td>
                                    <td class="center"  style="text-align: center;"><i class="fa fa-share">&nbsp;</i>
                                        <a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"delete")) ?>/<?php echo $mensaje->getId(); ?>" class="red remove" value="<?php echo $mensaje->getId(); ?>">
                                            <i class="fa fa-trash">&nbsp;</i>   
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                </div>
                <?php
                    // add at the end of the file after the table
                    echo $this->paginationControl(
                            // the paginator object
                            $this->paginator,
                            // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                            'sliding',
                            // the partial to use to render the control
                            array('partial/paginator.phtml', 'evaluacion'),
                            // the route to link to when a user clicks a control link
                            array(
                        'ruta' => 'list'
                            )
                    );
                    ?>
                    <!--<a class="btn btn-yellow pull-right" >Siguiente</a>
                    <a class="btn btn-cancel pull-right" >Anterior</a>-->
            </div>
        </div>     
    </div>
    </div>