<script src="<?php echo $this->basePath() ?>/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/markdown/markdown.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/markdown/bootstrap-markdown.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/jquery.hotkeys.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/bootstrap-wysiwyg.min.js"></script>


    <!--Respuesta-->
    <div class="panel-heading">
            <div class="text-muted bootstrap-admin-box-title">Redactar Mensaje</div>
        </div>
    <form name="form-send-email" id="form-send-email" method="post" action="<?php echo $this->url("usuarios",array("controller"=>"mensaje", "action"=>"send")) ?>">
        
        <input type="hidden" name="emisor-id" value="">
        <input type="hidden" name="textarea" value="">
        <div class="row-fluid">
            <div id="form_field_select_4_chzn" class="chzn-container chzn-container-multi chzn-with-drop chzn-container-active" title="">
                <label>Para:</label>
                <ul class="chzn-choices">
                    <li class="search-field">
                        <input type="text" name="para" id="para" autocomplete="off" placeholder="Para:">
                    </li>
                </ul>
                <div class="chzn-drop">
                    <ul class="chzn-results">
                        <li value=""></li>
                        <li vlue="1">Carloss</li>
                        <li vlue="2">Carmen</li>
                        <li vlue="3">Camilo</li>
                    </ul>
                </div>
            </div>
        </div>
        <br>
        <div class="label-msg" style="text-align: left;">
            <label>Asunto:</label><input name="asunto" id="asunto" placeholder="Asunto:" type="text" value="">
        </div>
        <div name="edit2" class="wysiwyg-editor" id="editor2"></div>
        <hr>
        <div class="form-actions">
            
            
            <button style="float: right;" name="send-evaluacion" type="button" class="btn btn-success btn-small btn-next" value="">
                <i class="icon-envelope-alt"></i>
                Enviar
            </button>        
        </div>
    </form>
<script>
    $(document).ready(function(){
       
       $("#editor2").ace_wysiwyg({toolbar:[
                'font',
                null,
                'fontSize',
                null,
                {name:'bold', className:'btn-info'},
                {name:'italic', className:'btn-info'},
                {name:'strikethrough', className:'btn-info'},
                {name:'underline', className:'btn-info'},
                null,
                null,
                null,
                {name:'justifyleft', className:'btn-primary'},
                {name:'justifycenter', className:'btn-primary'},
                {name:'justifyright', className:'btn-primary'},
                {name:'justifyfull', className:'btn-inverse'},
                null,
                null,
                null,
                null,
                null,
                null,
                'foreColor',
                null,
                null,
                null,
            ]
	}).prev().addClass('wysiwyg-style2');
        
        $("*[name=send-evaluacion]").click(function(){
            var textArea = $("#editor2").html();
            $("input[name=textarea]").val(textArea);
            
            $("#form-send-email").submit();
        })
        
        $(document).on("keyup","#para",function(){
            var text = $(this).val();

            if(text.indexOf(",")!=-1){
                text = text.split(",");
                text = text[text.length-1];
            }

            if(text.length>2){
                a = 0;
                $.ajax({
                    url:"<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"username")); ?>",
                    data:{text:text},
                    success:function(data){
                        var html = "";
                        $(".chzn-results").html(html);
                        
                        var res = JSON.parse(data);
                        for(var i in res){
                            html += "<li mail='"+res[i].email+"'>"+res[i].nombre+" - ["+res[i].email+"]</li>";
                        }
                        var ul = $(".chzn-drop").find("ul:first").html(html);
                        $(".chzn-results").find("li").show();
                    }
                })
            }
        })
        
        $(document).on("click",".chzn-container .chzn-results li",function(){
            var email = $(this).attr("mail");
            var texto = $("#para").val();
            var pos = texto.indexOf(",");
            if(pos == -1){
                $("#para").val(email+",");
            }else{
                var anterior = $("#para").val();
                anterior = anterior.substring(0,pos);
                $("#para").val(anterior+","+email+",");
            }
            $(".chzn-results").html("");
            $(".chzn-results").find("li").hide();
        });
        
        $('html').click(function() {
            $(".chzn-results").find("li").hide();
        })
        $(".chzn-select").chosen(); 
    });
</script>
<style>
#back {
    float: right;
    margin-right: 5px;
}
.chzn-choices{
    background-image:none !important;
    color: #858585 !important;
    border-color: #D5D5D5 !important;
    position: inherit !important;
}
.chzn-container .chzn-results li:hover{
    background: none repeat scroll 0 0 #316AC5;
    color: #FFFFFF;
    cursor:pointer;
}
</style>

