<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle(); ?>

        <meta name="description" content="overview &amp; stats" />

        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <script>
            var basepath_javascript = "<?php echo $this->basePath(); ?>";
        </script>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/assets/css/responsive.css')
                ->prependStylesheet($this->basePath() . '/assets/css/tutesis.css')
                ->prependStylesheet($this->basePath() . '/assets/css/styles_new.css')
                
                /*Inicio maqutado 2*/
                
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-new.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/assets/css/animate.css')
                ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                /* Fin maquetado 2*/
                
                /**/
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css')
                //->prependStylesheet($this->basePath() . '/assets/css/bootstrap-theme.css')
                //<!-- Bootstrap Admin Theme -->
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-admin-theme.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-admin-theme-change-size.css')
                //<!-- Custom  -->
                
                //<!-- Vendors -->
                //->prependStylesheet($this->basePath() . '/assets/vendors/easypiechart/jquery.easy-pie-chart.css')
                //->prependStylesheet($this->basePath() . '/assets/vendors/easypiechart/jquery.easy-pie-chart_custom.css')
                ->prependStylesheet($this->basePath() . '/assets/css/styles_new.css')
                /**/
                ->prependStylesheet($this->basePath() . '/assets/css/jquery-mentions/jquery.mentionsInput.css')
                //->prependStylesheet($this->basePath() . '/assets/css/jquery-mentions/style.css')
                ->prependStylesheet($this->basePath() . '/assets/css/main.css')
                ->prependStylesheet($this->basePath() . '/assets/css/jquery-ui-1.10.3.custom.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/jquery.alerts.css')
                ->prependStylesheet($this->basePath() . '/assets/css/chosen.css')
                ->prependStylesheet($this->basePath() . '/assets/css/ace-skins.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/ace-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/ace.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/daterangepicker.css')
                ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.min.css')
                //->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
        ?>

        <!--[if IE 7]>
          <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
        <![endif]-->

        <!--page specific plugin styles-->

        <!--fonts-->

        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

        <!--[if lte IE 8]>
          <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
        <![endif]-->

        <!--inline styles related to this page-->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                
                ->prependFile($this->basePath() . '/assets/js/twitter-bootstrap-hover-dropdown.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap-admin-theme-change-size.js')
                //->prependFile($this->basePath() . '/assets/vendors/easypiechart/jquery.easy-pie-chart.js')
                
                // PAGES
                ->prependFile($this->basePath() . '/assets/js/jquery-mentions/jquery.mentionsInput.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-mentions/jquery.elastic.source.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-mentions/underscore-min.js')
                ->prependFile($this->basePath() . '/assets/js/pages/evaluation.js')
                
                ->prependFile($this->basePath() . '/assets/js/select2.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/additional-methods.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootbox.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.maskedinput.min.js')
                ->prependFile($this->basePath() . '/assets/js/fuelux/fuelux.wizard.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.validate.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/jquery-migrate-1.2.1.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.alerts.js')
                
                ->prependFile($this->basePath() . '/assets/js/x-editable/ace-editable.min.js')
                //->prependFile($this->basePath() . '/assets/js/x-editable/xeditable.min.js')
                ->prependFile($this->basePath() . '/assets/js/x-editable/bootstrap-editable.min.js')
                ->prependFile($this->basePath() . '/assets/js/jonathan_main.js')
                ->prependFile($this->basePath() . '/assets/js/xeditable.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.resize.min.js')
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.categories.js')
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.pie.min.js')
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.min.js')
                ->prependFile($this->basePath() . '/assets/js/ace.min.js')
                ->prependFile($this->basePath() . '/assets/js/ace-elements.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/jquery.sparkline.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.easy-pie-chart.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.slimscroll.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.ui.touch-punch.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-ui-1.10.3.custom.min.js')
                //->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/additional-methods.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/js/excanvas.min.js', 'text/javascript', array('conditional' => 'lte IE 8',))
                
                ->prependFile($this->basePath() . '/assets/js/main.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.isotope.min.js')
                ->prependFile($this->basePath() . '/assets/js/drive-me-plugin.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.flexslider-min.js')
                ->prependFile($this->basePath() . '/assets/js/mapmaker.js')
                ->prependFile($this->basePath() . '/assets/js/wow.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.magnific-popup.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/ace.min.js')
                ->prependFile($this->basePath() . '/assets/js/ace-elements.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap-tag.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.maskedinput.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.inputlimiter.1.3.1.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.autosize-min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.knob.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap-colorpicker.min.js')
                ->prependFile($this->basePath() . '/assets/js/date-time/daterangepicker.min.js')
                ->prependFile($this->basePath() . '/assets/js/date-time/moment.min.js')
                ->prependFile($this->basePath() . '/assets/js/date-time/bootstrap-timepicker.min.js')
                ->prependFile($this->basePath() . '/assets/js/date-time/bootstrap-datepicker.min.js')
                ->prependFile($this->basePath() . '/assets/js/fuelux/fuelux.spinner.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/jquery.base64.js')
                
                ->prependFile($this->basePath() . '/assets/js/jquery.ui.touch-punch.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-ui-1.10.3.custom.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                
                ->prependFile($this->basePath() . '/assets/js/chosen.jquery.min.js')
                ->prependFile($this->basePath() . '/assets/js/typehead.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.min.2.0.3.js');
        ?>

        <script type="text/javascript">
            window.jQuery || document.write("&lt;script src='assets/js/jquery-2.0.3.min.js'&gt;" + "&lt;" + "/script&gt;");
        </script>
        <script type="text/javascript">
            if ("ontouchend" in document)
                document.write("&lt;script src='assets/js/jquery.mobile.custom.min.js'&gt;" + "&lt;" + "/script&gt;");
        </script>
        
    </head>
    <body>
        <!--======= PRELOADER =========-->
        <div class="work-in-progress">
            <div id="preloader">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <!--======= WRAPPER =========-->
        <div id="wrap"> 
            <?php foreach($this->mensajes as $mensaje):?>
                <div><?php echo $mensaje ?></div>
            <?php endforeach; ?>
            <!--======= TOP BAR =========-->
            <div class="top-bar">
                <div class="container">
                    <ul class="left-bar-side">
                        <li> <a href="#."><i class="fa fa-facebook"></i></a> - </li>
                        <li> <a href="#."><i class="fa fa-twitter"></i></a> - </li>
                        <li> <a href="#."><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                    <ul class="right-bar-side">
                        <li> <a href="#."><i class="fa fa-comment"></i> Chat de Atención </a></li>
                        <li> <a href="#."><i class="fa fa-phone"></i> +52 1 (735)1349472 </a></li>
                        <li> <a href="#."><i class="fa fa-envelope"></i> soporte@tutesisenlinea.com </a></li>
                        <li> <a href="#." data-toggle="modal" data-target="#myModal"> <i class="fa fa-user"></i> Ingresa </a></li>
                    </ul>
                </div>
            </div>

            <!--======= HEADER =========-->
            <header class="sticky">
                <div class="container">
                    <nav class="navbar navbar-default">
                        <div class="row">
                            <div class="navbar-header col-md-3 col-sm-3">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-res"> <span class="sr-only">Toggle navigation</span> <span class="fa fa-navicon"></span> </button>
                                <!--======= LOGO =========-->
                                <div class="logo"> <a href="index.html"> <img <img src="<?php echo $this->basePath('assets/images/logo.png')?>" alt="tu tesis en línea logo" > </a> </div>
                            </div>

                            <!--======= MENU =========-->
                            <div class="col-md-9 col-sm-9">
                                <div class="collapse navbar-collapse" id="nav-res">
                                    <ul class="nav navbar-nav">                         
                                        <li><a href="#">Nosotros</a></li>
                                        <li><a href="#">Ayuda</a></li>
                                        <li><a href="#">Contacto</a></li>
                                        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i> </a>
                                            <ul class="dropdown-menu mega srch navbar-right animated-half fadeInUp">
                                                <li>
                                                    <div class="form-group">
                                                        <input type="search" class="form-control" id="search" placeholder="Seacrh Here">
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
            </header>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    
                                 <div class="tel-home-form">
                                    <div href"dashboard.html" class="tel-home-form-title">Iniciar Sesion</div>
                                    <form id="form-login" method="post" action="<?php echo $this->basePath("usuarios/login/autenticar") ?>" style="padding-top: 25px;">
                                
                                
                              <div class="form-group">
                                <div class="col-sm-12 tel-form-space">
                                  <input type="email" class="form-control" name="nombre" placeholder="Correo Electrónico *">
                                </div>
                              </div>
                              <div class="form-group">
                                <div class="col-sm-12 tel-form-space">
                                    <input type="password" class="form-control" name="clave" placeholder="Contraseña *">
                                </div>
                              </div>
                              <div class="form-group">
                                <div class="col-sm-12 tel-form-space">
                                     <label class="uniform">
                                                        <div id="uniform-optionsCheckbox" class="checker"><span><input class="uniform_on" id="optionsCheckbox" value="option1" type="checkbox">&nbsp;  Recordarme</span></div>
                                                       
                                                    </label>
                                                             
                                </div>
                              </div>
                              <div class="form-group">
                                <div class="col-sm-12">
                                    
                                    <a id="iniciar-session" class="btn btn-black" style="width:100%;margin-top: 10px;">Iniciar Session</a>
                                    
                                </div>
                              </div>   
                              <div class="form-group" style="">
                                <div class="col-sm-12" style="margin-top: 10px;color:#fff;">
                                    
                                    
                                    
                                   ¿ Aún no tienes cuenta ? - <a class="" href="index.html" style="margin-top: 10px;color:#fff;">Registrate</a>
                                </div>
                              </div>                                    
                              <div class="form-group">
                                <div class="col-sm-12 tel-form-space" style="margin-top: 50px; text-align: center;">
                                    <a class="tel-login" href="">¿Olvido su Contaseña?</a>
                                </div>
                              </div>   
                            
                            </form>
                            
                            
                        </div>
    
    
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>














            <!--======= BANNER =========-->
            <div id="banner">
                <div class="flexslider">
                    <ul class="slides">

                        <!--======= SLIDE 1 =========-->
                        <li> <img <img src="<?php echo $this->basePath('assets/images/slide-1.jpg')?>" alt="">
                            <div class="container">
                                <div class="text-slider">
                                    <div class="col-sm-7">
                                        <h3>Registrate y comienza tu tesis.<i class="fa fa-long-arrow-right"></i></h3>
                                        <p>Con "Tu tesis en línea" puedes finalizar tus estudios desde casa.</p>
                                        <a class="btn" href="08_booking_page.html">Consulta Precio</a> 
                                        <a class="btn get-form" href="#." data-toggle="modal" data-target="#myModal">Ingresa</a> 
                                    </div>
                                    <div class="col-sm-5 col-md-4 pull-right hidden-xs">
                                        <div class="find-drive">
                                            <h5>Registrarse<i class="fa fa-pencil"></i></h5>
                                            <div class="drive-form">
                                                <div class="intres-lesson"> 

                                                    <!--======= FORM =========-->
                                                    <form id="reg_form" method="post" action="<?php echo $this->basePath("usuarios/login/registrarse") ?>">
                                                        <ul class="row">

                                                            <!--======= INPUT NAME =========-->
                                                            <li class="col-sm-6">
                                                                <div class="form-group">
                                                                    <input type="text" class="form-control" id="name" name="first-name-user" placeholder="Su nombre">
                                                                    <span class="fa fa-user"></span> </div>
                                                            </li>

                                                            <!--======= INPUT SURNAME =========-->
                                                            <li class="col-sm-6">
                                                                <div class="form-group">
                                                                    <input type="text" class="form-control" id="name" name="last-name-user" placeholder="Su apellido">
                                                                    <span class="fa fa-user"></span> </div>
                                                            </li>


                                                            <!--======= INPUT SELECT =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <select id="select1" name="level-user" required>
                                                                        <option value="">SELECCIONAR</option>
                                                                        <option value="4">Alumno</option>
                                                                        <option value="3">Asesor</option>
                                                                    </select>
                                                                    <span class="fa fa-file-text-o"></span> </div>
                                                            </li>

                                                            <!--======= INPUT EMAIL =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="email" class="form-control" id="email" name="email-user" placeholder="Su Email">
                                                                    <span class="fa fa-envelope"></span> </div>
                                                            </li>

                                                            <!--======= INPUT EMAIL 2 =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="email" class="form-control" id="email" name="reemail-user" placeholder="Repita su Email">
                                                                    <span class="fa fa-envelope"></span> </div>
                                                            </li>

                                                            <!--======= INPUT PASSWORD =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="password" class="form-control" name="pass-user" id="Contraseña" placeholder="Su Contraseña">
                                                                    <span class="fa fa-key"></span> </div>
                                                            </li>

                                                            <!--======= INPUT PASSWORD 2 =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="password" class="form-control" name="pass_conf" id="Contraseña" placeholder="Repita su Contraseña">
                                                                    <span class="fa fa-key"></span> </div>
                                                            </li>
                                                        <!--======= BUTTON =========-->
                                                        <div class="text-center">
                                                            <button type="submit" value="submit" class="btn" id="btn_submit">Registrarse</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

                        
                    </ul>
                </div>
            </div>

            <!--======= CONTENT START =========-->
            <div class="content"> 

                <!--======= TESTIMONIALS =========-->
                <section id="testimonials">
                    <div class="container">
                        <div class="testi-slide"> 

                            <!--======= SLIDE 1 =========-->
                            <div class="testi">
                                <div class="avatr"> <img <img src="<?php echo $this->basePath('assets/images/avatar-1.jpg')?>" alt="" > </div>
                                <div class="feed-text">
                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.</p>
                                    <h5>Abraham Doe <span> - Sociologo </span></h5>
                                </div>
                            </div>

                            <!--======= SLIDE 2 =========-->
                            <div class="testi">
                                <div class="avatr"> <img <img src="<?php echo $this->basePath('assets/images/avatar-2.jpg')?>" alt="" > </div>
                                <div class="feed-text">
                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, nec sagittis sem nibh id elit. lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.</p>
                                    <h5>Abraham Doe <span> - Sociologo </span></h5>
                                </div>
                            </div>

                            <!--======= SLIDE 3 =========-->
                            <div class="testi">
                                <div class="avatr"> <img <img src="<?php echo $this->basePath('assets/images/avatar-3.jpg')?>" alt="" > </div>
                                <div class="feed-text">
                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. nec sagittis sem nibh id elit.</p>
                                    <h5>Abraham Doe <span> - Sociologo </span></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <!--======= RESPONSIVE FORM =========-->
                <div class="visible-xs" id="find-course">
                    <div class="container">
                        <div class="col-xs-12">
                            <div class="find-drive">
                                <h5>Registrate <i class="fa fa-pencil"></i></h5>
                                <div class="drive-form">
                                    <div class="intres-lesson"> 

                                        <!--======= FORM =========-->
                                                    <form action="<?php echo $this->basePath("usuarios/login/registrarse") ?>" role="form" id="find_course" method="post">
                                                        <ul class="row">

                                                            <!--======= INPUT NAME =========-->
                                                            <li class="col-sm-6">
                                                                <div class="form-group">
                                                                    <input type="text" class="form-control" id="name" name="Nombre" placeholder="Su nombre">
                                                                    <span class="fa fa-user"></span> </div>
                                                            </li>

                                                            <!--======= INPUT SURNAME =========-->
                                                            <li class="col-sm-6">
                                                                <div class="form-group">
                                                                    <input type="text" class="form-control" id="name" name="Apellido" placeholder="Su apellido">
                                                                    <span class="fa fa-user"></span> </div>
                                                            </li>


                                                            <!--======= INPUT SELECT =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <select id="select1">
                                                                        <option>Seleccionar</option>
                                                                        <option>Alumno</option>
                                                                        <option>Asesor</option>
                                                                    </select>
                                                                    <span class="fa fa-file-text-o"></span> </div>
                                                            </li>

                                                            <!--======= INPUT EMAIL =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="email" class="form-control" id="email" placeholder="Su Email">
                                                                    <span class="fa fa-envelope"></span> </div>
                                                            </li>

                                                            <!--======= INPUT EMAIL 2 =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="email" class="form-control" id="email" placeholder="Repita su Email">
                                                                    <span class="fa fa-envelope"></span> </div>
                                                            </li>

                                                            <!--======= INPUT PASSWORD =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="password" class="form-control" id="Contraseña" placeholder="Su Contraseña">
                                                                    <span class="fa fa-key"></span> </div>
                                                            </li>

                                                            <!--======= INPUT PASSWORD 2 =========-->
                                                            <li class="col-sm-12">
                                                                <div class="form-group">
                                                                    <input type="password" class="form-control" id="Contraseña" placeholder="Repita su Contraseña">
                                                                    <span class="fa fa-key"></span> </div>
                                                            </li>


                                                        <!--======= BUTTON =========-->
                                                        <div class="text-center">
                                                            <button type="submit" value="submit" class="btn" id="btn_submit">Registrarse</button>
                                                        </div>
                                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <!--======= VIDEO =========-->
                <section id="video" data-stellar-background-ratio="0.2">
                    <div class="container text-center">
                        <h1>¿Que es "Tu tesis en línea"?</h1>
                        <h3>Reproduce el video y te explicaremos brevemete de que se trata</h3>
                        <a href="#small-vedio" class="link popup-vedio video-btn"><i class="fa fa-play-circle-o"></i></a> </div>
                </section>

                <!--======= POPUP VIDEO =========-->
                <div id="small-vedio" class="zoom-anim-dialog mfp-hide">
                    <div class="pop_up">
                        <iframe src="https://player.vimeo.com/video/1330769"></iframe>
                    </div>
                </div>


                <!--======= FEATURE =========-->
                <section id="feature">
                    <div class="container"> 

                        <!--======= TITTLE =========-->
                        <div class="tittle">
                            <h3>Nuestras características</h3>
                            <p>Las mejores opciones para usted</p>
                            <hr>
                        </div>
                        <div class="row">
                            <div class="col-md-6"> 
                                <!--======= FEATURE =========-->
                                <ul class="row">

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-calendar"></i> </div>
                                            <h5>En cualquier momento y en cualquier lugar</h5>
                                            <hr>
                                            <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>
                                            <a href="#.">Leer mas</a> </div>
                                    </li>

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-calendar"></i> </div>
                                            <h5>En cualquier momento y en cualquier lugar</h5>
                                            <hr>
                                            <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>
                                            <a href="#.">Leer mas</a> </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6"> 
                                <!--======= FEATURE =========-->
                                <ul class="row">

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-calendar"></i> </div>
                                            <h5>En cualquier momento y en cualquier lugar</h5>
                                            <hr>
                                            <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>
                                            <a href="#.">Leer mas</a> </div>
                                    </li>

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-calendar"></i> </div>
                                            <h5>En cualquier momento y en cualquier lugar</h5>
                                            <hr>
                                            <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>
                                            <a href="#.">Leer mas</a> </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>

            
                <!--======= FOOTER =========-->
                <footer>
                    <div class="container">
                        <div class="row"> 

                            <!--======= FOOTER ROWS =========-->
                            <div class="col-md-6">
                                <ul class="row">

                                    <!--======= ABOUT US =========-->
                                    <li class="col-sm-6">
                                        <h5>Nosotros</h5>
                                        <hr>
                                        <p>Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. </p>
                                        <form method="post" class="subscribe-form" id="subscribe_form">
                                            <input type="email" name="newsletter" id="scf_email" placeholder="tu.email@adress.com" required>
                                            <button type="submit" id="scf_submit"><i class="fa fa-check"></i> </button>
                                        </form>
                                    </li>

                                    <!--======= USEFUL LINKS =========-->
                                    <li class="col-sm-6">
                                        <h5>Links<span> mas usados</span></h5>
                                        <hr>
                                        <ul class="link">
                                            <li><a href="#."> Home <i class="fa fa-angle-right"></i></a></li>
                                            <li><a href="#."> Nosotros <i class="fa fa-angle-right"></i></a></li>
                                            <li><a href="#."> Ayuda <i class="fa fa-angle-right"></i></a></li>
                                            <li><a href="#."> Contacto <i class="fa fa-angle-right"></i></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>

                            <!--======= FOOTER ROWS =========-->
                            <div class="col-md-6">
                                <ul class="row">

                                    <!--======= USEFUL LINKS =========-->
                                    <li class="col-sm-6">
                                        <h5>Galeria <span>de Fotos</span></h5>
                                        <hr>
                                        <ul class="flicker">
                                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-1.jpg')?>" alt=""></a></li>
                                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-2.jpg')?>" alt=""></a></li>
                                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-3.jpg')?>" alt=""></a></li>
                                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-4.jpg')?>" alt=""></a></li>
                                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-5.jpg')?>" alt=""></a></li>
                                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-1.jpg')?>" alt=""></a></li>
                                        </ul>
                                    </li>

                                
                                </ul>
                            </div>
                        </div>
                        <div class="scroll-top">
                            <span class="fa fa-angle-up"></span>
                        </div> 
                    </div>

                    <!--======= RIGHTS =========-->
                    <div class="rights">
                        <div class="container">
                            <ul class="row">
                                <li class="col-md-8">
                                    <p>Todos los derechos reservados © Tu tesis en línea | Designed By Hueco-Creativo</p>
                                </li>
                                <!--======= SOCIAL ICON =========-->
                                <li class="col-md-4">
                                    <ul class="social_icons">
                                        <li class="facebook"><a href="#."><i class="fa fa-facebook"></i></a></li>
                                        <li class="googleplus"><a href="#."><i class="fa fa-google-plus"></i></a></li>
                                        <li class="twitter"><a href="#."><i class="fa fa-twitter"></i></a></li>
                                        <li class="vimeo"><a href="#."><i class="fa fa-vimeo-square"></i></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <!--<script src="js/jquery-1.11.0.min.js"></script> 
        <script src="js/wow.min.js"></script> 
        <script src="js/bootstrap.js"></script> 
        <script src="js/drive-me-plugin.js"></script> 
         <script src="js/jquery.cookie.js"></script> 
        <script src="js/jquery.isotope.min.js"></script> 
        <script src="js/jquery.flexslider-min.js"></script> 
        <script src="js/mapmarker.js"></script> 
        <script src="js/color-switcher.js"></script> 
        <script src="js/jquery.magnific-popup.min.js"></script> 
        <script src="js/main.js"></script>-->
    <script>
        $(document).ready(function(){
            $("#iniciar-session").click(function(){
                $("#form-login").submit();
            })
        });
    </script>
    </body>
</html>