<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle(); ?>

        <meta name="description" content="overview &amp; stats" />

        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/assets/css/ace-skins.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/ace-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/ace.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
        ?>

        <!--[if IE 7]>
          <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
        <![endif]-->

        <!--page specific plugin styles-->

        <!--fonts-->

        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

        <!--[if lte IE 8]>
          <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
        <![endif]-->

        <!--inline styles related to this page-->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <!-- Scripts -->

        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/js/ace.min.js')
                ->prependFile($this->basePath() . '/assets/js/ace-elements.min.js')
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.resize.min.js')
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.pie.min.js')
                ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.sparkline.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.easy-pie-chart.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.slimscroll.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.ui.touch-punch.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-ui-1.10.3.custom.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/excanvas.min.js', 'text/javascript', array('conditional' => 'lte IE 8',))
                ->prependFile($this->basePath() . '/assets/js/jquery.min.2.0.3.js')
        ;
        ?>

    </head>
    <body class="login-layout">
        <div class="main-container container-fluid">
            <div class="main-content">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="login-container">
                            <div class="row-fluid">
                                <div class="center">
                                    <h1>
                                        <i class="icon-ok green"></i>
                                        <span class="red">GeoMl</span>
                                    </h1>
                                    <h4 class="blue">&copy; Geocom. TODOS LOS DERECHOS RESERVADOS.</h4>
                                </div>
                            </div>

                            <div class="space-6"></div>

                            <div class="row-fluid">
                                <div class="position-relative">
                                    <div id="login-box" class="login-box visible widget-box no-border">
                                        <div class="widget-body">
                                            <div class="widget-main">
                                                <h4 class="header blue lighter bigger">
                                                    Please Enter Your Information
                                                </h4>

                                                <div class="space-6"></div>

                                                <?php echo $this->content; ?>

                                                
                                            </div><!--/widget-main-->

                                            <div class="toolbar clearfix">
                                                <div>
                                                    <!--<a href="" onclick="show_box('forgot-box'); return false;" class="forgot-password-link">-->
<!--                                                        <i class="icon-arrow-left"></i>-->
                                                        <a class="forgot-password-link" href="<?php echo $this->basePath("usuarios/login/recuperarpass"); ?>">
                                                            <i class="icon-arrow-left"></i>
                                                            ¿Olvidó su contraseña?
                                                        </a>
                                                    <!--</a>-->
                                                </div>
                                            </div>
                                        </div><!--/widget-body-->
                                    </div><!--/login-box-->

                                    <div id="forgot-box" class="forgot-box widget-box no-border">
                                        <div class="widget-body">
                                            <div class="widget-main">
                                                <h4 class="header red lighter bigger">
                                                    <i class="icon-key"></i>
                                                    Retrieve Password
                                                </h4>

                                                <div class="space-6"></div>
                                                <p>
                                                    Enter your email and to receive instructions
                                                </p>

                                                <form />
                                                <fieldset>
                                                    <label>
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="email" class="span12" placeholder="Email" />
                                                            <i class="icon-envelope"></i>
                                                        </span>
                                                    </label>

                                                    <div class="clearfix">
                                                        <button onclick="return false;" class="width-35 pull-right btn btn-small btn-danger">
                                                            <i class="icon-lightbulb"></i>
                                                            Send Me!
                                                        </button>
                                                    </div>
                                                </fieldset>
                                                </form>
                                            </div><!--/widget-main-->

                                            <div class="toolbar center">
                                                <a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
                                                    Back to login
                                                    <i class="icon-arrow-right"></i>
                                                </a>
                                            </div>
                                        </div><!--/widget-body-->
                                    </div><!--/forgot-box-->

                                    <div id="signup-box" class="signup-box widget-box no-border">
                                        <div class="widget-body">
                                            <div class="widget-main">
                                                <h4 class="header green lighter bigger">
                                                    <i class="icon-group blue"></i>
                                                    New User Registration
                                                </h4>

                                                <div class="space-6"></div>
                                                <p> Enter your details to begin: </p>

                                            </div>

                                            <div class="toolbar center">
                                                <a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
                                                    <i class="icon-arrow-left"></i>
                                                    Back to login
                                                </a>
                                            </div>
                                        </div><!--/widget-body-->
                                    </div><!--/signup-box-->
                                </div><!--/position-relative-->
                            </div>
                        </div>
                    </div><!--/.span-->
                </div><!--/.row-fluid-->

            </div>
        </div> <!-- /container -->
    </body>
</html>