<div class="modal-video">
    <div class="table-header">
            <button data-dismiss="modal" class="close" type="button">×</button>
            Tutorial
    </div>
    <div class="inputs-text-control">
        <div class="contenedor-video">
            
        </div>
    </div>
</div>
<style>
.modal-body {
    max-height: 400px;
    overflow: hidden;
    padding: 3px;
    position: relative;
}
</style>