<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            Asistente para la confeccion de la Tesis

        </h1>
    </div><!--/.page-header-->

    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->


            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-header widget-header-blue widget-header-flat">
                            <h4 class="lighter">New Item Wizard</h4>

                        </div>

                        <div class="widget-body">
                            <div class="widget-main">
                                <div class="row-fluid">
                                    <div id="fuelux-wizard" class="row-fluid hide" data-target="#step-container">
                                        <ul class="wizard-steps">
                                            <?php $count = 1; ?>
                                            <?php foreach ($this->paginas as $pagina): ?>
                                                <li data-target="#step<?php echo $count ?>" class="<?php echo ($count === 1 ) ? "active" : "" ?>">
                                                    <span class="step"><?php echo $count; ?></span>
                                                    <span class="title"><?php echo $pagina->getTitulo() ?></span>
                                                </li>
                                                <?php $count++; ?>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>

                                    <hr />
                                    <div class="step-content row-fluid position-relative" id="step-container">
                                        <?php $count = 1; ?>
                                        <?php foreach ($this->paginas as $pagina): ?>
                                            <div class="step-pane <?php echo ($count === 1 ) ? "active" : "" ?>" id="step<?php echo $count ?>">
                                                <h4 class="header green"><?php echo $pagina->getTitulo() ?></h4>
                                                <form class="form-horizontal" id="sample-form" >
                                                    <?php foreach ($pagina->getInputs() as $input): ?>
                                                        <div class="control-group inputs-respuestas">
                                                            <label nom="<?php echo $input->getNombre() ?>" id="label-<?php echo $input->getNombre() ?>" class="control-label" for=""><?php echo $input->getLabel() ?></label>
                                                            <div class="controls">
                                                                <span class="span6 input-icon input-icon-right">
                                                                    <?php if($input->getTipo()=="texto"):?>
                                                                        <?php if($input->getControl()->getRespuestasRequeridas() > 0 ):?>
                                                                    <input value="<?php echo $input->getRespuesta() ?>" id_input="<?php echo $input->getId() ?>" tipo="<?php echo $input->getTipo() ?>" id_pagina="<?php echo $input->getIdPagina() ?>"  name="<?php echo $input->getNombre() ?>" class="span12 <?php echo ($input->getIsMagic())?"isMagic":"" ?>" type="text" id="" <?php echo ($input->getRequired()) ? "required='required'" : "" ?>/>
                                                                        <?php endif; ?>
                                                                    <input type="hidden" name="hidden-<?php echo $input->getNombre() ?>" class="span12 hidden-response" type="text" id="" value="<?php echo $input->getRespuesta() ?>"/>
                                                                    <?php elseif($input->getTipo()=="dropdown"):?>
                                                                    <?php
                                                                    $sc = "";
                                                                    $stipo = $input->getControl()->getTipo();
                                                                    if($input->getIsMagic()){
                                                                        $sc = "isMagic";
                                                                    }
                                                                    $valuesSelected = array();
                                                                    ?>
                                                                    <select class="<?php echo $sc ?><?php echo ($stipo == "multi")? "chzn-select":"" ?>" <?php echo ($stipo == "multi")?"multiple='multiple'":"" ?> id_input="<?php echo $input->getId() ?>" tipo="<?php echo $input->getTipo() ?>" id_pagina="<?php echo $input->getIdPagina() ?>"  name="<?php echo $input->getNombre() ?>" <?php echo ($input->getRequired()) ? "required" : ""?>>
                                                                        <option value="">SELECCIONAR</option>
                                                                        <?php $control = $input->getControl();?>
                                                                        <?php foreach($control->getValues() as $value):?>
                                                                        <option 
                                                                            <?php 
                                                                            if($value->getSelected()){
                                                                                echo "selected='selected'";
                                                                                $valuesSelected[] = $value->getId();
                                                                            } 
                                                                            ?> 
                                                                            value="<?php echo $value->getId() ?>"><?php echo $value->getValue() ?></option>
                                                                        <?php endforeach;?>
                                                                    </select>
                                                                    <input type="hidden" name="hidden-<?php echo $input->getNombre() ?>" class="span12 hidden-response" type="text" id="" value="<?php echo implode(",", $valuesSelected) ?>"/>
                                                                    <?php endif;?>
                                                                    <?php if($input->getAyuda()):?>    
                                                                    <i class="tooltip-success icon-question-sign" data-rel="tooltip" data-placement="right" title="<?php echo $input->getAyuda(); ?>"></i>
                                                                    <?php endif;?>
                                                                    
                                                                </span>
                                                                <!--<span class="help-inline">Something may have gone wrong</span>-->
                                                            </div>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </form>
                                            </div>
                                            <?php $count++; ?>
                                        <?php endforeach; ?>
                                    </div>

                                    <hr />
                                    <div class="row-fluid wizard-actions">
                                        <button class="btn btn-prev">
                                            <i class="icon-arrow-left"></i>
                                            Prev
                                        </button>

                                        <button class="btn btn-success btn-next btn-next-wizard" data-last="Finish ">
                                            Next
                                            <i class="icon-arrow-right icon-on-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </div><!--/widget-main-->
                        </div><!--/widget-body-->
                    </div>
                </div>
            </div>

            <div id="modal-wizard" class="modal hide">
                <div class="modal-header" data-target="#modal-step-contents">
                    <ul class="wizard-steps clearfix">
                        <li data-target="#modal-step1" class="active">
                            <span class="step">1</span>
                            <span class="title">Validation states</span>
                        </li>

                        <li data-target="#modal-step2">
                            <span class="step">2</span>
                            <span class="title">Alerts</span>
                        </li>

                        <li data-target="#modal-step3">
                            <span class="step">3</span>
                            <span class="title">Payment Info</span>
                        </li>

                        <li data-target="#modal-step4">
                            <span class="step">4</span>
                            <span class="title">Other Info</span>
                        </li>
                    </ul>
                </div>

                <div class="modal-body step-content" id="modal-step-contents">
                    <div class="step-pane active" id="modal-step1">
                        <div class="center">
                            <h4 class="blue">Step 1</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step2">
                        <div class="center">
                            <h4 class="blue">Step 2</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step3">
                        <div class="center">
                            <h4 class="blue">Step 3</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step4">
                        <div class="center">
                            <h4 class="blue">Step 4</h4>
                        </div>
                    </div>
                </div>

                <div class="modal-footer wizard-actions">
                    <button class="btn btn-small btn-prev">
                        <i class="icon-arrow-left"></i>
                        Prev
                    </button>

                    <button class="btn btn-success btn-small btn-next" data-last="Finish ">
                        Next
                        <i class="icon-arrow-right icon-on-right"></i>
                    </button>

                    <button class="btn btn-danger btn-small pull-left" data-dismiss="modal">
                        <i class="icon-remove"></i>
                        Cancel
                    </button>
                </div>
            </div><!--PAGE CONTENT ENDS-->
        </div><!--/.span-->
    </div><!--/.row-fluid-->
</div><!--/.page-content-->
<style>

    .form-horizontal .control-label {
        float: left;
        margin-right: 10px;
        padding-top: 5px;
        text-align: right;
        width: 260px;
    }
</style>
<script>
    var resparent = "[]";
    var inputs = [];
    
    jQuery.extend({
    compare: function (arrayA, arrayB) {
        if (arrayA.length != arrayB.length) { return false; }
        // sort modifies original array
        // (which are passed by reference to our method!)
        // so clone the arrays before sorting
        var a = jQuery.extend(true, [], arrayA);
        var b = jQuery.extend(true, [], arrayB);
        a.sort(); 
        b.sort();
        for (var i = 0, l = a.length; i < l; i++) {
            if (a[i] !== b[i]) { 
                return false;
            }
        }
        return true;
    }
});
    
    function saveRes(nameInput) {
        var input = {},
                id_input = $("input[name=" + nameInput + "]").attr("id_input"),
                tipo = $("input[name=" + nameInput + "]").attr("tipo");

        switch (tipo) {
            case "texto":
                input.texto = $("#" + id_input + "").val()
                break;
        }

        $.ajax({
            url: "respuesta-save",
            data: {
                input: input,
                id_input: id_input,
                tipo: tipo
            },
            success: function (data) {

            }
        });

    }

    function getRespuesta(word) {
        $.ajax({
            async: false,
            url: "<?php echo $this->url("usuarios", array("controller" => "formulario", "action" => "resparent")) ?>",
            data: {word: word},
            type: "post",
            success: function (data) {
                resparent = data.join();
            }
        })
    }

    function seteoInputs(){
        inputs = [];
        $("#sample-form input[type=text]").each(function(){
            input = {};
            input.name = $(this).attr("name");
            input.val = $(this).val();
            inputs.push(input);
        })
    }

    function modificoDatos(obj){
        for(var i=0;i<inputs.length;i++){
            if(obj.attr("name") == inputs[i].name){
                val = obj.val();
                if(val == inputs[i].val){
                    return false;
                }
            }
        }
        seteoInputs();
        return true;
    }

    $(document).ready(function () {
        
        $(".wizard-steps").hide();
        
        actualizoPaginas();
        
        $(".wizard-steps").show();
        
        $(".chzn-select").chosen(); 
        
        arrobaToSpan();
        
        seteoInputs();
        
        
        $("#sample-form select.isMagic").change(function(){
            saveRespuesta($(this));
        });
        
        $("#sample-form input.isMagic").focusout(function(){
            if(modificoDatos($(this))){
                saveRespuesta($(this));
            }
        })
        
        function actualizoLabels(){
            
            $(".resp-span").each(function () {
                $(".main-container").css("opacity",0.3);
                $("#ajax_loader").show();
                span = $(this);
                nom = $(this).attr("nom");
                tipo = $(this).attr("tipo");
                
                $.ajax({
                    url:"<?php echo $this->url("usuarios", array("controller" => "respuesta", "action" => "actualizospan")) ?>",
                    type:"post",
                    async:false,
                    data:{
                        nom:nom,
                        tipo:tipo
                    },
                    success:function(data){
                        str = data[0];
                        span.text(str);
                        $(".main-container").css("opacity",1);
                        $("#ajax_loader").hide();
                    }
                })
            });
            
            
        }

        function arrobaToSpan() {

            $(".inputs-respuestas").each(function () {
                var txt = $(this).find("label").text();
                txt = txt.trim();
                
                words = txt.split(" ");

                words_res = "";

                    for (var i = 0; i < words.length; i++) {
                    if (words[i].indexOf("@") === 0) {
                        getRespuesta(words[i]);
                        words_res += resparent;
                    } else {
                        words_res += words[i] + " ";
                    }
                }

                $(this).find("label").html(words_res);

            });
        }
        
        function saveRespuesta(obj){
            respuesta = {};
            
            respuesta.nombre = obj.attr("name");
            respuesta.id_pagina = obj.attr("id_pagina");
            respuesta.tipo = obj.attr("tipo");
            respuesta.id_input = obj.attr("id_input");
            respuesta.texto = obj.val();
            
            $(".main-container").css("opacity",0.3);
            $("#ajax_loader").show();
            
            $.ajax({
                url:"<?php echo $this->url("usuarios", array("controller" => "respuesta", "action" => "add")) ?>",
                type:"post",
                data:{respuesta:respuesta},
                success:function(data){
                    actualizoLabels();
                }
            })
            
            return respuesta;
        }
        
        function intersection(a,b){
            
            typea = typeof a;
            typeb = typeof b;

            if(typea == "string"){
                a = a.split(",");
            }

            if(typeb == "string"){
                b = b.split(",");
            }
            
            return jQuery.compare(a, b);
        }
        
        function saveRespuestas(){
            var huboCambios = huboCambiosEnInputs();    
            if(huboCambios){
                respuestas = [];
                $("#step-container .active .inputs-respuestas").each(function(){
                    respuesta = {};

                    respuesta.tipo = $(this).find("input[type=text]").attr("tipo");

                    if(respuesta.tipo == "texto"){
                        respuesta.id_input = $(this).find("input[type=text]").attr("id_input");
                        respuesta.texto = $(this).find("input[type=text]").val();
                        respuesta.nombre = $(this).find("input[type=text]").attr("name");
                        respuesta.id_pagina = $(this).find("input[type=text]").attr("id_pagina");
                    }else{
                        respuesta.tipo = $(this).find("select").attr("tipo");
                        respuesta.nombre = $(this).find("select").attr("name");
                        respuesta.id_pagina = $(this).find("select").attr("id_pagina");
                        respuesta.id_input = $(this).find("select").attr("id_input");
                        
                        
                        if(!$(this).find(".chzn-select").length){
                            respuesta.texto = $(this).find("select option:selected").val();
                        }else{
                            respuesta.texto = $(this).find(".chzn-select").val()
                        }
                    }

                    respuestas.push(respuesta);
                });

                $(".main-container").css("opacity",0.3);
                $("#ajax_loader").show();

                $.ajax({
                    url:"<?php echo $this->url("usuarios", array("controller" => "respuesta", "action" => "adds")) ?>",
                    type:"post",
                    data:{respuestas:respuestas},
                    success:function(data){
                        actualizoLabels();
                    }
                })

                return respuesta;
                }
        }
        
        function huboCambiosEnInputs(){
            var cambios = false;
            $(".inputs-respuestas").each(function(){
                obj = $(this).find("input[tipo=texto]");
                
                if(obj.length){
                    a = obj.val() + "";
                    b = $(this).find("input[type=hidden]").val() + "";
                    if(a !== b){
                        console.log("obj in1: "+obj.val());
                        cambios = true;
                        $(this).find("input[type=hidden]").val(a)
                    }
                }else{
                    var s = $(this).find("select");
                    
                    //selectVal = s.val();
                    
                    
                    if(!$(this).find(".chzn-select").length){
                        selectVal = $(this).find("select option:selected").val();
                    }else{
                        selectVal = $(this).find(".chzn-select").val();
                    }
                    
                    
                    if(selectVal){
                        //selectVal = selectVal.split(",");
                        type = typeof selectVal;
                        
                        selVal2 = $(this).find("input[type=hidden]").val();
                        
                        type2 = typeof selVal2;
                        
                        if(type == "string" && type2 == "string"){
                            if(selectVal != selVal2){
                                cambios = true;
                            }
                        }else{
                            v = intersection(selectVal, selVal2);

                            if(!v){
                                cambios = true;
                            }
                        }
                        
                        /*for(var i=0; i<selectVal.length;i++){
                            var arr = $(this).find("input[type=hidden]").val();
                            arr = arr.split(",");
                            //if(selectVal[i] !== ){
                            var iguales = false;
                            console.log("obj: "+s.attr("name"));
                            for(var x = 0; x<arr.length;x++){
                                console.log("selectVal[i]: "+selectVal[i]);
                                console.log("arr[x]: "+arr[x]);
                                if(selectVal[i] == arr[x]){
                                    iguales = true;
                                }
                            }
                            console.log("iguales: "+iguales);
                            if(!iguales){
                                console.log("obj in: "+s.attr("name"));
                                
                                type = typeof selectVal;
                                
                                if(type != "string"){
                                    selectVal = selectVal.join()
                                }
                                
                                $(this).find("input[type=hidden]").val(selectVal);
                                cambios = true;
                            }
                        }*/
                    }
                }
                //hidden-response
            });
            
            console.log("cambios: "+cambios);
            return cambios;
        }
        
        $(".btn-next").mousedown(function(){
            $("#sample-form").submit();
            if($('#sample-form').valid()){
                saveRespuestas();
            }
            
        })
        
        $('#sample-form').validate({
            errorElement: 'span',
            errorClass: 'help-inline',
            focusInvalid: false,
            rules: {
                <?php foreach ($this->paginas as $pagina): ?>
                    <?php foreach ($pagina->getInputs() as $input): ?>
                        <?php echo ($input->getRequired())?$input->getNombre().": 'required',":"" ?><?php echo "\n"?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            },

            messages: {
                    email: {
                            required: "Please provide a valid email.",
                            email: "Please provide a valid email."
                    },
                    password: {
                            required: "Please specify a password.",
                            minlength: "Please specify a secure password."
                    },
                    subscription: "Please choose at least one option",
                    gender: "Please choose gender",
                    agree: "Please accept our policy"
            },

            invalidHandler: function (event, validator) { //display error alert on form submit   
                    $('.alert-error', $('.login-form')).show();
            },

            highlight: function (e) {
                    $(e).closest('.control-group').removeClass('info').addClass('error');
            },

            success: function (e) {
                    $(e).closest('.control-group').removeClass('error').addClass('info');
                    $(e).remove();
            },

            errorPlacement: function (error, element) {
                    if(element.is(':checkbox') || element.is(':radio')) {
                            var controls = element.closest('.controls');
                            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
                            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                    }
                    else if(element.is('.select2')) {
                            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                    }
                    else if(element.is('.chzn-select')) {
                            error.insertAfter(element.siblings('[class*="chzn-container"]:eq(0)'));
                    }
                    else error.insertAfter(element);
            },

            submitHandler: function (form) {
            },
            invalidHandler: function (form) {
            }
    });
    
    });
</script>