<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            Asistente para la confeccion de la Tesis

        </h1>
    </div><!--/.page-header-->

    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->


            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-header widget-header-blue widget-header-flat">
                            <h4 class="lighter">New Item Wizard</h4>

                        </div>

                        <div class="widget-body">
                            <div class="widget-main">
                                <div class="row-fluid">
                                    <div id="fuelux-wizard" class="row-fluid hide" data-target="#step-container">
                                        <ul class="wizard-steps">
                                            <?php $count = 1; ?>
                                            <?php foreach ($this->paginas as $pagina): ?>
                                                <li data-target="#step<?php echo $count ?>" class="<?php echo ($count === 1 ) ? "active" : "" ?>">
                                                    <span class="step"><?php echo $count; ?></span>
                                                    <span class="title"><?php echo $pagina->getTitulo() ?></span>
                                                </li>
                                                <?php $count++; ?>
                                            <?php endforeach; ?>
                                        </ul>
                                            <div class="row-fluid wizard-actions wizard-actions-top">
                                                <a class="btn btn-prev">
                                                    <i class="icon-arrow-left"></i>
                                                    Prev
                                                </a>

                                                <a class="btn btn-success btn-next" data-last="Finish ">
                                                    Next
                                                    <i class="icon-arrow-right icon-on-right"></i>
                                                </a>
                                            </div>
                                    </div>

                                    <div class="step-content row-fluid position-relative" id="step-container">
                                        <?php $count = 1; ?>
                                        <?php foreach ($this->paginas as $pagina): ?>
                                            <div class="step-pane <?php echo ($count === 1 ) ? "active" : "" ?>" id="step<?php echo $count ?>">
                                                <h4 class="header green"><?php echo $pagina->getTitulo() ?></h4>
                                                <form enctype="multipart/form-data" class="form-horizontal" id="sample-form" >
                                                    <?php foreach ($pagina->getInputs() as $input): ?>
                                                        <div class="control-group inputs-respuestas">
                                                            <label nom="<?php echo $input->getNombre() ?>" id="label-<?php echo $input->getNombre() ?>" class="control-label" for=""><?php echo $input->getLabel() ?></label>
                                                            <div class="controls">
                                                                <?php 
                                                                    $tamanio = $input->getTamanio();
                                                                    
                                                                    switch ($tamanio) {
                                                                        case "Largo":
                                                                            $tamanio = "50";
                                                                            break;
                                                                        case "Mediano":
                                                                            $tamanio = "25";

                                                                            break;
                                                                        case "Pequeño":
                                                                            $tamanio = "12.5";
                                                                            break;
                                                                        default:
                                                                            $tamanio = "50";
                                                                            break;
                                                                    }
                                                                    
                                                                    if($input->getTipo()=="imagen"){
                                                                        $tamanio = "22";
                                                                        if($input->getControl()->getArchivo()){
                                                                            $tamanio = "27";
                                                                        }
                                                                    }
                                                                    
                                                                    ?>
                                                                <span class="span6 input-icon input-icon-right" style="width: <?php echo $tamanio ?>% !important">
                                                                    <?php if($input->getTipo()=="texto"):?>
                                                                        <?php if($input->getControl()->getRespuestasRequeridas() > 0 ):?>
                                                                        <?php for($i = 0; $i < $input->getControl()->getRespuestasRequeridas(); $i++):?>
                                                                        <input  
                                                                               numero_respuesta ="<?php echo $i+1 ?>"
                                                                               placeholder="<?php echo $input->getControl()->getEjemplo() ?>" 
                                                                               value="<?php echo $input->getRespuesta($i+1) ?>" 
                                                                               id_input="<?php echo $input->getId() ?>" 
                                                                               tipo="<?php echo $input->getTipo() ?>" 
                                                                               id_pagina="<?php echo $input->getIdPagina() ?>"  
                                                                               name="<?php echo $input->getNombre() ?>" 
                                                                               class="span12 <?php echo ($input->getIsMagic())?"isMagic":"" ?>" 
                                                                               <?php $validacion = strtolower($input->getControl()->getValidacion()) ?>
                                                                               type="<?php echo ($validacion != "" && $validacion != "validacion")?$validacion:"text" ?>" 
                                                                               id="" <?php echo ($input->getRequired()) ? "required='required'" : "" ?>/>
                                                                        <input type="hidden" name="hidden-<?php echo $input->getNombre() ?>" class="span12 hidden-response" type="text" id="" value="<?php echo $input->getRespuesta($i+1) ?>"/>
                                                                        <?php endfor; ?>
                                                                    <?php endif; ?>
                                                                    <?php elseif($input->getTipo()=="dropdown"):?>
                                                                    <?php
                                                                    $sc = "";
                                                                    $stipo = $input->getControl()->getTipo();
                                                                    if($input->getIsMagic()){
                                                                        $sc = "isMagic";
                                                                    }
                                                                    $valuesSelected = array();
                                                                    ?>
                                                                    <select style="width: <?php echo $tamanio*2 ?>% !important" class="<?php echo $sc ?><?php echo ($stipo == "multi")? "chzn-select":"" ?>" <?php echo ($stipo == "multi")?"multiple='multiple'":"" ?> id_input="<?php echo $input->getId() ?>" tipo="<?php echo $input->getTipo() ?>" id_pagina="<?php echo $input->getIdPagina() ?>"  name="<?php echo $input->getNombre() ?>" <?php echo ($input->getRequired()) ? "required" : ""?>>
                                                                        <option value="">SELECCIONAR</option>
                                                                        <?php $control = $input->getControl();?>
                                                                        <?php foreach($control->getValues() as $value):?>
                                                                        <option 
                                                                            <?php 
                                                                            if($value->getSelected()){
                                                                                echo "selected='selected'";
                                                                                $valuesSelected[] = $value->getId();
                                                                            } 
                                                                            ?> 
                                                                            value="<?php echo $value->getId() ?>"><?php echo $value->getValue() ?></option>
                                                                        <?php endforeach;?>
                                                                    </select>
                                                                    <input type="hidden" name="hidden-<?php echo $input->getNombre() ?>" class="span12 hidden-response" type="text" id="" value="<?php echo implode(",", $valuesSelected) ?>"/>
                                                                    <?php elseif($input->getTipo()=="fecha"):?>
                                                                                <?php 
                                                                                $fechaTipo = $input->getControl()->getTipoFecha(); ?>
                                                                                <?php if($fechaTipo == "simple"): ?>
                                                                                
                                                                                <div class="control-group">
                                                                                        <div class="row-fluid input-append">
                                                                                                <input 
                                                                                                    style="width: calc(<?php echo $tamanio*2 ?>% - 36px) ! important;"
                                                                                                    id_input="<?php echo $input->getId() ?>" id_pagina="<?php echo $input->getIdPagina() ?>"  name="<?php echo $input->getNombre() ?>"
                                                                                                    tipo="fecha" tipofecha="simple" class="span10 date-picker fechadatepicker" id="id-date-picker-1" type="text" data-date-format="dd-mm-yyyy" 
                                                                                                    value="<?php echo $input->getRespuesta() ?>"
                                                                                                    />
                                                                                                <input type="hidden" name="hidden-<?php echo $input->getNombre() ?>" class="span12 hidden-response" id="" value="<?php echo $input->getRespuesta() ?>"/>
                                                                                                <span class="add-on">
                                                                                                        <i class="icon-calendar"></i>
                                                                                                </span>
                                                                                        </div>
                                                                                </div>
                                                                                
                                                                                <?php else: ?>

                                                                                <div class="control-group">
                                                                                        <div class="row-fluid input-prepend">
                                                                                                <span class="add-on">
                                                                                                        <i class="icon-calendar"></i>
                                                                                                </span>

                                                                                                <input 
                                                                                                    style="width: calc(<?php echo $tamanio*2 ?>% - 27px) ! important;"
                                                                                                    id_input="<?php echo $input->getId() ?>" id_pagina="<?php echo $input->getIdPagina() ?>"  name="<?php echo $input->getNombre() ?>"
                                                                                                    tipo="fecha" tipofecha="rango" class="span10 fechadatepicker fechadatepicker-rango" type="text" name="date-range-picker" id="id-date-range-picker-1" 
                                                                                                    value="<?php echo $input->getRespuesta() ?>"
                                                                                                    />
                                                                                                <input type="hidden" name="hidden-<?php echo $input->getNombre() ?>" class="span12 hidden-response" id="" value="<?php echo $input->getRespuesta() ?>"/>
                                                                                        </div>
                                                                                </div>
                                                                                
                                                                                <?php endif; ?>
                                                                        
                                                                    <?php elseif($input->getTipo()=="imagen"):?>
                                                                    <div class="widget-main">
                                                                        
                                                                            <input 
                                                                                estado=""
                                                                                type="file" 
                                                                                id_input="<?php echo $input->getId() ?>" 
                                                                                tipo="<?php echo $input->getTipo() ?>" 
                                                                                id_pagina="<?php echo $input->getIdPagina() ?>"  
                                                                                name="<?php echo $input->getNombre() ?>" 
                                                                                class="id-input-file" <?php //echo ($input->getRequired()) ? "required='required'" : "" ?> />
                                                                            <?php if($archivo = $input->getControl()->getArchivo()): ?>
                                                                            <img class="imagen-control" width="38" src="data:image/jpeg;base64,<?php echo base64_encode($archivo); ?>">
                                                                            <a href="#" class="remove remove-imagen"><i class="icon-remove"></i></a>
                                                                        <?php endif; ?>
                                                                    </div>
                                                                    <?php endif;?>
                                                                    <?php if($input->getAyuda()):?>    
                                                                    <i class="tooltip-success icon-question-sign" data-rel="tooltip" data-placement="right" title="<?php echo $input->getAyuda(); ?>"></i>
                                                                    <?php endif;?>
                                                                </span>
                                                                <?php if($input->getLinkAyuda()):?>    
                                                                <a class="link_ayuda" target="_blank" href="<?php echo $input->getLinkAyuda(); ?>">Tutorial</a>
                                                                <?php endif;?>
                                                                <!--<span class="help-inline">Something may have gone wrong</span>-->
                                                            </div>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </form>
                                            </div>
                                            <?php $count++; ?>
                                        <?php endforeach; ?>
                                    </div>

                                    <hr />
                                    <div class="row-fluid wizard-actions">
                                        <button class="btn btn-prev">
                                            <i class="icon-arrow-left"></i>
                                            Prev
                                        </button>

                                        <button class="btn btn-success btn-next btn-next-wizard" data-last="Finish ">
                                            Next
                                            <i class="icon-arrow-right icon-on-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </div><!--/widget-main-->
                        </div><!--/widget-body-->
                    </div>
                </div>
            </div>

            <div id="modal-wizard" class="modal hide">
                <div class="modal-header" data-target="#modal-step-contents">
                    <ul class="wizard-steps clearfix">
                        <li data-target="#modal-step1" class="active">
                            <span class="step">1</span>
                            <span class="title">Validation states</span>
                        </li>

                        <li data-target="#modal-step2">
                            <span class="step">2</span>
                            <span class="title">Alerts</span>
                        </li>

                        <li data-target="#modal-step3">
                            <span class="step">3</span>
                            <span class="title">Payment Info</span>
                        </li>

                        <li data-target="#modal-step4">
                            <span class="step">4</span>
                            <span class="title">Other Info</span>
                        </li>
                    </ul>
                </div>

                <div class="modal-body step-content" id="modal-step-contents">
                    <div class="step-pane active" id="modal-step1">
                        <div class="center">
                            <h4 class="blue">Step 1</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step2">
                        <div class="center">
                            <h4 class="blue">Step 2</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step3">
                        <div class="center">
                            <h4 class="blue">Step 3</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step4">
                        <div class="center">
                            <h4 class="blue">Step 4</h4>
                        </div>
                    </div>
                </div>

                <div class="modal-footer wizard-actions">
                    <button class="btn btn-small btn-prev">
                        <i class="icon-arrow-left"></i>
                        Prev
                    </button>

                    <button class="btn btn-success btn-small btn-next" data-last="Finish ">
                        Next
                        <i class="icon-arrow-right icon-on-right"></i>
                    </button>

                    <button class="btn btn-danger btn-small pull-left" data-dismiss="modal">
                        <i class="icon-remove"></i>
                        Cancel
                    </button>
                </div>
            </div><!--PAGE CONTENT ENDS-->
        </div><!--/.span-->
    </div><!--/.row-fluid-->
</div><!--/.page-content-->
<style>
    .wizard-actions-top {
    margin-bottom: 10px;
    margin-top: 20px;
}
    .ace-file-input{
        float: left;
    }
    .imagen-control {
        border: 3px solid #438eb9;
        float: left;
        height: 36px;
        margin-right: 5px;
        margin-top: -6px;
    }
    .tooltip-inner {
        max-width: 250px !important;
        width: 250px;
    }

    .form-horizontal .control-label {
        float: left;
        margin-right: 10px;
        padding-top: 5px;
        text-align: right;
        width: 260px;
    }
    .fechadatepicker{
        width: 479px !important;
    }
    .fechadatepicker-rango{
        width: 516px !important;
    }
    .input-append .add-on{
        width: 25px;
    }
    .input-icon.input-icon-right > input {
        margin-bottom: 2px;
    }
</style>
<script>
    var resparent = "[]";
    var inputs = [];
    
    jQuery.extend({
    compare: function (arrayA, arrayB) {
        if (arrayA.length != arrayB.length) { return false; }
        // sort modifies original array
        // (which are passed by reference to our method!)
        // so clone the arrays before sorting
        var a = jQuery.extend(true, [], arrayA);
        var b = jQuery.extend(true, [], arrayB);
        a.sort(); 
        b.sort();
        for (var i = 0, l = a.length; i < l; i++) {
            if (a[i] !== b[i]) { 
                return false;
            }
        }
        return true;
    }
});
    
    function saveRes(nameInput) {
        var input = {},
                id_input = $("input[name=" + nameInput + "]").attr("id_input"),
                tipo = $("input[name=" + nameInput + "]").attr("tipo");

        switch (tipo) {
            case "texto":
                input.texto = $("#" + id_input + "").val()
                break;
        }

        $.ajax({
            url: "respuesta-save",
            data: {
                input: input,
                id_input: id_input,
                tipo: tipo
            },
            success: function (data) {

            }
        });

    }

    function getRespuesta(word) {
        $.ajax({
            async: false,
            url: "<?php echo $this->url("usuarios", array("controller" => "formulario", "action" => "resparent")) ?>",
            data: {word: word},
            type: "post",
            success: function (data) {
                resparent = data.join();
            }
        })
    }

    function seteoInputs(){
        inputs = [];
        $("#sample-form input[type=text]").each(function(){
            input = {};
            input.name = $(this).attr("name");
            input.val = $(this).val();
            inputs.push(input);
        })
        $("#sample-form input[type=email]").each(function(){
            input = {};
            input.name = $(this).attr("name");
            input.val = $(this).val();
            inputs.push(input);
        })
    }

    function modificoDatos(obj){
        for(var i=0;i<inputs.length;i++){
            if(obj.attr("name") == inputs[i].name){
                val = obj.val();
                if(val == inputs[i].val){
                    return false;
                }
            }
        }
        seteoInputs();
        return true;
    }

    $(document).ready(function () {
        
        $(document).on("click", ".wizard-actions-top a.btn-prev", function () {
            $("button.btn-prev").trigger("click");
        })

        $(document).on("click", ".wizard-actions-top a.btn-next", function () {
            $("button.btn-next").trigger("click");
        })
        
        $(".wizard-steps").hide();
        
        actualizoPaginas();
        
        $(".wizard-steps").show();
        
        $(".chzn-select").chosen(); 
        
        arrobaToSpan();
        
        seteoInputs();
        
        
        $("#sample-form select.isMagic").change(function(){
            saveRespuesta($(this));
        });
        
        $("#sample-form input.isMagic").focusout(function(){
            if(modificoDatos($(this))){
                saveRespuesta($(this));
            }
        })
        
        function actualizoLabels(){
            
            $(".resp-span").each(function () {
                $(".main-container").css("opacity",0.3);
                $("#ajax_loader").show();
                span = $(this);
                nom = $(this).attr("nom");
                tipo = $(this).attr("tipo");
                
                $.ajax({
                    url:"<?php echo $this->url("usuarios", array("controller" => "respuesta", "action" => "actualizospan")) ?>",
                    type:"post",
                    async:false,
                    data:{
                        nom:nom,
                        tipo:tipo
                    },
                    success:function(data){
                        str = data[0];
                        span.text(str);
                        $(".main-container").css("opacity",1);
                        $("#ajax_loader").hide();
                    }
                })
            });
            
            
        }

        function arrobaToSpan() {

            $(".inputs-respuestas").each(function () {
                var txt = $(this).find("label").text();
                txt = txt.trim();
                
                words = txt.split(" ");

                words_res = "";

                    for (var i = 0; i < words.length; i++) {
                    if (words[i].indexOf("@") === 0) {
                        getRespuesta(words[i]);
                        words_res += resparent;
                    } else {
                        words_res += words[i] + " ";
                    }
                }

                $(this).find("label").html(words_res);

            });
        }
        
        function saveRespuesta(obj){
            respuesta = {};
            
            respuesta.nombre = obj.attr("name");
            respuesta.id_pagina = obj.attr("id_pagina");
            respuesta.tipo = obj.attr("tipo");
            respuesta.id_input = obj.attr("id_input");
            respuesta.texto = obj.val();
            
            $(".main-container").css("opacity",0.3);
            $("#ajax_loader").show();
            
            $.ajax({
                url:"<?php echo $this->url("usuarios", array("controller" => "respuesta", "action" => "add")) ?>",
                type:"post",
                data:{respuesta:respuesta},
                success:function(data){
                    actualizoLabels();
                }
            })
            
            return respuesta;
        }
        
        function intersection(a,b){
            
            typea = typeof a;
            typeb = typeof b;

            if(typea == "string"){
                a = a.split(",");
            }

            if(typeb == "string"){
                b = b.split(",");
            }
            
            return jQuery.compare(a, b);
        }
        
        function saveRespuestas(){
            var formData = new FormData();
            var huboCambios = huboCambiosEnInputs();    
            if(huboCambios){
                respuestas = [];
                $("#step-container .active .inputs-respuestas").each(function(){
                    respuesta = {};

                    respuesta.id = $(this).find("input[type=text]").attr("id");
                    respuesta.tipo = $(this).find("input[type=text]").attr("tipo");
                    
                    if(!respuesta.tipo || respuesta.tipo == "undefined"){
                        respuesta.tipo = $(this).find("input[type=email]").attr("tipo");
                    }
                    
                    if(!respuesta.tipo || respuesta.tipo == "undefined"){
                        respuesta.tipo = $(this).find("input[type=file]").attr("tipo");
                    }

                    if(respuesta.tipo == "texto"){
                        $(this).find("input[type=text]").each(function(){
                            respuesta_temp = {};
                            respuesta_temp.id = respuesta.id;
                            respuesta_temp.tipo = respuesta.tipo;
                            respuesta_temp.id_input = $(this).attr("id_input");
                            respuesta_temp.numeroRespuesta = $(this).attr("numero_respuesta");
                            respuesta_temp.texto = $(this).val();
                            respuesta_temp.nombre = $(this).attr("name");
                            respuesta_temp.id_pagina = $(this).attr("id_pagina");
                            respuestas.push(respuesta_temp);
                        })
                    }else{
                        if(respuesta.tipo == "fecha"){
                            tipo = $(this).find(".fechadatepicker").attr("tipofecha");
                            respuesta.id_input = $(this).find(".fechadatepicker").attr("id_input");
                            respuesta.texto = $(this).find(".fechadatepicker").val();
                            respuesta.nombre = $(this).find(".fechadatepicker").attr("name");
                            respuesta.id_pagina = $(this).find(".fechadatepicker").attr("id_pagina");
                            if(tipo == "simple"){
                                val = $(this).find(".fechadatepicker").val();
                                respuesta.desde = val;
                                respuesta.hasta = "";
                            }else{
                                val = $(this).find(".fechadatepicker").val();
                                val = $.trim(val);
                                val = val.split("-");
                                respuesta.desde = val[0];
                                respuesta.hasta = val[1];
                            }
                            
                        }else{
                            if(respuesta.tipo == "imagen"){
                                var nombre = $(this).find("input[type=file]").attr("name");
                                formData.append(nombre,$(this).find("input[type=file]")[0].files[0]);
                                respuesta.id_input = $(this).find("input[type=file]").attr("id_input");
                                respuesta.archivo = $(this).find("input[type=file]").val();
                                respuesta.nombre = $(this).find("input[type=file]").attr("name");
                                respuesta.estado = $(this).find("input[type=file]").attr("estado");
                                respuesta.id_pagina = $(this).find("input[type=file]").attr("id_pagina");
                                //respuesta.archivo = imagen;
                            }else{
                                respuesta.tipo = $(this).find("select").attr("tipo");
                                respuesta.nombre = $(this).find("select").attr("name");
                                respuesta.id_pagina = $(this).find("select").attr("id_pagina");
                                respuesta.id_input = $(this).find("select").attr("id_input");


                                if(!$(this).find(".chzn-select").length){
                                    respuesta.texto = $(this).find("select option:selected").val();
                                }else{
                                    respuesta.texto = $(this).find(".chzn-select").val()
                                }
                            }
                            
                        }
                    }
                    
                    if(respuesta.tipo != "texto"){
                        respuestas.push(respuesta);
                    }
                });
                
                console.log(JSON.stringify(respuestas));
                
                formData.append("respuestas",JSON.stringify(respuestas));

                $(".main-container").css("opacity",0.3);
                $("#ajax_loader").show();

                $.ajax({
                    url:"<?php echo $this->url("usuarios", array("controller" => "respuesta", "action" => "adds")) ?>",
                    type:"post",
                    data : formData,
                    contentType : false,
                    processData : false,
                    /*data:{respuestas:respuestas,imagen:imagen},*/
                    success:function(data){
                        actualizoLabels();
                    }
                })

                return respuesta;
                }
        }
        
        function huboCambiosEnInputs(){
            var cambios = false;
            $(".inputs-respuestas").find("input[type=file]").each(function(){
                console.log($(this).attr("estado"));
                if($(this).attr("estado") != ""){
                    cambios = true;
                }
            });
            $(".inputs-respuestas").each(function(){
                obj = $(this).find("input[tipo=texto]");
                if(obj.length){
                    if(obj.length == 1){
                        a = obj.val() + "";
                        b = $(this).find("input[type=hidden]").val() + "";
                        if(a !== b){
                            console.log("obj in1: "+obj.val());
                            cambios = true;
                            $(this).find("input[type=hidden]").val(a)
                        }
                    }else{
                        $(this).find("input[tipo=texto]").each(function(){
                            a = $(this).val() + "";
                            b = $(this).next().val() + "";
                            if(a !== b){
                                console.log("obj in1: "+$(this).val());
                                cambios = true;
                                $(this).next().val(a)
                            }
                        });
                    }
                }else{
                    
                    obj = $(this).find("input[tipo=fecha]");
                
                    if(obj.length){
                    a = obj.val() + "";
                    b = $(this).find("input[type=hidden]").val() + "";
                    if(a !== b){
                        console.log("obj in1: "+obj.val());
                        cambios = true;
                        $(this).find("input[type=hidden]").val(a)
                    }
                    }else
                    {
                    
                    
                    var s = $(this).find("select");
                    
                    //selectVal = s.val();
                    
                    
                    if(!$(this).find(".chzn-select").length){
                        selectVal = $(this).find("select option:selected").val();
                    }else{
                        selectVal = $(this).find(".chzn-select").val();
                    }
                    
                    
                    if(selectVal){
                        //selectVal = selectVal.split(",");
                        type = typeof selectVal;
                        
                        selVal2 = $(this).find("input[type=hidden]").val();
                        
                        type2 = typeof selVal2;
                        
                        if(type == "string" && type2 == "string"){
                            if(selectVal != selVal2){
                                cambios = true;
                            }
                        }else{
                            v = intersection(selectVal, selVal2);

                            if(!v){
                                cambios = true;
                            }
                        }
                        
                        /*for(var i=0; i<selectVal.length;i++){
                            var arr = $(this).find("input[type=hidden]").val();
                            arr = arr.split(",");
                            //if(selectVal[i] !== ){
                            var iguales = false;
                            console.log("obj: "+s.attr("name"));
                            for(var x = 0; x<arr.length;x++){
                                console.log("selectVal[i]: "+selectVal[i]);
                                console.log("arr[x]: "+arr[x]);
                                if(selectVal[i] == arr[x]){
                                    iguales = true;
                                }
                            }
                            console.log("iguales: "+iguales);
                            if(!iguales){
                                console.log("obj in: "+s.attr("name"));
                                
                                type = typeof selectVal;
                                
                                if(type != "string"){
                                    selectVal = selectVal.join()
                                }
                                
                                $(this).find("input[type=hidden]").val(selectVal);
                                cambios = true;
                            }
                        }*/
                    }
                    }
                }
                //hidden-response
            });
            
            console.log("cambios: "+cambios);
            return cambios;
        }
        
        $(".btn-next").mousedown(function(){
            $("#sample-form").submit();
            var r = $('#sample-form').valid();
            console.log("valid: "+r);
            if($('#sample-form').valid()){
                saveRespuestas();
            }
            
        })
        
        $('#sample-form').validate({
            errorElement: 'span',
            errorClass: 'help-inline',
            focusInvalid: false,
            rules: {
                <?php foreach ($this->paginas as $pagina): ?>
                    <?php foreach ($pagina->getInputs() as $input): ?>
                        <?php if($input->getTipo()!= "imagen"):?>
                            <?php echo ($input->getRequired())?$input->getNombre().": 'required',":"" ?><?php echo "\n"?>
                        <?php endif;?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            },

            messages: {
                    email: {
                            required: "Please provide a valid email.",
                            email: "Please provide a valid email."
                    },
                    password: {
                            required: "Please specify a password.",
                            minlength: "Please specify a secure password."
                    },
                    subscription: "Please choose at least one option",
                    gender: "Please choose gender",
                    agree: "Please accept our policy"
            },

            invalidHandler: function (event, validator) { //display error alert on form submit   
                    $('.alert-error', $('.login-form')).show();
            },

            highlight: function (e) {
                    $(e).closest('.control-group').removeClass('info').addClass('error');
            },

            success: function (e) {
                    $(e).closest('.control-group').removeClass('error').addClass('info');
                    $(e).remove();
            },

            errorPlacement: function (error, element) {
                    if(element.is(':checkbox') || element.is(':radio')) {
                            var controls = element.closest('.controls');
                            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
                            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                    }
                    else if(element.is('.select2')) {
                            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                    }
                    else if(element.is('.chzn-select')) {
                            error.insertAfter(element.siblings('[class*="chzn-container"]:eq(0)'));
                    }
                    else error.insertAfter(element);
            },

            submitHandler: function (form) {
            },
            invalidHandler: function (form) {
            }
    });
        
        $('.date-picker').datepicker().next().on(ace.click_event, function(){
                $(this).prev().focus();
        });
        $('.fechadatepicker-rango').daterangepicker({
            yearRange: '2010:2020',
        }).prev().on(ace.click_event, function(){
                $(this).next().focus();
        });
        
        $('.id-input-file').change(function(){
            $(this).attr("estado","change");
        })
        
        $('.id-input-file').ace_file_input({
                no_file:'No File ...',
                btn_choose:'Choose',
                btn_change:'Change',
                droppable:false,
                onchange:null,
                thumbnail:false //| true | large
                //whitelist:'gif|png|jpg|jpeg'
                //blacklist:'exe|php'
                //onchange:''
                //
        });
        
        $(function(){
           $(".id-input-file").each(function(){
               var img = $(this).parent().find("imagen-control")
               if(!img.length){
                   $(this).val("imagen");   
               }
           }) 
        });
        
        $(".remove-imagen").click(function(e){
            e.preventDefault();
            $(this).prev().remove();
            $(this).parent().find("input[type=file]").attr("estado","baja");
            $(this).remove();
        })
    });
</script>
