<div class="page-content">
    <div class="page-header position-relative">
        <h1>
            Asistente para la confeccion de la Tesis
        </h1>
    </div><!--/.page-header-->

    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->


            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-header widget-header-blue widget-header-flat">
                            <h4 class="lighter h4-action-paginas">Pasos
                                <div class="action-paginas hidden-phone visible-desktop action-buttons">
                                    <a id="edit-pagina" href="<?php echo $this->url("usuarios", array("controller" => "pagina", "action" => "update")) ?>/id_pagina" class="green">
                                        <i class="icon-pencil bigger-130"></i>
                                    </a>
                                    <a id="del-pagina" href="<?php echo $this->url("usuarios", array("controller" => "pagina", "action" => "delete")) ?>/id_pagina" class="red remove">
                                        <i class="icon-trash bigger-130"></i>
                                    </a>
                                    <a id="add-pagina" href="<?php echo $this->url("usuarios", array("controller" => "pagina", "action" => "add")) ?>/id_pagina" class="red remove">
                                        <i class="icon-plus-sign bigger-130"></i>
                                    </a>
                                </div>
                            </h4>

                        </div>

                        <div class="widget-body">
                            <div class="widget-main">
                                <div class="row-fluid">
                                    <div id="fuelux-wizard" class="row-fluid hide" data-target="#step-container">
                                        <ul class="wizard-steps">
                                            <?php $count = 1; ?>
                                            <?php foreach ($this->formulario->getPaginas() as $pagina): ?>
                                                <li id_page="<?php echo $pagina->getId() ?>" data-target="#step<?php echo $count ?>" class="<?php echo ($count === 1 ) ? "active" : "" ?>">
                                                    <span class="step"><?php echo $count; ?></span>
                                                    <span class="title"><?php echo $pagina->getTitulo() ?></span>
                                                </li>
                                                <?php $count++; ?>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>

                                    <hr />
                                    <div class="step-content row-fluid position-relative" id="step-container">

                                        <div class="widget-header widget-header-blue widget-header-flat">
                                            <h4 class="lighter h4-action-paginas">Controles 
                                                <div class="action-paginas hidden-phone visible-desktop action-buttons">
                                                    <a id="add-input" class="red remove">
                                                        <i class="icon-plus-sign bigger-130"></i>
                                                    </a>
                                                </div>
                                            </h4>
                                        </div>

                                        <?php $count = 1; ?>
                                        <?php foreach ($this->formulario->getPaginas() as $pagina): ?>

                                            <div class="step-pane <?php echo ($count === 1 ) ? "active" : "" ?>" id="step<?php echo $count ?>">

                                                <form class="form-horizontal" id="inputs-collections" >
                                                    <?php foreach ($pagina->getInputs() as $input): ?>
                                                        <div class="control-group item-input">
                                                            <div class="alert alert-info" id_input="<?php echo $input->getId() ?>">
                                                                <i class="icon-move bigger-130"></i>
                                                                <button data-dismiss="alert" class="close" type="button">
                                                                    <i class="ace-icon fa fa-times"></i>
                                                                </button>
                                                                <strong><?php echo $input->getNombre() ?></strong>
                                                                <?php echo $input->getLabel() ?>
                                                                <div class="action-paginas hidden-phone visible-desktop action-buttons">
                                                                    <a href="#" class="green edit-input">
                                                                        <i class="icon-pencil bigger-130"></i>
                                                                    </a>
                                                                    <a href="#" class="red remove del-item">
                                                                        <i class="icon-trash bigger-130"></i>
                                                                    </a>
                                                                </div>
                                                                <br>
                                                            </div>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </form>
                                            </div>
                                            <?php $count++; ?>
                                        <?php endforeach; ?>
                                    </div>

                                    <hr />
                                    <div class="row-fluid wizard-actions">
                                        <button class="btn btn-prev">
                                            <i class="icon-arrow-left"></i>
                                            Prev
                                        </button>

                                        <button class="btn btn-success btn-next" data-last="Finish ">
                                            Next
                                            <i class="icon-arrow-right icon-on-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </div><!--/widget-main-->
                        </div><!--/widget-body-->
                    </div>
                </div>
            </div>

            <div id="modal-wizard" class="modal hide">
                <div class="modal-header" data-target="#modal-step-contents">
                    <ul class="wizard-steps clearfix">
                        <li data-target="#modal-step1" class="active">
                            <span class="step">1</span>
                            <span class="title">Validation states</span>
                        </li>

                        <li data-target="#modal-step2">
                            <span class="step">2</span>
                            <span class="title">Alerts</span>
                        </li>

                        <li data-target="#modal-step3">
                            <span class="step">3</span>
                            <span class="title">Payment Info</span>
                        </li>

                        <li data-target="#modal-step4">
                            <span class="step">4</span>
                            <span class="title">Other Info</span>
                        </li>
                    </ul>
                </div>

                <div class="modal-body step-content" id="modal-step-contents">
                    <div class="step-pane active" id="modal-step1">
                        <div class="center">
                            <h4 class="blue">Step 1</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step2">
                        <div class="center">
                            <h4 class="blue">Step 2</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step3">
                        <div class="center">
                            <h4 class="blue">Step 3</h4>
                        </div>
                    </div>

                    <div class="step-pane" id="modal-step4">
                        <div class="center">
                            <h4 class="blue">Step 4</h4>
                        </div>
                    </div>
                </div>

                <div class="modal-footer wizard-actions">
                    <button class="btn btn-small btn-prev">
                        <i class="icon-arrow-left"></i>
                        Prev
                    </button>

                    <button class="btn btn-success btn-small btn-next" data-last="Finish ">
                        Next
                        <i class="icon-arrow-right icon-on-right"></i>
                    </button>

                    <button class="btn btn-danger btn-small pull-left" data-dismiss="modal">
                        <i class="icon-remove"></i>
                        Cancel
                    </button>
                </div>
            </div><!--PAGE CONTENT ENDS-->
        </div><!--/.span-->
    </div><!--/.row-fluid-->
</div><!--/.page-content-->
<style>
    .save-formulario{
        margin-right: -8px;
    }   
    #save{
        float: right;
    }
    .tab-content {
        border: 1px solid #c5d0dc;
        padding: 19px 12px;
        position: relative;
        z-index: 11;
    }
    .modal-body input{
        /*width: 384px;*/
    }
    .span6 {
        width: auto;
    }
    #add-input{
        cursor:pointer
    }
    textarea.mention {
        width: calc(100% - 12px);
    }
    .modal-body h3{
        margin:0 5px 0 5px;
    }
    .alert{
        margin-bottom:0;
    }
    .modal-body{
        max-height: none !important;
    }
    .icon-move,.wizard-steps li .step{
        cursor:move;
    }
    .alert {
        padding: 8px 7px 8px 14px;
    }
    select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
        margin-bottom: 20px;
    }
    .item-input .icon-move {
        margin-right: 5px;
    }
    
    .item-input strong{
        margin-right: 6px;
    }
</style>
<script>
    $(document).ready(function () {
        $("#add-input").on(ace.click_event, function (e) {
            e.preventDefault();
            bootbox.dialog({});
            $.ajax({
                url: "formulario_edit/popup",
                data: "",
                success: function (data) {
                    $(".bootbox .modal-body").html(data);
                    $('#numero-respuestas')
                            .ace_spinner({value: 1, min: 0, max: 200, step: 1, btn_up_class: 'btn-info', btn_down_class: 'btn-info'})
                            .on('change', function () {
                            });

                    $(function () {
                        $('textarea.mention').mentionsInput({
                            onDataRequest: function (mode, query, callback) {
                                var strquery = 'query=' + query;
                                $.getJSON("<?php echo $this->url("usuarios", array("controller" => "input", "action" => "getInputsJson")) ?>", strquery, function (responseData) {
                                    responseData = _.filter(responseData, function (item) {
                                        return item.name.toLowerCase().indexOf(query.toLowerCase()) > -1
                                    });
                                    callback.call(this, responseData);
                                });
                            }
                        });

                    });
                }
            })
        });

        $(document).on("click", ".edit-input", function (e) {
            e.preventDefault();
            var idinput = $(this).parent().parent().attr("id_input");
            bootbox.dialog({});
            $.ajax({
                url: "formulario_edit/popupeditinput",
                data: {idinput: idinput},
                success: function (data) {
                    $(".bootbox .modal-body").html(data);



                    $('#numero-respuestas')
                            .ace_spinner({value: 1, min: 0, max: 200, step: 1, btn_up_class: 'btn-info', btn_down_class: 'btn-info'})
                            .on('change', function () {
                            });

                    $(function () {
                        $('textarea.mention').mentionsInput({
                            onDataRequest: function (mode, query, callback) {
                                var strquery = 'query=' + query;
                                $.getJSON("<?php echo $this->url("usuarios", array("controller" => "input", "action" => "getInputsJson")) ?>", strquery, function (responseData) {
                                    responseData = _.filter(responseData, function (item) {
                                        return item.name.toLowerCase().indexOf(query.toLowerCase()) > -1
                                    });
                                    callback.call(this, responseData);
                                });
                            }
                        });

                    });

                    var textareaval = $(".textarea-mention").val();
                    $('textarea.mention').val(textareaval);
                }
            })
        });

        $(document).on("click", ".del-item", function (e) {
            e.preventDefault();
            var id = $(this).parent().parent().attr("id_input");
            bootbox.confirm("Desea eliminar este item?", function (result) {
                if (result == false) {
                    $('.bootbox').modal('toggle');
                } else {
                    $.ajax({
                        url: "<?php echo $this->url("usuarios", array("controller" => "input", "action" => "delete")) ?>",
                        type: "get",
                        data: {
                            id: id,
                        },
                        success: function (data) {
                            var respuesta = data[0];
                            var div = "danger";
                            if (respuesta.error == false) {
                                div = "success";
                            }

                            $(".bootbox .modal-body").prepend(
                                    '<div class="alert alert-' + div + '">' +
                                    '<button data-dismiss="alert" class="close" type="button">' +
                                    '<i class="icon-remove"></i>' +
                                    '</button>' +
                                    respuesta.mensaje +
                                    '<br>' +
                                    '</div>');

                            if (div == "success") {

                                $("#inputs-collections").find(".item-input").each(function () {
                                    if ($(this).find(".alert-info").attr("id_input") == id) {
                                        $(this).remove();
                                    }
                                });

                                setTimeout(function () {
                                    $('.bootbox').modal('toggle');
                                }, 2000);
                            }
                        }
                    });
                }
            });
        });


        $("#edit-pagina").click(function (e) {
            e.preventDefault();
            var idpagina = $(".wizard-steps").find("li.active").attr("id_page");
            bootbox.dialog({});
            $.ajax({
                url: "formulario_edit/popup-edit",
                data: {idpagina: idpagina},
                success: function (data) {
                    $(".bootbox .modal-body").html(data);
                }
            });
        });

        $("#del-pagina").click(function (e) {
            e.preventDefault();
            var idpagina = $(".wizard-steps").find("li.active").attr("id_page");
            bootbox.confirm("Desea eliminar este item?", function (result) {
                if (result == false) {
                    $('.bootbox').modal('toggle');
                } else {
                    $.ajax({
                        url: "<?php echo $this->url("usuarios", array("controller" => "pagina", "action" => "delete")) ?>",
                        type: "get",
                        data: {
                            idpagina: idpagina,
                        },
                        success: function (data) {
                            var respuesta = data[0];
                            var div = "danger";
                            if (respuesta.error == false) {
                                div = "success";
                            }

                            $(".bootbox .modal-body").prepend(
                                    '<div class="alert alert-' + div + '">' +
                                    '<button data-dismiss="alert" class="close" type="button">' +
                                    '<i class="icon-remove"></i>' +
                                    '</button>' +
                                    respuesta.mensaje +
                                    '<br>' +
                                    '</div>');

                            if (div == "success") {
                                setTimeout(function () {
                                    $('.bootbox').modal('toggle');
                                    window.location.reload();
                                }, 2000);
                            }
                        }
                    });
                }
            });
        });

        $("#add-pagina").click(function (e) {
            e.preventDefault();
            bootbox.dialog({});
            $.ajax({
                url: "formulario_edit/popup-pagina",
                data: "",
                success: function (data) {
                    $(".bootbox .modal-body").html(data);
                }
            });
        });

        $(document).on("click", "#close-modal-pagina", function () {
            var nombre = $("input[name=nombre]").val(),
                    orden = $(".wizard-steps li").length + 1;

            $.ajax({
                url: "<?php echo $this->url("usuarios", array("controller" => "pagina", "action" => "add")) ?>",
                type: "post",
                data: {
                    nombre: nombre,
                    orden: orden
                },
                success: function (data) {
                    var respuesta = data[0];
                    var div = "danger";
                    if (respuesta.error == false) {
                        div = "success";
                    }

                    $(".bootbox .modal-body").prepend(
                            '<div class="alert alert-' + div + '">' +
                            '<button data-dismiss="alert" class="close" type="button">' +
                            '<i class="icon-remove"></i>' +
                            '</button>' +
                            respuesta.mensaje +
                            '<br>' +
                            '</div>');

                    if (div == "success") {
                        setTimeout(function () {
                            $('.bootbox').modal('toggle');
                            window.location.reload();
                        }, 2000);
                    }
                }
            });
        });

        $(document).on("click", "#close-modal-edit-input", function () {

            var nombre = $("input[name=nombre]").val(),
                    idinput = $("#idinput").val(),
                    ayuda = $("input[name=ayuda]").val(),
                    label = $("textarea.mention").val(),
                    tipo = $("ul#myTab li.active a").attr("tipo"),
                    obligatorio = ($(".inputs-text-control-edit input[name=obligatorio]").prop('checked') == true) ? "1" : "0";

            input_data = {};

            if (tipo == "texto") {
                input_data.respuestas_requeridas = $("#numero-respuestas").val();
            }

            $.ajax({
                url: "<?php echo $this->url("usuarios", array("controller" => "input", "action" => "edit")) ?>",
                type: "post",
                data: {
                    idinput: idinput,
                    nombre: nombre,
                    label: label,
                    tipo: tipo,
                    ayuda:ayuda,
                    input_data: input_data,
                    obligatorio:obligatorio
                },
                success: function (data) {
                    var respuesta = data[0];
                    var div = "danger";
                    if (respuesta.error == false) {
                        div = "success";
                    }

                    $(".bootbox .modal-body").prepend(
                            '<div class="alert alert-' + div + '">' +
                            '<button data-dismiss="alert" class="close" type="button">' +
                            '<i class="icon-remove"></i>' +
                            '</button>' +
                            respuesta.mensaje +
                            '<br>' +
                            '</div>');

                    if (div == "success") {
                        setTimeout(function () {
                            $('.bootbox').modal('toggle');
                            window.location.reload();
                        }, 2000);
                    }
                }
            });
        });

        $(document).on("click", "#close-modal-edit-pagina", function () {
            $(".wizard-steps li").each(function (i) {
                var at = $(this).attr("class");
                if (at.indexOf("active") !== -1) {
                    orden = i;
                    return false;
                }
            })

            var nombre = $("input[name=nombre]").val(),
                    idpagina = $("#idpagina").val();

            $.ajax({
                url: "<?php echo $this->url("usuarios", array("controller" => "pagina", "action" => "edit")) ?>",
                type: "post",
                data: {
                    idpagina: idpagina,
                    nombre: nombre,
                    orden: orden
                },
                success: function (data) {
                    var respuesta = data[0];
                    var div = "danger";
                    if (respuesta.error == false) {
                        div = "success";
                    }

                    $(".bootbox .modal-body").prepend(
                            '<div class="alert alert-' + div + '">' +
                            '<button data-dismiss="alert" class="close" type="button">' +
                            '<i class="icon-remove"></i>' +
                            '</button>' +
                            respuesta.mensaje +
                            '<br>' +
                            '</div>');

                    if (div == "success") {
                        setTimeout(function () {
                            $('.bootbox').modal('toggle');
                            window.location.reload();
                        }, 2000);
                    }
                }
            });
        });

        function addControlHtml(id, nombre, label) {
            var s = 
                    '<div class="control-group item-input">' +
                        '<div class="alert alert-info" id_input="' + id + '">' +
                            '<i class="icon-move bigger-130"></i>' +
                            '<button data-dismiss="alert" class="close" type="button">' +
                                '<i class="ace-icon fa fa-times"></i>' +
                            '</button>' +
                            '<strong>' + nombre + '</strong>' + label +
                            '<div class="action-paginas hidden-phone visible-desktop action-buttons">' +
                                '<a href="#" class="green edit-input">' +
                                    '<i class="icon-pencil bigger-130"></i>' +
                                '</a>' +
                                '<a href="#" class="red remove del-item">' +
                                    '<i class="icon-trash bigger-130"></i>' +
                                '</a>' +
                            '</div>' +
                            '<br>' +
                        '</div>' +
                    '</div>';

            $("#step-container .active #inputs-collections").append(s);
        }

        $(document).on("click", "#close-modal", function () {
            var
                    id_pagina = $(".wizard-steps li.active").attr("id_page"),
                    nombre = $("input[name=nombre]").val(),
                    label = $(".mention").val(),
                    obligatorio = ($(".inputs-text-control-add input[name=obligatorio]").prop('checked') == true) ? "1" : "0",
                    tipo = $("#myTab li.active a").attr("tipo"),
                    orden = $("#inputs-collections").find(".item-input").length + 1;

            input_data = {};

            if (tipo == "texto") {
                input_data.respuestas_requeridas = $("#numero-respuestas").val();
            }

            $.ajax({
                url: "<?php echo $this->url("usuarios", array("controller" => "input", "action" => "add")) ?>",
                type: "post",
                data: {
                    id_pagina: id_pagina,
                    nombre: nombre,
                    label: label,
                    obligatorio: obligatorio,
                    tipo: tipo,
                    input_data: input_data,
                    orden: orden
                },
                success: function (data) {
                    var respuesta = data.response;

                    addControlHtml(respuesta.id, nombre, label);

                    var div = "danger";
                    if (respuesta.error == false) {
                        div = "success";
                    }

                    $(".bootbox .modal-body").prepend(
                            '<div class="alert alert-' + div + '">' +
                            '<button data-dismiss="alert" class="close" type="button">' +
                            '<i class="icon-remove"></i>' +
                            '</button>' +
                            respuesta.mensaje +
                            '<br>' +
                            '</div>');

                    if (div == "success") {
                        setTimeout(function () {
                            $('.bootbox').modal('toggle');
                        }, 2000);
                    }
                }
            })
        })

        $(function () {
            $(".wizard-steps").sortable({
                connectWith: ".wizard-steps",
                stop: function ( ) {
                    $(".wizard-steps li").each(function (i) {
                        $(this).find(".step").text(i + 1);
                    })

                    saveOrden();
                }
            }).disableSelection();
        });

        $(function () {
            $(".form-horizontal").sortable({
                connectWith: ".form-horizontal",
                stop: function ( ) {
                    saveOrdenItem();
                }
            }).disableSelection();
        });



    });
    function saveOrdenItem() {
        var items = [];

        $("#step-container .item-input").each(function (i) {
            var unInput = {};
            unInput.id = $(this).find(".alert-info:first").attr("id_input");
            unInput.orden = i + 1;
            items.push(unInput);
        })

        $.ajax({
            url: "<?php echo $this->url("usuarios", array("controller" => "formulario_edit", "action" => "saveordenitems")) ?>",
            type: "post",
            data: {
                items: items
            },
            success: function (data) {

            }
        });
    }

    function saveOrden() {
        var paginas = [];

        $(".wizard-steps li").each(function (i) {
            var unaPagina = {};
            unaPagina.id = $(this).attr("id_page");
            unaPagina.orden = i + 1;
            paginas.push(unaPagina);
        })

        $.ajax({
            url: "<?php echo $this->url("usuarios", array("controller" => "formulario_edit", "action" => "saveordenpaginas")) ?>",
            type: "post",
            data: {
                paginas: paginas
            },
            success: function (data) {

            }
        });
    }
</script>