<div class="">
    <div class="table-header">
        <button data-dismiss="modal" class="close" type="button">×</button>
        Nuevo Control
    </div>
    <div class="inputs-text-control inputs-text-control-edit">
        <input type="text" name="nombre" placeholder="Nombre" value="<?php echo $this->input->getNombre() ?>">
        <input type="text" name="ayuda" placeholder="Ayuda" value="<?php echo $this->input->getAyuda() ?>">
        <textarea name="nombre" placeholder="Etiqueta" class='mention'></textarea>
        <input type="hidden" class="textarea-mention" value="<?php echo $this->input->getLabel() ?>">
        <input type="hidden" id="idinput" value="<?php echo $this->input->getId() ?>">
        <input type="hidden" id="tipoinput" value="<?php echo $this->input->getTipo() ?>">
        <div class="">
            <label class="popup-label">Obligatorio</label>
            <label>
                <input name="obligatorio" class="ace-switch ace-switch-2" type="checkbox" <?php echo ($this->input->getRequired()) ? "checked='checked'" : "" ?> />
                <span class="lbl"></span>
            </label>
        </div>
    </div>
    <div>
        <label>Tipo de control</label>
    </div>
    <div class="tabbable">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active">
                <a data-toggle="tab" href="#home" tipo="texto">
                    Texto
                </a>
            </li>

            <li>
                <a data-toggle="tab" href="#profile" tipo="dropdown">
                    Dropdown
                </a>
            </li>

            <li class="dropdown">
                <a data-toggle="tab" href="#" tipo="imagen">
                    Imagen
                </a>
            </li>
        </ul>

        <div class="tab-content">
            <div id="home" class="tab-pane in active">
                <div class="widget-main">
                    <label>Respuestas requeridas</label>
                    <input type="text" class="input-mini" id="numero-respuestas" />
                    <div class="space-6"></div>
                </div>
            </div>

            <div id="profile" class="tab-pane row">
                <div class="row">
                    <label class="control-label" style="float: left;">Multi</label>
                    <div class="span3">
                        <label>
                            <input type="checkbox" class="ace-switch ace-switch-2" id="esmulti" name="esmulti">
                            <span class="lbl"></span>
                        </label>
                    </div>
                </div>
                <div class="row" style="height: 50px;">
                    <label>Respuestas requeridas</label>
                    <input type="text" class="input-mini" id="numero-respuestas-select" disabled/>
                    <div class="space-6"></div>
                </div>
                <div id="values-select" class="row" style="max-height: 145px; overflow-y: scroll;">
                    <?php if($this->input->getTipo()=="dropdown"):?>
                    <?php
                    $select = $this->input->getControl();
                    $values = $select->getValues();
                    ?>
                    <input type="hidden" id="idselecthidden" value="<?php echo $select->getId() ?>">
                    <?php foreach($values as $value):?>
                    <div class="control-group item-input select-value-input">
                        <div class="alert alert-info">
                            <i class="icon-move bigger-130"></i>
                            <button data-dismiss="alert" class="close" type="button">
                                <i class="ace-icon fa fa-times"></i>
                            </button>
                            <input id_input="<?php echo $value->id_input ?>" id_select="<?php echo $value->getId() ?>" name="input-select-value-<?php echo $value->getId() ?>" id="input-select-value-<?php echo $value->getId() ?>" class="value-option" type="text" value="<?php echo $value->getValue() ?>" disabled="disabled">
                            <div class="action-paginas hidden-phone visible-desktop action-buttons">
                                <a id="" class="red remove del-input-select-value-on-edit" style=""> 
                                    <i class="icon-trash bigger-130"></i>
                                </a>
                                <a class="edit-input-select-value green" id="">
                                    <i class="icon-pencil bigger-130"></i>
                                </a>
                            </div>
                            <br>
                        </div>
                    </div>
                    <?php endforeach;?>
                    <?php endif; ?>
                </div>
                <div class="row">
                    <div class="action-paginas hidden-phone visible-desktop action-buttons" style="float: left; width: 100%;">
                        <input type="text" style="margin-bottom: 2px; width: 84%;" placeholder="Dropdown valor" name="select_value">
                        <a class="red remove" href="/tesisenlinea/public/usuarios/pagina/add/id_pagina" id="add-select-value">
                            <i class="icon-plus-sign bigger-130"></i>
                        </a>
                    </div>
                </div>
            </div>

            <div id="dropdown1" class="tab-pane">
                <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
            </div>

            <div id="dropdown2" class="tab-pane">
                <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin.</p>
            </div>
        </div>
    </div>
    <button id="close-modal-edit-input" class="btn  btn-primary">Save</button>
</div>
<style>
    .row {
        margin-left: 0;
    }
</style>