<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle(); ?>

        <meta name="description" content="overview &amp; stats" />
        
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/ace-skins.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/ace-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/ace.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css') ?>

        <!--[if IE 7]>
          <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
        <![endif]-->

        <!--page specific plugin styles-->

        <!--fonts-->

        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

        <!--[if lte IE 8]>
          <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
        <![endif]-->

        <!--inline styles related to this page-->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        
        <!-- Scripts -->

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/js/ace.min.js')
            ->prependFile($this->basePath() . '/assets/js/ace-elements.min.js')
            ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.resize.min.js')
            ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.pie.min.js')
            ->prependFile($this->basePath() . '/assets/js/flot/jquery.flot.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.sparkline.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.easy-pie-chart.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.slimscroll.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.ui.touch-punch.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery-ui-1.10.3.custom.min.js')
            ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/excanvas.min.js',   'text/javascript', array('conditional' => 'lte IE 8',))
                ->prependFile($this->basePath() . '/assets/js/jquery.min.2.0.3.js')
        ; ?>

    </head>
<div class="page-content">
    <div class="row-fluid">
        <div class="span12">
            <!--PAGE CONTENT BEGINS-->

            <div class="error-container">
                <div class="well">
                    <h1 class="grey lighter smaller">
                        <span class="blue bigger-125">
                            <i class="icon-sitemap"></i>
                            404
                        </span>
                        Page Not Found
                    </h1>

                    <hr>
                    <h3 class="lighter smaller">We looked everywhere but we couldn't find it!</h3>

                    <div>

                        <div class="space"></div>
                        <h4 class="smaller">Try one of the following:</h4>

                        <ul class="unstyled spaced inline bigger-110">
                            <li>
                                <i class="icon-hand-right blue"></i>
                                Re-check the url for typos
                            </li>

                            <li>
                                <i class="icon-hand-right blue"></i>
                                Read the faq
                            </li>

                            <li>
                                <i class="icon-hand-right blue"></i>
                                Tell us about it
                            </li>
                        </ul>
                    </div>

                    <hr>
                    <div class="space"></div>

                    <div class="row-fluid">
                        <div class="center">


                            <a class="btn btn-primary" href="<?php echo $this->url("usuarios", array("controller" => "index", "action" => "index")) ?>">
                                <i class="icon-dashboard"></i>
                                Dashboard
                            </a>
                        </div>
                    </div>
                </div>
            </div><!--PAGE CONTENT ENDS-->
        </div><!--/.span-->
    </div><!--/.row-fluid-->
</div>