<footer>
    <div class="container">
        <div class="row"> 

            <!--======= FOOTER ROWS =========-->
            <div class="col-md-6">
                <ul class="row">

                    <!--======= ABOUT US =========-->
                    <li class="col-sm-6">
                        <h5>Nosotros</h5>
                        <hr>
                        <p>Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. </p>
                        <form class="subscribe-form" id="subscribe_form">
                            <input type="email" name="newsletter" id="scf_email" placeholder="tu.email@adress.com" required="">
                            <button type="submit" id="scf_submit"><i class="fa fa-check"></i> </button>
                        </form>
                    </li>

                    <!--======= USEFUL LINKS =========-->
                    <li class="col-sm-6">
                        <h5>Links<span> mas usados</span></h5>
                        <hr>
                        <ul class="link">
                            <li><a href="#."> Home <i class="fa fa-angle-right"></i></a></li>
                            <li><a href="#."> Nosotros <i class="fa fa-angle-right"></i></a></li>
                            <li><a href="#."> Ayuda <i class="fa fa-angle-right"></i></a></li>
                            <li><a href="#."> Contacto <i class="fa fa-angle-right"></i></a></li>
                        </ul>
                    </li>
                </ul>
            </div>

            <!--======= FOOTER ROWS =========-->
            <div class="col-md-6">
                <ul class="row">

                    <!--======= USEFUL LINKS =========-->
                    <li class="col-sm-6">
                        <h5>Galeria <span>de Fotos</span></h5>
                        <hr>
                        <ul class="flicker">
                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-1.jpg')?>" alt=""></a></li>
                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-2.jpg')?>" alt=""></a></li>
                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-3.jpg')?>" alt=""></a></li>
                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-4.jpg')?>" alt=""></a></li>
                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-5.jpg')?>" alt=""></a></li>
                            <li><a href="#."><img class="img-responsive" <img src="<?php echo $this->basePath('assets/images/g-img-1.jpg')?>" alt=""></a></li>
                        </ul>
                    </li>


                </ul>
            </div>
        </div>
        <div class="scroll-top" style="display: block;">
            <span class="fa fa-angle-up"></span>
        </div> 
    </div>

    <!--======= RIGHTS =========-->
    <div class="rights">
        <div class="container">
            <ul class="row">
                <li class="col-md-8">
                    <p>Todos los derechos reservados © Tu tesis en línea | Designed By Hueco-Creativo</p>
                </li>
                <!--======= SOCIAL ICON =========-->
                <li class="col-md-4">
                    <ul class="social_icons">
                        <li class="facebook"><a href="#."><i class="fa fa-facebook"></i></a></li>
                        <li class="googleplus"><a href="#."><i class="fa fa-google-plus"></i></a></li>
                        <li class="twitter"><a href="#."><i class="fa fa-twitter"></i></a></li>
                        <li class="vimeo"><a href="#."><i class="fa fa-vimeo-square"></i></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</footer>