<?php 
$usuario = new \Usuarios\Model\Entity\Usuario();
if(isset($_SESSION["miSession"]["usuario"])){
    $usuario = $_SESSION["miSession"]["usuario"]; 
}
$alertas = $this->alertas->getAlertasUsuario($usuario->getId());
$mensajes = $this->mensajes->getMensajesUsuario($usuario->getId());
$totalAlertas = count($alertas);
$totalMensajes = count($mensajes);
?>
<nav role="navigation" class="navbar navbar-default navbar-fixed-top bootstrap-admin-navbar-sm">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="collapse navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="#"> <i class="glyphicon glyphicon-envelope"></i></a>
                        </li>
                        <li>
                            <a class="badge-important" href="#"> <i class="glyphicon glyphicon-bell"></i>
                                <?php echo $totalAlertas ?>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a data-hover="dropdown" class="dropdown-toggle" role="button" href="#">  <?php if(isset($usuario)) echo $usuario->getNombre(); ?> <i class="caret"></i> <i class="glyphicon glyphicon-user"></i></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->basePath('usuarios/usuario/profile'); ?>">
                                            Perfil
                                    </a>
                                </li>
                                <li class="divider" role="presentation"></li>
                                <li><a href="<?php echo $this->url("usuarios",array("controller"=>"login","action"=>"logout")) ?>">Salir</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>
<nav role="navigation" class="navbar navbar-default navbar-fixed-top bootstrap-admin-navbar bootstrap-admin-navbar-under-small">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="navbar-header">
                    <button data-target=".main-navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="../index.html" class="navbar-brand"><img src="<?php echo $this->basePath('assets/images/logo.png') ?>"></a>
                </div>
                <div style="background-color: #0076c0 ;" class="collapse navbar-collapse main-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="">
                            <a href="dashboard.html"><i class="glyphicon glyphicon-dashboard"></i> Dashboard</a>
                        </li>
                         <?php if( $this->acl->isAllowed($this->role,"usuarios:formulario","wizard")): ?>
                        <li>
                            <a href="<?php echo $this->url("usuarios",array("controller"=>"formulario","action"=>"wizard")) ?>/"><i class="glyphicon glyphicon-open-file"></i> Tesis Wizard </a>
                        </li>
                        <?php endif; ?>
                        <?php if( $this->acl->isAllowed($this->role,"usuarios:formulario_edit","index")): ?>
                        <li>
                            <a href="<?php echo $this->url("usuarios",array("controller"=>"formulario_edit","action"=>"index")) ?>"><i class="glyphicon glyphicon-open-file"></i> Form </a>
                        </li>
                        <?php endif; ?>
                        <?php if( $this->acl->isAllowed($this->role,"usuarios:usuario","index")): ?>
                           <li class="dropdown">
                                <a data-hover="dropdown" class="dropdown-toggle" href="#"><i class="glyphicon glyphicon-envelope"></i> Usuarios <b class="caret"></b></a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"usuario","action"=>"list")) ?>/">
                                            <i class="glyphicon glyphicon-pencil"></i> Listar</a></li>
                                            <li class="divider" role="presentation"></li>
                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"usuario","action"=>"add")) ?>"><i class="glyphicon glyphicon-cloud-download"></i> Nuevo</a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if( $this->acl->isAllowed($this->role,"usuarios:mensaje","msgs")): ?>
                           <li class="dropdown">
                                <a data-hover="dropdown" class="dropdown-toggle" href="#"><i class="glyphicon glyphicon-envelope"></i> Messages <b class="caret"></b></a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"new")) ?>/"><i class="glyphicon glyphicon-pencil"></i> Redactar</a></li>


                                    <li class="divider" role="presentation"></li>

                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"msgs")) ?>/"><i class="glyphicon glyphicon-cloud-download"></i> Recibidos</a></li>
                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"msgsenviados")) ?>"><i class="glyphicon glyphicon-cloud-upload "></i> Enviados</a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>

                </div><!-- /.navbar-collapse -->
            </div>
        </div>
    </div><!-- /.container -->
</nav>
<script>
    $(document).ready(function(){
        /*$(".dropdown-toggle-mensajes").click(function(){
            var id = "<?php //echo $usuario->getId() ?>";
            $.ajax({
                url: "<?php //echo $this->url("usuarios", array("controller" => "mensaje", "action" => "setvistos")) ?>",
                data:{id:id},
                success:function(data){
                    if(data == "0"){
                        $(".badge-success").text("0");
                    }
                }
            });
        });*/
        
        $(".dropdown-toggle-alertas").click(function(){
            var id = "<?php echo $usuario->getId() ?>";
            $.ajax({
                url: "<?php echo $this->url("usuarios", array("controller" => "alerta", "action" => "setvistos")) ?>",
                data:{id:id},
                success:function(data){
                    if(data == "0"){
                        $(".badge-important").text("0");
                    }
                }
            });
        });
        
    })
</script>