<?php 
$usuario = new \Usuarios\Model\Entity\Usuario();
if(isset($_SESSION["miSession"]["usuario"])){
    $usuario = $_SESSION["miSession"]["usuario"]; 
}
$alertas = $this->alertas->getAlertasUsuario($usuario->getId());
$mensajes = $this->mensajes->getMensajesUsuario($usuario->getId());
$totalAlertas = count($alertas);
$totalMensajes = count($mensajes);
?>
<div class="top-bar">
    <div class="container">
        <ul class="left-bar-side">
            <li> <a href="#."><i class="fa fa-facebook"></i></a> - </li>
            <li> <a href="#."><i class="fa fa-twitter"></i></a> - </li>
            <li> <a href="#."><i class="fa fa-linkedin"></i></a></li>
        </ul>
        <ul class="right-bar-side">
            <li> <a href="#."><i class="fa fa-comment"></i> Chat de Atención </a></li>
            <li> <a href="#."><i class="fa fa-phone"></i> +52 1 (735)1349472 </a></li>
            <li> <a href="#."><i class="fa fa-envelope"></i> soporte@tutesisenlinea.com </a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-hover="dropdown" aria-expanded="false">
                    <i class="fa fa-user"></i>
                    <?php if(isset($usuario)) echo $usuario->getNombre(); ?> 
                </a>
                <ul class="dropdown-menu dropdown-usuario">
                    <li>
                        <a href="<?php echo $this->basePath('usuarios/usuario/profile'); ?>">
                            Perfil
                        </a>
                    </li> 
                    <li class="divider" role="presentation"></li>
                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"login","action"=>"logout")) ?>">Salir</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<div id="undefined-sticky-wrapper" class="sticky-wrapper" style="height: 111px;">
    <header class="sticky">
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="row">
                    <div class="navbar-header col-md-3 col-sm-3">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-res"> <span class="sr-only">Toggle navigation</span> <span class="fa fa-navicon"></span> </button>
                        <!--======= LOGO =========-->
                        <div class="logo"> <a href="index.html"> <img src="<?php echo $this->basePath('assets/images/logo.png') ?>"> </a> </div>
                    </div>

                    <!--======= MENU =========-->
                    <div class="col-md-9 col-sm-9">
                        <div class="collapse navbar-collapse" id="nav-res">
                            <ul class="nav navbar-nav">
                                <li class="">
                            <a href="dashboard.html"> Dashboard</a>
                        </li>
                         <?php if( $this->acl->isAllowed($this->role,"usuarios:formulario","wizard")): ?>
                        <li>
                            <a href="<?php echo $this->url("usuarios",array("controller"=>"formulario","action"=>"wizard")) ?>/"> Desarrollo </a>
                        </li>
                        <?php endif; ?>
                        <?php if( $this->acl->isAllowed($this->role,"usuarios:formulario_edit","index")): ?>
                        <li>
                            <a href="<?php echo $this->url("usuarios",array("controller"=>"formulario_edit","action"=>"index")) ?>"> Form </a>
                        </li>
                        <?php endif; ?>
                        <?php if( $this->acl->isAllowed($this->role,"usuarios:usuario","index")): ?>
                           <li class="dropdown">
                                <a data-hover="dropdown" class="dropdown-toggle" href="#"> Usuarios <b class="caret"></b></a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"usuario","action"=>"list")) ?>/">
                                            <i class="glyphicon glyphicon-pencil"></i> Listar</a></li>
                                            <li class="divider" role="presentation"></li>
                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"usuario","action"=>"add")) ?>"><i class="glyphicon glyphicon-cloud-download"></i> Nuevo</a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if( $this->acl->isAllowed($this->role,"usuarios:mensaje","msgs")): ?>
                           <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-hover="dropdown" aria-expanded="false"> Messages <b class="caret"></b></a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"new")) ?>/"><i class="glyphicon glyphicon-pencil"></i> Redactar</a></li>


                                    <li class="divider" role="presentation"></li>

                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"msgs")) ?>/"><i class="glyphicon glyphicon-cloud-download"></i> Recibidos</a></li>
                                    <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"msgsenviados")) ?>"><i class="glyphicon glyphicon-cloud-upload "></i> Enviados</a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                                <!--<li><a href="dashboard.html">Dashboard</a></li>
                                <li><a href="wizard.html">Tesis Wizard</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-hover="dropdown" aria-expanded="false"> Messages <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="email-write.html"> Redactar</a></li> 
                                        <li role="presentation" class="divider"></li>
                                        <li><a href="email-inbox.html">Recibidos</a></li>
                                        <li><a href="email-outbox.html">Enviados</a></li>
                                    </ul>
                                </li>-->
                                <li><a href="<?php echo $this->url("usuarios",array("controller"=>"mensaje","action"=>"msgs")) ?>/"> <i class="fa fa-envelope">  <?php echo $totalMensajes ?></i></a></li>
                                <li><a href=""> <i class="fa fa-bell"> <?php echo $totalAlertas ?></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>
</div>
<!--Viejo-->
<script>
    $(document).ready(function(){
        $(".dropdown-toggle-alertas").click(function(){
            var id = "<?php echo $usuario->getId() ?>";
            $.ajax({
                url: "<?php echo $this->url("usuarios", array("controller" => "alerta", "action" => "setvistos")) ?>",
                data:{id:id},
                success:function(data){
                    if(data == "0"){
                        $(".badge-important").text("0");
                    }
                }
            });
        });
        
    })
</script>