<!-- left, vertical navbar & content -->
            <div class="row">
                <!-- left, vertical navbar -->
                

                <!-- content -->
                <div class="col-md-12">

 
                <!--======= FEATURE =========-->
                <section id="feature">
                    <div class="container"> 

                        <div class="row">
                            <div class="col-md-6"> 
                                <!--======= FEATURE =========-->
                                <ul class="row">

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-bar-chart"></i> </div>
                                            <h3>1782</h3>
                                            <h5>Agentes Evaluados</h5>
                                        </div>
                                    </li>

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-area-chart"></i> </div>
                                            <h3>1782</h3>
                                            <h5>Promedio Agentes</h5>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                            <div class="col-md-6"> 
                                <!--======= FEATURE =========-->
                                <ul class="row">

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-pie-chart"></i> </div>
                                            <h3>1782</h3>
                                            <h5>Topico mas puntuado</h5>
                                        </div>
                                    </li>

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-pie-chart"></i> </div>
                                            <h3>1782</h3>
                                            <h5>Topico menos puntuado</h5>
                                        </div>
                                    </li>
                                </ul>
                            </div>


                            <div class="col-md-6"> 
                                <!--======= FEATURE =========-->
                                <ul class="row">

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                    </li>

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-line-chart"></i> </div>
                                            <h3>1782</h3>
                                            <h5>Categoria mas puntuado</h5>
                                        </div>
                                    </li>
                                </ul>
                            </div>


                            <div class="col-md-6"> 
                                <!--======= FEATURE =========-->
                                <ul class="row">

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6">
                                        <div class="inner">
                                            <div class="circle"><span> </span></div>
                                            <div class="icon"> <i class="fa fa-line-chart"></i> </div>
                                            <h3>1782</h3>
                                            <h5>Categoria menos puntuado</h5>
                                        </div>
                                    </li>

                                    <!--======= SERVICES 1 =========-->
                                    <li class="col-sm-6"> 
                                    </li>
                                </ul>
                            </div>



                        </div>
                    </div>
                </section>


            <div class="container">

                        <div class="col-md-6">
                            <div class="panel panel-default">
                                
                                <div class="title-bar-dashboard">Evaluations</div>
                                
                                <div class= "evaluations-rate">
                                    
                                        <table class="pull-right">
                                            <tr><td style="background-color:green;width:40px;">&nbsp;</td><td>&nbsp;Aproved</td></tr>
                                            <tr><td style="background-color:red;width:40px;">&nbsp;</td><td>&nbsp;Not Aproved</td></tr>
                                            <tr><td style="background-color:yellow;width:40px;">&nbsp;</td><td>&nbsp;Need Work</td></tr>
                                        </table>
                                </div>
                            </div>
                        </div>


                        <div class="col-md-6">
                            <div class="panel panel-default">
                                
                                <div class="title-bar-dashboard">Top Agents</div>
                                
                                <div class= "top-rate">
                                    
                                        <table class="pull-right">
                                
                                <div class="bootstrap-admin-panel-content">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                
                                                <th>Name</th>
                                                <th>Last Name</th>
                                                <th>Points</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                
                                                <td>Name 1</td>
                                                <td>Last Name 2</td>
                                                <td>50</td>
                                            </tr>
                                            <tr>
                                                
                                                <td>Name 2</td>
                                                <td>Last Name 2</td>
                                                <td>38</td>
                                            </tr>
                                            <tr>
                                               
                                                <td>Name 3</td>
                                                <td>Last Name 3</td>
                                                <td>22</td>
                                            </tr>
                                            <tr> 
                                                <td>Name 4</td>
                                                <td>Last Name 4</td>
                                                <td>17</td>
                                            </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    


                        
                        <div class="col-lg-12">

                            <div class="title-bar-dashboard">Evaluations Statics</div>
                            <div class="bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in">
               
                            </div>

                        </div>


     
                </div>
            </div>
        </div>