<style>
    .infobox{
        width:304px;
    }
    .row-fluid .span7 {
        width: 97.265%;
    }
    .row-fluid .span5 {
        width: 44.771%;
    }
    .widget-box.transparent {
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -webkit-border-radius: 1em;
        border-color: #CCCCCC;
        border-image: none;
        border-style: solid;
        border-width: 1px 1px 2px;
        box-shadow: none;
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
    }
    .infobox > .infobox-data > .infobox-data-number {
        font-size: 16px;
    }

</style>

<div class="row-fluid">
    <div class="span12">
        <!--PAGE CONTENT BEGINS-->

        <div class="space-6"></div>

        <div class="row-fluid">
            <div class="span7 infobox-container">
                <div class="infobox infobox-green  ">
                    <div class="infobox-icon">
                        <i class="icon-user"></i>
                    </div>

                    <div class="infobox-data">
                        <span id="agentes-evaluados" class="infobox-data-number"></span>
                        <div class="infobox-content">Articulos Publicados</div>
                    </div>
                </div>

                <div class="infobox infobox-blue  ">
                    <div class="infobox-icon">
                        <i class="icon-bar-chart"></i>
                    </div>

                    <div class="infobox-data">
                        <span class="infobox-data-number">12</span>
                        <div class="infobox-content">Publicaciones finalizadas</div>
                    </div>


                </div>

                <div class="infobox infobox-pink  ">
                    <div class="infobox-icon">
                        <i class="icon-bullhorn"></i>
                    </div>

                    <div class="infobox-data">
                        
                        <span class="infobox-data-number">80%</span>
                        <div class="infobox-content">Mensajes respondidos</div>
                    </div>
                    <div class="stat stat-success" style="margin-top: 25px;">0Pts</div>
                </div>

                <div class="infobox infobox-red  ">
                    <div class="infobox-icon">
                        <i class="icon-bullhorn"></i>
                    </div>

                    <div class="infobox-data">
                        
                        <span class="infobox-data-number">$99999</span>
                        <div class="infobox-content">Total Ventas</div>
                    </div>

                    <div class="stat stat-important" style="margin-top: 25px;">0Pts</div>
                </div>

                <div class="infobox infobox-orange2  ">
                    <div class="infobox-icon">
                        <i class="icon-sitemap"></i>
                    </div>

                    <div class="infobox-data">
                        <span class="infobox-data-number"></span>
                        <div class="infobox-content">Total Visitas</div>
                    </div>
                    <div class="stat stat-success" style="margin-top: 25px;">9999</div>
                </div>

                <div class="infobox infobox-blue2  ">
                    <div class="infobox-icon">
                        <i class="icon-sitemap"></i>
                    </div>
                    <div class="infobox-data">
                        <span class="infobox-data-number"></span>
                        <div class="infobox-content">Total mensajes</div>
                    </div>
                    <div class="stat stat-important" style="margin-top: 25px;">0Pts</div>
                </div>

                <div class="space-6"></div>


            </div>
            <div class="vspace"></div>

            <div class="span5">
                <div class="widget-box">
                    <div style="min-height: 38px;" class="widget-header widget-header-flat widget-header-small">
                        <h5>
                            <i class="icon-signal"></i>
                            Ventas
                        </h5>

                        <div class="widget-toolbar no-border">
                            <!--<button data-toggle="dropdown" class="btn btn-minier btn-primary dropdown-toggle">
                                This Week
                                <i class="icon-angle-down icon-on-right"></i>
                            </button>
                            
                            <ul class="dropdown-menu dropdown-info pull-right dropdown-caret">
                                <li class="active">
                                    <a href="#">This Week</a>
                                </li>

                                <li>
                                    <a href="#">Last Week</a>
                                </li>

                                <li>
                                    <a href="#">This Month</a>
                                </li>

                                <li>
                                    <a href="#">Last Month</a>
                                </li>
                            </ul>-->
                        </div>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main">
                            <div id="piechart-placeholder" style="width: 90%; min-height: 221px; padding: 0px; position: relative;">
                                <canvas class="flot-base" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 350px; height: 150px;" width="350" height="150"></canvas>
                                <canvas class="flot-overlay" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 350px; height: 150px;" width="350" height="150"></canvas>
                                <div class="legend">
                                    <div style="position: absolute; width: 95px; height: 110px; top: 15px; right: -30px; background-color: rgb(255, 255, 255); opacity: 0.85;"> </div>
                                    <table style="position:absolute;top:15px;right:-30px;;font-size:smaller;color:#545454">
                                        <tbody>
                                            <tr>
                                                <td class="legendColorBox">
                                                    <div style="border:1px solid null;padding:1px">
                                                        <div style="width:4px;height:0;border:5px solid #68BC31;overflow:hidden"></div>

                                                    </div>
                                                </td>
                                                <td class="legendLabel">Vendidos</td>
                                            </tr>
                                            <tr>
                                                <td class="legendColorBox">
                                                    <div style="border:1px solid null;padding:1px">
                                                        <div style="width:4px;height:0;border:5px solid #DA5430;overflow:hidden"></div>
                                                    </div>
                                                </td>
                                                <td class="legendLabel">Pausados</td>
                                            </tr>
                                            <tr>
                                                <td class="legendColorBox">
                                                    <div style="border:1px solid null;padding:1px">
                                                        <div style="width:4px;height:0;border:5px solid #FEE074;overflow:hidden"></div>
                                                    </div>
                                                </td>
                                                <td class="legendLabel">Finalizados</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div><!--/widget-main-->
                    </div><!--/widget-body-->
                </div><!--/widget-box-->

            </div><!--/span-->

            <div class="span5">
                <div class="widget-box transparent">
                    <div class="widget-header widget-header-flat">
                        <h4 class="lighter">
                            <i class="icon-star orange"></i>
                            Top Ventas
                        </h4>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main no-padding">
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            <i class="icon-caret-right blue"></i>
                                            Name
                                        </th>

                                        <th>
                                            <i class="icon-caret-right blue"></i>
                                            Last Name
                                        </th>

                                        <th class="hidden-phone">
                                            <i class="icon-caret-right blue"></i>
                                            Points
                                        </th>
                                    </tr>
                                </thead>

                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div><!--/widget-main-->
                    </div><!--/widget-body-->
                </div><!--/widget-box-->
            </div>

        </div><!--/row-->





        <!--PAGE CONTENT ENDS-->
    </div><!--/.span-->
</div><!--/.row-fluid-->
<script type="text/javascript">
    $(function() {
        $('.easy-pie-chart.percentage').each(function() {
            var $box = $(this).closest('.infobox');
            var barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');
            var trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';
            var size = parseInt($(this).data('size')) || 50;
            $(this).easyPieChart({
                barColor: barColor,
                trackColor: trackColor,
                scaleColor: false,
                lineCap: 'butt',
                lineWidth: parseInt(size / 10),
                animate: /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,
                size: size
            });
        })

        $('.sparkline').each(function() {
            var $box = $(this).closest('.infobox');
            var barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';
            $(this).sparkline('html', {tagValuesAttribute: 'data-values', type: 'bar', barColor: barColor, chartRangeMin: $(this).data('min') || 0});
        });


        var evaluationsCake = JSON.parse('');

        var AgentesEvaluados = JSON.parse('');

        $("#agentes-evaluados").text(AgentesEvaluados.evaluados + "/" + AgentesEvaluados.total);

        var placeholder = $('#piechart-placeholder').css({'width': '90%', 'min-height': '221px'});
        var data = [
            {label: "Approved", data: evaluationsCake.approbed, color: "#68BC31"},
            {label: "Not Approved", data: evaluationsCake.notApprobed, color: "#DA5430"},
            {label: "Need Work", data: evaluationsCake.needWork, color: "#FEE074"}
        ]
        function drawPieChart(placeholder, data, position) {
            $.plot(placeholder, data, {
                series: {
                    pie: {
                        show: true,
                        tilt: 0.8,
                        highlight: {
                            opacity: 0.25
                        },
                        stroke: {
                            color: '#fff',
                            width: 2
                        },
                        startAngle: 2
                    }
                },
                legend: {
                    show: true,
                    position: position || "ne",
                    labelBoxBorderColor: null,
                    margin: [-30, 15]
                }
                ,
                grid: {
                    hoverable: true,
                    clickable: true
                }
            })
        }
        drawPieChart(placeholder, data);

        /**
         we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically
         so that's not needed actually.
         */
        placeholder.data('chart', data);
        placeholder.data('draw', drawPieChart);



        var $tooltip = $("<div class='tooltip top in hide'><div class='tooltip-inner'></div></div>").appendTo('body');
        var previousPoint = null;

        placeholder.on('plothover', function(event, pos, item) {
            if (item) {
                if (previousPoint != item.seriesIndex) {
                    previousPoint = item.seriesIndex;
                    var tip = item.series['label'] + " : " + Math.round(item.series['percent']) + '%';
                    $tooltip.show().children(0).text(tip);
                }
                $tooltip.css({top: pos.pageY + 10, left: pos.pageX + 10});
            } else {
                $tooltip.hide();
                previousPoint = null;
            }

        });

        var meses = JSON.parse('');
        var evaluaciones = JSON.parse('');

        var eva = [];

        for (var x in evaluaciones) {
            for (var i in meses) {
                if (evaluaciones[x].mes == meses[i].mes && evaluaciones[x].anio == meses[i].anio) {
                    mes = meses[i].mes - 1;
                    mes = getMesNombre(mes);
                    anio = meses[i].anio + "";
                    anio = anio.substring(2, anio.lenght);
                    eva.push([mes + "/" + anio, evaluaciones[x].total]);
                    console.log(mes + "/" + anio + " " + evaluaciones[x].total);
                }
            }
        }

        var evaluations_charts = $('#evaluations-charts').css({'width': '100%', 'height': '500px'});
        plot = $.plot("#evaluations-charts", [
            {label: "Evaluaciones", data: eva, color: 'blue'},
            /*{label: "Puntaje Promedio", data: puntProm},
             {label: "Aprobacion", data: aprob},
             {label: "Reprobacion", data: reprob},
             {label: "Necesita Practicar", data: necPrac}*/
        ], {
            hoverable: true,
            shadowSize: 0,
            series: {
                lines: {show: true},
                points: {show: true}
            },
            xaxis: {
                mode: "categories"
            },
            yaxis: {
                show: false
            },
            grid: {hoverable: true, clickable: true},
        });
        var legends = $("#evaluations-charts .legendLabel");
        var updateLegendTimeout = null;
        var latestPosition = null;

        function updateLegend() {
            updateLegendTimeout = null;

            var pos = latestPosition;

            var axes = plot.getAxes();
            if (pos.x < axes.xaxis.min || pos.x > axes.xaxis.max || pos.y < axes.yaxis.min || pos.y > axes.yaxis.max)
                return;

            var i, j, dataset = plot.getData();
            for (i = 0; i < dataset.length; ++i) {
                var series = dataset[i];

                // find the nearest points, x-wise
                for (j = 0; j < series.data.length; ++j)
                    if (series.data[j][0] > pos.x)
                        break;

                // now interpolate
                var y, p1 = series.data[j - 1],
                        p2 = series.data[j];
                if (p1 == null)
                    y = p2[1];
                else if (p2 == null)
                    y = p1[1];
                else
                    y = p1[1] + (p2[1] - p1[1]) * (pos.x - p1[0]) / (p2[0] - p1[0]);

                legends.eq(i).text(series.label.replace(/=.*/, "= " + y.toFixed(2) + " °C"));
            }
        }

        $("#evaluations-charts").bind("plothover", function(event, pos, item) {
            latestPosition = pos;
            if (!updateLegendTimeout)
                updateLegendTimeout = setTimeout(updateLegend, 50);
        });


        $('#recent-box [data-rel="tooltip"]').tooltip({placement: tooltip_placement});
        function tooltip_placement(context, source) {
            var $source = $(source);
            var $parent = $source.closest('.tab-content')
            var off1 = $parent.offset();
            var w1 = $parent.width();

            var off2 = $source.offset();
            var w2 = $source.width();

            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2))
                return 'right';
            return 'left';
        }


        $('.dialogs,.comments').slimScroll({
            height: '300px'
        });


        //Android's default browser somehow is confused when tapping on label which will lead to dragging the task
        //so disable dragging when clicking on label
        var agent = navigator.userAgent.toLowerCase();
        if ("ontouchstart" in document && /applewebkit/.test(agent) && /android/.test(agent))
            $('#tasks').on('touchstart', function(e) {
                var li = $(e.target).closest('#tasks li');
                if (li.length == 0)
                    return;
                var label = li.find('label.inline').get(0);
                if (label == e.target || $.contains(label, e.target))
                    e.stopImmediatePropagation();
            });

        $('#tasks').sortable({
            opacity: 0.8,
            revert: true,
            forceHelperSize: true,
            placeholder: 'draggable-placeholder',
            forcePlaceholderSize: true,
            tolerance: 'pointer',
            stop: function(event, ui) {//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved
                $(ui.item).css('z-index', 'auto');
            }
        }
        );
        $('#tasks').disableSelection();
        $('#tasks input:checkbox').removeAttr('checked').on('click', function() {
            if (this.checked)
                $(this).closest('li').addClass('selected');
            else
                $(this).closest('li').removeClass('selected');
        });


    })
</script>