<script src="<?php echo $this->basePath() ?>/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/markdown/markdown.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/markdown/bootstrap-markdown.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/jquery.hotkeys.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/bootstrap-wysiwyg.min.js"></script>

<?php if($this->alerta):?>
    <!--Mensaje-->
    <input readonly="readonly" type="text" value="<?php echo $this->alerta->getAsunto(); ?>">
    <div class="wysiwyg-editor" id="editor"></div>
    
    <!--Respuesta-->
    <div class="wysiwyg-editor" id="editor2"></div>
    <hr>
    <div class="form-actions">
        <button style="float: right;" name="send-evaluacion" type="button" class="btn btn-success btn-small btn-next" value="">
            <i class="icon-envelope-alt"></i>
            Send
        </button>        
    </div>
<script>
    $(document).ready(function(){
       $("#editor").html('<?php echo $this->alerta->getMensaje() ?>'); 
       
       $("#editor2").ace_wysiwyg({toolbar:[
                'font',
                null,
                'fontSize',
                null,
                {name:'bold', className:'btn-info'},
                {name:'italic', className:'btn-info'},
                {name:'strikethrough', className:'btn-info'},
                {name:'underline', className:'btn-info'},
                null,
                null,
                null,
                {name:'justifyleft', className:'btn-primary'},
                {name:'justifycenter', className:'btn-primary'},
                {name:'justifyright', className:'btn-primary'},
                {name:'justifyfull', className:'btn-inverse'},
                null,
                null,
                null,
                null,
                null,
                null,
                'foreColor',
                null,
                null,
                null,
            ]
	}).prev().addClass('wysiwyg-style2');
    });
</script>
<?php endif; ?>
