<?php
$form = $this->form;
$form->prepare();
?>

<?php $form->setAttribute('action', $this->url('usuarios', array('controller' => 'usuario', 'action' => 'add'))); ?>
<?php
$form->setAttribute('method', 'post')
        ->setAttribute('id', 'form-add-user')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('enctype', 'multipart/form-data');
?>

<div class="page-header position-relative">
    <h1>
        New User
    </h1>
</div><!--/.page-header-->

<div class="row-fluid">
    <div class="span12">
        <!--PAGE CONTENT BEGINS-->
        <?php
        $formValid = true;

        foreach ($form as $element) {
            $messages = $element->getMessages();

            if (!empty($messages)) {
                $formValid = true;
            }
        }
        ?>
        
        <?php if($this->save):?>
            <div class="alert alert-block alert-success">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="icon-remove"></i>
                </button>
                <i class="icon-ok green"></i>
                User Save
            </div>
            <script>
                $(document).ready(function(){
                    $("input[name=email-user],input[name=first-name-user],input[name=last-name-user],input[name=pass-user],input[name=repass-user]").val("");
                    setTimeout(function(){
                        $(".chzn-choices").find(".search-choice-close").each(function(){
                            $(this).click();
                        })
                    },10)
                    $("select[name=level-user]").val("").change()
                })
            </script>
        <?php endif; ?>
            
        <?php if(isset($this->error)):?>
            <div class="alert alert-block alert-error">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="icon-remove"></i>
                </button>
                <i class="icon-ok green"></i>
                <?php echo $this->error["mensaje"] ?>
            </div>
        <?php endif; ?>
        
    <?php echo $this->form()->openTag($form); ?>
        <?php $mensaje = $this->formElementErrors($form->get('email-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-1" class="control-label">E-Mail</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('email-user')); ?>
                <span class="help-inline"><?php echo $mensaje ?></span>
            </div>
        </div>

        <?php $mensaje = $this->formElementErrors($form->get('first-name-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-1" class="control-label">First Name</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('first-name-user')); ?>
                <span class="help-inline"><?php echo $mensaje ?></span>
            </div>
        </div>

        <?php $mensaje = $this->formElementErrors($form->get('last-name-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-1" class="control-label">Last Name</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('last-name-user')); ?>
                <span class="help-inline"><?php echo $mensaje ?></span>
            </div>
        </div>

        <?php $mensaje = $this->formElementErrors($form->get('pass-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-2" class="control-label">Password</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('pass-user')); ?>
                <span class="help-inline"><?php echo $mensaje ?></span>
            </div>
        </div>

        <?php $mensaje = $this->formElementErrors($form->get('repass-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-2" class="control-label">Retype Password</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('repass-user')); ?>
                <span class="help-inline"><?php echo $mensaje ?></span>
            </div>
        </div>

        <?php $mensaje = $this->formElementErrors($form->get('level-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-2" class="control-label">User type</label>
            <div class="controls">
            <?php echo $this->formSelect($form->get('level-user')); ?>
                <span class="help-inline"><?php echo $mensaje ?></span>
            </div>
        </div>
            
<?php $mensaje = $this->formElementErrors($form->get('avatar-user')); ?>
        <div class="control-group <?php if (!empty($mensaje)): ?>error<?php endif; ?>">
            <label for="form-field-1" class="control-label">Avatar</label>
            <div class="controls">
                <div class="widget-main">
                    <!--<input multiple="" type="file" id="id-input-file-3" />-->
<?php echo $this->formFile($form->get('avatar-user')); ?>
                    <span class="help-inline"><?php echo $mensaje ?></span>
                </div>
            </div>
        </div>

        <div class="form-actions">

            <?php echo $this->formButton()->openTag($form->get('send-user')) . '<i class="icon-ok bigger-110"></i>Submit' . $this->formButton()->closeTag(); ?>

<?php echo $this->formButton()->openTag($form->get('reset-user')) . '<i class="icon-undo bigger-110"></i>Reset' . $this->formButton()->closeTag(); ?>

            &nbsp; &nbsp; &nbsp;
        </div>

<?php echo $this->form()->closeTag() ?>

    </div>
</div><!--PAGE CONTENT ENDS-->
</div><!--/.span-->
<script type="text/javascript">
    $(function() {
        $('#id-disable-check').on('click', function() {
            var inp = $('#form-input-readonly').get(0);
            if (inp.hasAttribute('disabled')) {
                inp.setAttribute('readonly', 'true');
                inp.removeAttribute('disabled');
                inp.value = "This text field is readonly!";
            }
            else {
                inp.setAttribute('disabled', 'disabled');
                inp.removeAttribute('readonly');
                inp.value = "This text field is disabled!";
            }
        });


        $(".chzn-select").chosen();

        $('[data-rel=tooltip]').tooltip({container: 'body'});
        $('[data-rel=popover]').popover({container: 'body'});

        $('textarea[class*=autosize]').autosize({append: "\n"});
        $('textarea[class*=limited]').each(function() {
            var limit = parseInt($(this).attr('data-maxlength')) || 100;
            $(this).inputlimiter({
                "limit": limit,
                remText: '%n character%s remaining...',
                limitText: 'max allowed : %n.'
            });
        });

        $.mask.definitions['~'] = '[+-]';
        $('.input-mask-date').mask('99/99/9999');
        $('.input-mask-phone').mask('(999) 999-9999');
        $('.input-mask-eyescript').mask('~9.99 ~9.99 999');
        $(".input-mask-product").mask("a*-999-a999", {placeholder: " ", completed: function() {
                alert("You typed the following: " + this.val());
            }});



        $("#input-size-slider").css('width', '200px').slider({
            value: 1,
            range: "min",
            min: 1,
            max: 6,
            step: 1,
            slide: function(event, ui) {
                var sizing = ['', 'input-mini', 'input-small', 'input-medium', 'input-large', 'input-xlarge', 'input-xxlarge'];
                var val = parseInt(ui.value);
                $('#form-field-4').attr('class', sizing[val]).val('.' + sizing[val]);
            }
        });

        $("#input-span-slider").slider({
            value: 1,
            range: "min",
            min: 1,
            max: 11,
            step: 1,
            slide: function(event, ui) {
                var val = parseInt(ui.value);
                $('#form-field-5').attr('class', 'span' + val).val('.span' + val).next().attr('class', 'span' + (12 - val)).val('.span' + (12 - val));
            }
        });


        $("#slider-range").css('height', '200px').slider({
            orientation: "vertical",
            range: true,
            min: 0,
            max: 100,
            values: [17, 67],
            slide: function(event, ui) {
                var val = ui.values[$(ui.handle).index() - 1] + "";

                if (!ui.handle.firstChild) {
                    $(ui.handle).append("<div class='tooltip right in' style='display:none;left:15px;top:-8px;'><div class='tooltip-arrow'></div><div class='tooltip-inner'></div></div>");
                }
                $(ui.handle.firstChild).show().children().eq(1).text(val);
            }
        }).find('a').on('blur', function() {
            $(this.firstChild).hide();
        });

        $("#slider-range-max").slider({
            range: "max",
            min: 1,
            max: 10,
            value: 2
        });

        $("#eq > span").css({width: '90%', 'float': 'left', margin: '15px'}).each(function() {
            // read initial values from markup and remove that
            var value = parseInt($(this).text(), 10);
            $(this).empty().slider({
                value: value,
                range: "min",
                animate: true

            });
        });


        $('#id-input-file-1 , #id-input-file-2').ace_file_input({
            no_file: 'No File ...',
            btn_choose: 'Choose',
            btn_change: 'Change',
            droppable: false,
            onchange: null,
            thumbnail: false //| true | large
                    //whitelist:'gif|png|jpg|jpeg'
                    //blacklist:'exe|php'
                    //onchange:''
                    //
        });

        $('#id-input-file-3').ace_file_input({
            style: 'well',
            btn_choose: 'Drop files here or click to choose',
            btn_change: null,
            no_icon: 'icon-cloud-upload',
            droppable: true,
            thumbnail: 'small'
                    //,icon_remove:null//set null, to hide remove/reset button
                    /**,before_change:function(files, dropped) {
                     //Check an example below
                     //or examples/file-upload.html
                     return true;
                     }*/
                    /**,before_remove : function() {
                     return true;
                     }*/
                    ,
            preview_error: function(filename, error_code) {
                //name of the file that failed
                //error_code values
                //1 = 'FILE_LOAD_FAILED',
                //2 = 'IMAGE_LOAD_FAILED',
                //3 = 'THUMBNAIL_FAILED'
                //alert(error_code);
            }

        }).on('change', function() {
            //console.log($(this).data('ace_input_files'));
            //console.log($(this).data('ace_input_method'));
        });


        //dynamically change allowed formats by changing before_change callback function


        (function() {
            var before_change
            var btn_choose
            var no_icon
            //if (this.checked) {
            btn_choose = "Drop images here or click to choose";
            no_icon = "icon-picture";
            before_change = function(files, dropped) {
                var allowed_files = [];
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    if (typeof file === "string") {
                        //IE8 and browsers that don't support File Object
                        if (!(/\.(jpe?g|png|gif|bmp)$/i).test(file))
                            return false;
                    }
                    else {
                        var type = $.trim(file.type);
                        if ((type.length > 0 && !(/^image\/(jpe?g|png|gif|bmp)$/i).test(type))
                                || (type.length == 0 && !(/\.(jpe?g|png|gif|bmp)$/i).test(file.name))//for android's default browser which gives an empty string for file.type
                                )
                            continue;//not an image so don't keep this file
                    }

                    allowed_files.push(file);
                }
                if (allowed_files.length == 0)
                    return false;

                return allowed_files;
            }

            var file_input = $('#id-input-file-3');
            file_input.ace_file_input('update_settings', {'before_change': before_change, 'btn_choose': btn_choose, 'no_icon': no_icon})
            file_input.ace_file_input('reset_input');
        })();




        $('#spinner1').ace_spinner({value: 0, min: 0, max: 200, step: 10, btn_up_class: 'btn-info', btn_down_class: 'btn-info'})
                .on('change', function() {
            //alert(this.value)
        });
        $('#spinner2').ace_spinner({value: 0, min: 0, max: 10000, step: 100, icon_up: 'icon-caret-up', icon_down: 'icon-caret-down'});
        $('#spinner3').ace_spinner({value: 0, min: -100, max: 100, step: 10, icon_up: 'icon-plus', icon_down: 'icon-minus', btn_up_class: 'btn-success', btn_down_class: 'btn-danger'});



        $('.date-picker').datepicker().next().on(ace.click_event, function() {
            $(this).prev().focus();
        });
        $('#id-date-range-picker-1').daterangepicker().prev().on(ace.click_event, function() {
            $(this).next().focus();
        });

        $('#timepicker1').timepicker({
            minuteStep: 1,
            showSeconds: true,
            showMeridian: false
        })

        $('#colorpicker1').colorpicker();
        $('#simple-colorpicker-1').ace_colorpicker();


        $(".knob").knob();


        //we could just set the data-provide="tag" of the element inside HTML, but IE8 fails!
        var tag_input = $('#form-field-tags');
        if (!(/msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase())))
            tag_input.tag({placeholder: tag_input.attr('placeholder')});
        else {
            //display a textarea for old IE, because it doesn't support this plugin or another one I tried!
            tag_input.after('<textarea id="' + tag_input.attr('id') + '" name="' + tag_input.attr('name') + '" rows="3">' + tag_input.val() + '</textarea>').remove();
            //$('#form-field-tags').autosize({append: "\n"});
        }


        /////////
        $('#modal-form input[type=file]').ace_file_input({
            style: 'well',
            btn_choose: 'Drop files here or click to choose',
            btn_change: null,
            no_icon: 'icon-cloud-upload',
            droppable: true,
            thumbnail: 'large'
        })

        //chosen plugin inside a modal will have a zero width because the select element is originally hidden
        //and its width cannot be determined.
        //so we set the width after modal is show
        $('#modal-form').on('show', function() {
            $(this).find('.chzn-container').each(function() {
                $(this).find('a:first-child').css('width', '200px');
                $(this).find('.chzn-drop').css('width', '210px');
                $(this).find('.chzn-search input').css('width', '200px');
            });
        })
        /**
         //or you can activate the chosen plugin after modal is shown
         //this way select element has a width now and chosen works as expected
         $('#modal-form').on('shown', function () {
         $(this).find('.modal-chosen').chosen();
         })
         */

        /*Seteo los botones que desde Zend se complica aplicarle el estilo*/

        $("#submit-user").attr("Value", "Submit")
                .css("padding", "7px 14px 10px 26px").append("<i class='icon-ok bigger-110'></i>")

    });

    $(document).ready(function() {
        //Globals
        var email,
                emailValido = "<?php echo $formValid; ?>";

        (function() {
            //Validar Email con ajax
            $("input[name=email-user]").focusout(function() {
                
                var inputEmail = $(this),
                        pEMail = inputEmail.val();
                
                if (email != pEMail) {
                    
                    emailValido = true;

                    if (pEMail == "") {
                        inputEmail.parent().parent().addClass("error");
                        inputEmail.next().text("Ingrese un email");
                        emailValido = false;
                        return;
                    }

                    if (!emailNoExiste(pEMail)) {
                        inputEmail.parent().parent().addClass("error");
                        inputEmail.next().text("El email no es valido");
                        emailValido = false;
                        return;
                    }


                    var loading = "<?php echo $this->basePath('assets/img/loading.gif') ?>";
                    inputEmail.parent().append("<img id='loading-gif' src='" + loading + "'>");
                    $.get("<?php echo $this->url("usuarios", array("controller" => "usuario", "action" => "validarEmail")) ?>"
                        ,{email: pEMail}
                        , function(data) {
                        if (data == "0") {
                            emailValido = false;
                            inputEmail.parent().parent().removeClass("success");
                            inputEmail.parent().parent().addClass("error");
                            inputEmail.next().text("El email ya esta registrado");
                        }
                        if (data == "1") {
                            inputEmail.parent().parent().removeClass("error");
                            inputEmail.parent().parent().addClass("success");
                            inputEmail.next().text("");
                            emailValido = true;
                        }
                        $(document).find("#loading-gif").remove();
                        email = pEMail;
                    });
                }

            })
            $("input[name=email-user],input[name=first-name-user],input[name=last-name-user],input[name=pass-user],input[name=repass-user]")
                .keyup(function() {
                    $(this).parent().parent().removeClass("error");
                    $(this).next().text("");
            });
            //Validar Password
            $("#pass-user").focusout(function(){
                
            })
        })();
        
        

        //Submit
        $("*[name=send-user]").click(function() {
            if (emailValido) {
                $("#form-add-user").submit();
            }
        });
        $(".icon-question-sign").click(function(){
            $(".help-callcenter").toggle();
        })
        
        $(".icon-question-sign").blur(function(){
            $(".help-callcenter").hide();
        })
    });
</script>
<style>
    label, .lbl {
        display: table-cell;
        vertical-align: middle;
    }
    .control-group {
    }
    .user-submit{
        padding: 1px 2px 3px 4px;
        content:  "\f00c";
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    }
    .user-submit{

    }
    .icon-question-sign{
        cursor: pointer;
    }
    .help-callcenter {
        background-color: #F5DEB3;
        box-shadow: 2px 2px 2px -1px;
        display: block;
        float: left;
        margin-left: 241px;
        margin-top: -12px;
        padding: 10px;
        position: absolute;
    }
</style>