<h3 class="header smaller lighter blue">List Users</h3>
<div role="grid" class="dataTables_wrapper" id="sample-table-2_wrapper">
    <div class="row-fluid">
        <div class="span6">
            <div id="sample-table-2_length" class="dataTables_length">
                <label>
                    Display 
                    <select name="sample-table-2_length" size="1" aria-controls="sample-table-2">
                        <option value="10" selected="selected">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    records
                </label>
            </div>
        </div>
        <div class="span6">
            <div class="dataTables_filter" id="sample-table-2_filter"><label>Search: <input type="text" aria-controls="sample-table-2"></label></div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-2" aria-describedby="sample-table-2_info">
        <thead>
            <tr role="row">
                <th class="center sorting_disabled" role="columnheader" rowspan="1" colspan="1" style="width: 51px;" aria-label="
                    ">
                    <label>
                        <input type="checkbox">
                        <span class="lbl"></span>
                    </label>
                </th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 154px;" aria-label="Domain: activate to sort column ascending">Id</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 111px;" aria-label="Price: activate to sort column ascending">Nombre</th>
                <th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 121px;" aria-label="Clicks: activate to sort column ascending">Apellido</th>
                <th class="hidden-phone sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 181px;" aria-label="Update: activate to sort column ascending">Email</th>
                <th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" style="width: 150px;" aria-label="Status: activate to sort column ascending">Tipo</th>
                <th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" style="width: 146px;" aria-label=""></th>
            </tr>
        </thead>
        <tbody role="alert" aria-live="polite" aria-relevant="all">
            <?php $currentPageRange = $this->paginator->getCurrentPageNumber(); ?>
            <?php $pageRange = $this->paginator->getPageRange(); ?>
            <?php $end = $pageRange * $currentPageRange; ?>
            <?php $start = ($end - $pageRange) + 1; ?>
            <?php $count = 1; ?>
            <?php foreach ($this->usuarios as $usuario): ?>
                <?php if ($count >= $start && $count <= $end): ?>
                    <tr class="<?php echo ($count % 2 == 0) ? "odd" : "even"; ?>">
                        <td class="center  sorting_1">
                            <label>
                                <input type="checkbox">
                                <span class="lbl"></span>
                            </label>
                        </td>
                        <td class=" ">
                            <a href="#"><?php echo $usuario->getId(); ?></a>
                        </td>
                        <td class=" "><?php echo $usuario->getNombre(); ?></td>
                        <td class="hidden-480 "><?php echo $usuario->getApellido(); ?></td>
                        <td class="hidden-480 "><?php echo $usuario->getEmail(); ?></td>
                        <td class="hidden-480 ">
                            <?php echo $usuario->getTipo(); ?>
                        </td>
                        <td class="td-actions ">
                            <div class="hidden-phone visible-desktop action-buttons">
                                <a href="<?php echo $this->basePath("usuarios/usuario/edit") ?>?id=<?php echo $usuario->getId() ?>" class="green">
                                    <i class="icon-pencil bigger-130"></i>
                                </a>
                                <a href="<?php echo $this->url("usuarios",array("controller"=>"usuario","action"=>"delete")) ?>/<?php echo $usuario->getId(); ?>" class="red remove" value="<?php echo $usuario->getId(); ?>">
                                    <i class="icon-trash bigger-130"></i>
                                </a>
                            </div>
                            <div class="hidden-desktop visible-phone">
                                <div class="inline position-relative">
                                    <button data-toggle="dropdown" class="btn btn-minier btn-yellow dropdown-toggle">
                                        <i class="icon-caret-down icon-only bigger-120"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-icon-only dropdown-yellow pull-right dropdown-caret dropdown-close">
                                        <li>
                                            <a title="" data-rel="tooltip" class="tooltip-info" href="#" data-original-title="View">
                                                <span class="blue">
                                                    <i class="icon-zoom-in bigger-120"></i>
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a title="" data-rel="tooltip" class="tooltip-success" href="#" data-original-title="Edit">
                                                <span class="green">
                                                    <i class="icon-edit bigger-120"></i>
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a title="" data-rel="tooltip" class="tooltip-error" href="#" data-original-title="Delete">
                                                <span class="red">
                                                    <i class="icon-trash bigger-120"></i>
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php $count++; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="row-fluid">
        <div class="span6">
            <div class="dataTables_info" id="sample-table-2_info">Showing 1 to 10 of 23 entries</div>
        </div>
        <div class="span6">
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                    'sliding',
                    // the partial to use to render the control
                    array('partial/paginator.phtml', 'Album'),
                    // the route to link to when a user clicks a control link
                    array(
                'ruta' => 'list'
                    )
            );
            ?>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(".remove").click(function(e){
            e.preventDefault();
            var href = $(this).attr('href');
            jConfirm('Are you sure you want to remove this user?', 'Delete?', function (ans) {
                if (ans){
                    window.location = href;
                }
            });
        });
    })
</script>