<?php
//$this->layout()->setTemplate('usuarios/usuario/profile.phtml');

$usuario = new \Usuarios\Model\Entity\Usuario();
$usuario = $this->usuario;
if (!$usuario) {
    if (isset($_SESSION["miSession"]["usuario"])) {
        $usuario = $_SESSION["miSession"]["usuario"];
    }
}


//$alertas = $this->alertas->getAlertasUsuario($usuario->getId());
//$mensajes = $this->mensajes->getMensajesUsuario($usuario->getId());
//$totalAlertas = count($alertas);
//$totalMensajes = count($mensajes);
?>


                        <form class="form-horizontal" action="<?php echo $this->basePath() ?>/usuarios/login/modificarusuario" method="post">
                        <!--<div class="tabbable">

                            <div class="tab-content profile-edit-tab-content">
                                <div id="edit-basic" class="tab-pane in active">-->
                                    
                                <!--Nuevo-->
                                <div class="title-wizard">
                                    <div class="col-lg-12">
                                        <h>Perfil del Usuario</h>
                                    </div>
                                </div>

                                <div class="title-bar-wizard ">
                                    <div class="col-lg-12">
                                        <h>General</h>
                                    </div>
                                </div>

                                <div class= "perfil-container">


                                    <h class="title-tesis">Datos Personales</h> 

                                    <div class="col-lg-6 col-xs-12">

                                        <div class="form-perfil ">
                                            <div class="col-lg-4 text-perfil">Nombre</div>
                                            <div class="col-lg-8">
                                                <input class="form-control" name="nom" value="<?php echo $usuario->getNombre() ?>" type="text" id="form-field-pass1" placeholder="Edgar">
                                            </div>
                                        </div>

                                        <div class=" form-perfil">
                                            <div class="col-lg-4 text-perfil">Apellido</div>
                                            <div class="col-lg-8">
                                                <input class="form-control" name="apellido" value="<?php echo $usuario->getApellido() ?>" type="text" id="form-field-pass1">
                                            </div>
                                        </div>

                                        <div class=" form-perfil">
                                            <div class="col-lg-4 text-perfil">E-mail</div>
                                            <div class="col-lg-8">
                                                <input class="form-control" name="email"  value="<?php echo $usuario->getEmail() ?>" type="email" id="form-field-pass1">
                                            </div>
                                        </div>

                                    </div>


                                    <div class="col-lg-5 col-xs-6 avatar">

                                        <!--<div class="col-lg-7 col-xs-6 user-photo">-->
                                            <div class="widget-main">
                                                <?php if ($usuario->getAvatar()): ?>
                                                    <img style="max-width:170px;" class="imagen-control" src="data:image/jpeg;base64,<?php echo base64_encode($usuario->getAvatar()); ?>">
                                                <?php endif; ?>
                                                <div class="col-lg-2 col-xs-6 col-photo">
                                                    <a class="btn btn-yellow pull-right btn-photo" >Cambiar Foto</a>
                                                </div>
                                                <input 
                                                    estado=""
                                                    type="file" 
                                                    id_input="" 
                                                    tipo="" 
                                                    id_pagina=""  
                                                    name="avatar" 
                                                    class="control id-input-file" <?php //echo ($input->getRequired()) ? "required='required'" : ""  ?> 
                                                    onchange=""
                                                    />
                                            </div>
                                        <!--</div>-->
                                    </div>

                                    </br>
                                    </br>


                                    <h class="title-tesis">Cambiar Contraseña</h> 

                                    <div class=" form-perfil col-lg-6 ">
                                        <div class="col-lg-4 text-perfil">Nueva Contraseña</div>
                                        <div class="col-lg-8">
                                            <input class="form-control" id="form" placeholder="●●●●●●●●●●●"  name="password" type="password" id="form-field-pass1"></div>
                                    </div>

                                    <div class=" form-perfil col-lg-6 ">
                                        <div class="col-lg-4 text-perfil">Confirmar Contraseña</div>
                                        <div class="col-lg-8">
                                            <input class="form-control" name="repassword" type="password" id="form-field-pass2" placeholder="●●●●●●●●●●●"  type="password"></div>
                                    </div>                                                                                                                                                                           

                                </div>

                                <button id="btn-guardar" class="btn btn-yellow btn-end pull-right" >Guardar</button>
                                <button type="reset" class="btn btn-cancel btn-end pull-right" >Resetear</button>
                                <!-- Fin Nuevo -->
                            <!--</div>
                        </div>

                        <div class="form-actions">
                            <button class="btn btn-info" type="button">
                                <i class="icon-ok bigger-110"></i>
                                Save
                            </button>

                            &nbsp; &nbsp; &nbsp;
                            <button class="btn" type="reset">
                                <i class="icon-undo bigger-110"></i>
                                Reset
                            </button>
                        </div>-->
                        </form>
                    
<script type="text/javascript">
    $(function () {

        //editables on first profile page
        $.fn.editable.defaults.mode = 'inline';
        $.fn.editableform.loading = "<div class='editableform-loading'><i class='light-blue icon-2x icon-spinner icon-spin'></i></div>";
        $.fn.editableform.buttons = '<button type="submit" class="btn btn-info editable-submit"><i class="icon-ok icon-white"></i></button>' +
                '<button type="button" class="btn editable-cancel"><i class="icon-remove"></i></button>';

        //editables 
        $('#username').editable({
            type: 'text',
            name: 'username'
        });

        var countries = [];
        $.each({"CA": "Canada", "IN": "India", "NL": "Netherlands", "TR": "Turkey", "US": "United States"}, function (k, v) {
            countries.push({id: k, text: v});
        });

        var cities = [];
        cities["CA"] = [];
        $.each(["Toronto", "Ottawa", "Calgary", "Vancouver"], function (k, v) {
            cities["CA"].push({id: v, text: v});
        });
        cities["IN"] = [];
        $.each(["Delhi", "Mumbai", "Bangalore"], function (k, v) {
            cities["IN"].push({id: v, text: v});
        });
        cities["NL"] = [];
        $.each(["Amsterdam", "Rotterdam", "The Hague"], function (k, v) {
            cities["NL"].push({id: v, text: v});
        });
        cities["TR"] = [];
        $.each(["Ankara", "Istanbul", "Izmir"], function (k, v) {
            cities["TR"].push({id: v, text: v});
        });
        cities["US"] = [];
        $.each(["New York", "Miami", "Los Angeles", "Chicago", "Wysconsin"], function (k, v) {
            cities["US"].push({id: v, text: v});
        });

        var currentValue = "NL";
        $('#country').editable({
            type: 'select2',
            value: 'NL',
            source: countries,
            success: function (response, newValue) {
                if (currentValue == newValue)
                    return;
                currentValue = newValue;

                var source = (!newValue || newValue == "") ? [] : cities[newValue];
                $('#city').editable('destroy').editable({
                    type: 'select2',
                    source: source
                }).editable('setValue', null);
            }
        });

        $('#city').editable({
            type: 'select2',
            value: 'Amsterdam',
            source: cities[currentValue]
        });



        $('#signup').editable({
            type: 'date',
            format: 'yyyy-mm-dd',
            viewformat: 'dd/mm/yyyy',
            datepicker: {
                weekStart: 1
            }
        });

        $('#age').editable({
            type: 'spinner',
            name: 'age',
            spinner: {
                min: 16, max: 99, step: 1
            }
        });

        //var $range = document.createElement("INPUT");
        //$range.type = 'range';
        $('#login').editable({
            type: 'slider', //$range.type == 'range' ? 'range' : 'slider',
            name: 'login',
            slider: {
                min: 1, max: 50, width: 100
            },
            success: function (response, newValue) {
                if (parseInt(newValue) == 1)
                    $(this).html(newValue + " hour ago");
                else
                    $(this).html(newValue + " hours ago");
            }
        });

        $('#about').editable({
            mode: 'inline',
            type: 'wysiwyg',
            name: 'about',
            wysiwyg: {
                //css : {'max-width':'300px'}
            },
            success: function (response, newValue) {
            }
        });



        // *** editable avatar *** //
        try {//ie8 throws some harmless exception, so let's catch it

            //it seems that editable plugin calls appendChild, and as Image doesn't have it, it causes errors on IE at unpredicted points
            //so let's have a fake appendChild for it!
            if (/msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()))
                Image.prototype.appendChild = function (el) {
                }

            var last_gritter
            $('#avatar').editable({
                type: 'image',
                name: 'avatar',
                value: null,
                image: {
                    //specify ace file input plugin's options here
                    btn_choose: 'Change Avatar',
                    droppable: true,
                    /**
                     //this will override the default before_change that only accepts image files
                     before_change: function(files, dropped) {
                     return true;
                     },
                     */

                    //and a few extra ones here
                    name: 'avatar', //put the field name here as well, will be used inside the custom plugin
                    max_size: 110000, //~100Kb
                    on_error: function (code) {//on_error function will be called when the selected file has a problem
                        if (last_gritter)
                            $.gritter.remove(last_gritter);
                        if (code == 1) {//file format error
                            last_gritter = $.gritter.add({
                                title: 'File is not an image!',
                                text: 'Please choose a jpg|gif|png image!',
                                class_name: 'gritter-error gritter-center'
                            });
                        } else if (code == 2) {//file size rror
                            last_gritter = $.gritter.add({
                                title: 'File too big!',
                                text: 'Image size should not exceed 100Kb!',
                                class_name: 'gritter-error gritter-center'
                            });
                        }
                        else {//other error
                        }
                    },
                    on_success: function () {
                        $.gritter.removeAll();
                    }
                },
                url: function (params) {
                    // ***UPDATE AVATAR HERE*** //
                    //You can replace the contents of this function with examples/profile-avatar-update.js for actual upload


                    var deferred = new $.Deferred

                    //if value is empty, means no valid files were selected
                    //but it may still be submitted by the plugin, because "" (empty string) is different from previous non-empty value whatever it was
                    //so we return just here to prevent problems
                    var value = $('#avatar').next().find('input[type=hidden]:eq(0)').val();
                    if (!value || value.length == 0) {
                        deferred.resolve();
                        return deferred.promise();
                    }


                    //dummy upload
                    setTimeout(function () {
                        if ("FileReader" in window) {
                            //for browsers that have a thumbnail of selected image
                            var thumb = $('#avatar').next().find('img').data('thumb');
                            if (thumb)
                                $('#avatar').get(0).src = thumb;
                        }

                        deferred.resolve({'status': 'OK'});

                        if (last_gritter)
                            $.gritter.remove(last_gritter);
                        last_gritter = $.gritter.add({
                            title: 'Avatar Updated!',
                            text: 'Uploading to server can be easily implemented. A working example is included with the template.',
                            class_name: 'gritter-info gritter-center'
                        });

                    }, parseInt(Math.random() * 800 + 800))

                    return deferred.promise();
                },
                success: function (response, newValue) {
                }
            })
        } catch (e) {
        }



        //another option is using modals
        $('#avatar2').on('click', function () {
            var modal =
                    '<div class="modal hide fade">\
                                                <div class="modal-header">\
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>\
                                                        <h4 class="blue">Change Avatar</h4>\
                                                </div>\
                                                \
                                                <form class="no-margin">\
                                                <div class="modal-body">\
                                                        <div class="space-4"></div>\
                                                        <div style="width:75%;margin-left:12%;"><input type="file" name="file-input" /></div>\
                                                </div>\
                                                \
                                                <div class="modal-footer center">\
                                                        <button type="submit" class="btn btn-small btn-success"><i class="icon-ok"></i> Submit</button>\
                                                        <button type="button" class="btn btn-small" data-dismiss="modal"><i class="icon-remove"></i> Cancel</button>\
                                                </div>\
                                                </form>\
                                        </div>';


            var modal = $(modal);
            modal.modal("show").on("hidden", function () {
                modal.remove();
            });

            var working = false;

            var form = modal.find('form:eq(0)');
            var file = form.find('input[type=file]').eq(0);
            file.ace_file_input({
                style: 'well',
                btn_choose: 'Click to choose new avatar',
                btn_change: null,
                no_icon: 'icon-picture',
                thumbnail: 'small',
                before_remove: function () {
                    //don't remove/reset files while being uploaded
                    return !working;
                },
                before_change: function (files, dropped) {
                    var file = files[0];
                    if (typeof file === "string") {
                        //file is just a file name here (in browsers that don't support FileReader API)
                        if (!(/\.(jpe?g|png|gif)$/i).test(file))
                            return false;
                    }
                    else {//file is a File object
                        var type = $.trim(file.type);
                        if ((type.length > 0 && !(/^image\/(jpe?g|png|gif)$/i).test(type))
                                || (type.length == 0 && !(/\.(jpe?g|png|gif)$/i).test(file.name))//for android default browser!
                                )
                            return false;

                        if (file.size > 110000) {//~100Kb
                            return false;
                        }
                    }

                    return true;
                }
            });

            form.on('submit', function () {
                if (!file.data('ace_input_files'))
                    return false;

                file.ace_file_input('disable');
                form.find('button').attr('disabled', 'disabled');
                form.find('.modal-body').append("<div class='center'><i class='icon-spinner icon-spin bigger-150 orange'></i></div>");

                var deferred = new $.Deferred;
                working = true;
                deferred.done(function () {
                    form.find('button').removeAttr('disabled');
                    form.find('input[type=file]').ace_file_input('enable');
                    form.find('.modal-body > :last-child').remove();

                    modal.modal("hide");

                    var thumb = file.next().find('img').data('thumb');
                    if (thumb)
                        $('#avatar2').get(0).src = thumb;

                    working = false;
                });


                setTimeout(function () {
                    deferred.resolve();
                }, parseInt(Math.random() * 800 + 800));

                return false;
            });

        });



        //////////////////////////////
        $('#profile-feed-1').slimScroll({
            height: '250px',
            alwaysVisible: true
        });

        $('.profile-social-links > a').tooltip();

        $('.easy-pie-chart.percentage').each(function () {
            var barColor = $(this).data('color') || '#555';
            var trackColor = '#E2E2E2';
            var size = parseInt($(this).data('size')) || 72;
            $(this).easyPieChart({
                barColor: barColor,
                trackColor: trackColor,
                scaleColor: false,
                lineCap: 'butt',
                lineWidth: parseInt(size / 10),
                animate: false,
                size: size
            }).css('color', barColor);
        });

        ///////////////////////////////////////////


        $("#btn-guardar").click(function () {
            $("form").submit();
        })

        ///////////////////////////////////////////
        $('#user-profile-3')
                .find('input[type=file]').ace_file_input({
            style: 'well',
            btn_choose: 'Change avatar',
            btn_change: null,
            no_icon: 'icon-picture',
            thumbnail: 'large',
            droppable: true,
            before_change: function (files, dropped) {
                var file = files[0];
                if (typeof file === "string") {//files is just a file name here (in browsers that don't support FileReader API)
                    if (!(/\.(jpe?g|png|gif)$/i).test(file))
                        return false;
                }
                else {//file is a File object
                    var type = $.trim(file.type);
                    if ((type.length > 0 && !(/^image\/(jpe?g|png|gif)$/i).test(type))
                            || (type.length == 0 && !(/\.(jpe?g|png|gif)$/i).test(file.name))//for android default browser!
                            )
                        return false;

                    if (file.size > 110000) {//~100Kb
                        return false;
                    }
                }

                return true;
            }
        })
                .end().find('button[type=reset]').on(ace.click_event, function () {
            $('#user-profile-3 input[type=file]').ace_file_input('reset_input');
        })
                .end().find('.date-picker').datepicker().next().on(ace.click_event, function () {
            $(this).prev().focus();
        })
        $('.input-mask-phone').mask('(999) 999-9999');



        ////////////////////
        //change profile
        $('[data-toggle="buttons-radio"]').on('click', function (e) {
            var target = $(e.target);
            var which = parseInt($.trim(target.text()));
            $('.user-profile').parent().hide();
            $('#user-profile-' + which).parent().show();
        });
        
        $(".btn-photo").click(function(){
           $("input[type=file]").trigger("click"); 
        });
    });
</script>
<style>
    
.perfil-container{
    font-size: 16px;
    padding-top: 20px;
    padding-bottom: 20px;
    margin-bottom: 10px;
    background-color: #fff;
    min-height: 550px;
    }


.personal{
    padding: 40px;
}


.avatar{
    padding: 15px;
}

.form-perfil {
    height: 40px;
    margin: 25px 10px 25px 10px;
    padding: 10px;
}


.text-perfil {
    text-align: left;
    padding: 2px 0px 2px 25px;
}


.user-photo {
    padding: 20px;
    padding-left: 40px;
    display: block;
    max-width: 100%;
    height: auto;

}

.btn-photo {
    margin: 20px;
    display: block;
}
.col-photo{
    float:right;
}
.btn-photo{
    margin-top:0;
}
input[type=file]{
    opacity: 0;
}
</style>